all:
	tasm -07 -b spc.asm spc.obj
	../size spc.obj
	wla music
	snes music.smc
#	zsnes music.smc
spc:
	tasm -07 -b spc.asm spc.obj
	../size spc.obj
	../size sound.brr
asm:
	wla music
	snes music.smc
#	zsnes music.smc
