all:
	tasm -07 -b spc2.asm spc.obj
	size spc.obj
	wla main
#	snes main.smc
#	zsnes music.smc
spc:
	tasm -07 -b spc2.asm spc.obj
	size spc.obj
	#size piano.brr
asm:
	wla music
#	snes music.smc
#	zsnes music.smc
