Meatball: Collision.cpp File Reference
Collision.cpp File Reference
#include "Collision.h"
#include "sprite.h"
#include "level.h"
#include "enemy.h"
#include "player.h"
Functions
void CollideMove (cBasicSprite *Sprite, double velx, double vely, Collisiondata *Collision, unsigned int type)
Returns the Collision data if a Collision happened.
void CollideMove_Meatball (cBasicSprite *Sprite, double velx, double vely, Collisiondata *Collision, unsigned int type)
void PositionCheck (int x, int y, int width, int height, Collisiondata *Collision, unsigned int type)
Checks if the given position is valid if the Position is not valid it returns the direction.
int GetCollide (SDL_Rect *r1, SDL_Rect *r2)
Returns the collision direction.
Variables
cLevel * pLevel
cPlayer * pPlayer
Function Documentation
void CollideMove (cBasicSprite * Sprite, double velx, double vely, Collisiondata * Collision, unsigned int type)
Returns the Collision data if a Collision happened.
The direction of all Collisions
-1 = No Collision detected
1 = Collision Up/Down/Left/Right
2 = Collision in Left/Right
3 = Collision Up/Down
Definition at line 12 of file Collision.cpp.
References ALL_COLLISIONS_LR, ALL_COLLISIONS_NONE, ALL_COLLISIONS_UD, ALL_COLLISIONS_UDLR, Collisiondata::collide, Collisiondata::direction, DOWN, cBasicSprite::height, Collisiondata::iCollisionNumber, Collisiondata::iCollisionType, LEFT, PositionCheck(), cBasicSprite::posx, cBasicSprite::posy, RIGHT, SPRITE_TYPE_BULLET, UP, cVelocitySprite::velx, cVelocitySprite::vely, and cBasicSprite::width.
Referenced by cMParticleEmitter::Update(), UpdateBullets(), and UpdateEnemies().
void CollideMove_Meatball (cBasicSprite * Sprite, double velx, double vely, Collisiondata * Collision, unsigned int type)
Definition at line 149 of file Collision.cpp.
References ALL_COLLISIONS_LR, ALL_COLLISIONS_NONE, ALL_COLLISIONS_UD, ALL_COLLISIONS_UDLR, Collisiondata::collide, cMVelSprite::Collision, Collisiondata::direction, DOWN, cBasicSprite::height, Collisiondata::iCollisionNumber, Collisiondata::iCollisionType, LEFT, PositionCheck(), cBasicSprite::posx, cBasicSprite::posy, RIGHT, UP, cVelocitySprite::velx, and cVelocitySprite::vely.
Referenced by UpdatePlayer().
int GetCollide (SDL_Rect * r1, SDL_Rect * r2)
Returns the collision direction.
Definition at line 412 of file Collision.cpp.
References DOWN, LEFT, RIGHT, and UP.
Referenced by PositionCheck().
void PositionCheck (int x, int y, int width, int height, Collisiondata * Collision, unsigned int type)
Checks if the given position is valid if the Position is not valid it returns the direction.
Definition at line 322 of file Collision.cpp.
References cLevelData::BasicSprites, Collisiondata::collide, Collisiondata::cRect, Enemies, GetCollide(), Collisiondata::iCollisionNumber, Collisiondata::iCollisionType, ObjectManager< T >::objcount, ObjectManager< T >::objects, cLevel::pLevelData_Layer1, cBasicSprite::rect, RectIntersect(), SetRect(), SPRITE_TYPE_BULLET, SPRITE_TYPE_ENEMY, SPRITE_TYPE_HALFMASSIVE, SPRITE_TYPE_MASSIVE, SPRITE_TYPE_PARTICLE, SPRITE_TYPE_PLAYER, and cMVelSprite::type.
Referenced by cAF373::AI_PlayerSearch(), CollideMove(), CollideMove_Meatball(), cAF373::Update(), and cPlayer::Update().
Variable Documentation
cLevel* pLevel
Definition at line 19 of file main.cpp.
Referenced by QuitGame().
cPlayer* pPlayer
Definition at line 18 of file main.cpp.