Meatball: OptionsMenu.cpp File Reference
OptionsMenu.cpp File Reference
#include "OptionsMenu.h"
#include "MainMenu.h"
Functions
void playSoundEffect ()
Variables
cPreferences * pPreferences
SDL_bool mouse_alreadypressed =SDL_FALSE
int channel =0
Function Documentation
void playSoundEffect ()
Definition at line 10 of file OptionsMenu.cpp.
References channel, cSoundManager::GetPointer(), pAudio, cAudio::PlaySound(), and SMan.
Referenced by OptionsMenu::Update().
Variable Documentation
int channel =0
Definition at line 9 of file OptionsMenu.cpp.
Referenced by playSoundEffect().
SDL_bool mouse_alreadypressed =SDL_FALSE
Definition at line 7 of file OptionsMenu.cpp.