Meatball: ObjectManager< T > Class Template Reference
ObjectManager< T > Class Template Reference
#include <include/ObjectManager.h>
Public Member Functions
ObjectManager (SDL_bool delete_at_destroy=OM_SAVE_OBJS_AT_DESTROY, SDL_bool delete_or_free=OM_DELETE_OBJS)
~ObjectManager ()
virtual void add (T *)
void RemoveAllObjects ()
Remove from OM but don't delete from memory.
int hasa (T *)
void Remove (int n)
void DeleteAllObjectContents ()
uses Delete instead of Free()
void FreeAllObjectContents ()
uses free();
Public Attributes
SDL_bool obliterate_objects_at_destructor
this sets to only delete the manager of the objects/ or should we also delete the objects too???
unsigned int objcount
SDL_bool delete_or_free_objects
delete them or free them? (depends of new was used or SDL_malloc-equiv)
T ** objects
Detailed Description
template<class T>
class ObjectManager< T >
Definition at line 18 of file ObjectManager.h.
Constructor & Destructor Documentation
template<class T> ObjectManager< T >::ObjectManager (SDL_bool delete_at_destroy = OM_SAVE_OBJS_AT_DESTROY, SDL_bool delete_or_free = OM_DELETE_OBJS) inline
Definition at line 21 of file ObjectManager.h.
template<class T> ObjectManager< T >::~ObjectManager () inline
Definition at line 27 of file ObjectManager.h.
Referenced by cLevelData::~cLevelData().
Member Function Documentation
template<class T> void ObjectManager< T >::add (T * new_obj) virtual
Definition at line 106 of file ObjectManager.h.
Referenced by cLevelData::AddSprite(), CmdAddAlias(), cMultiSelect::GetAllCollidingObjects(), cLevelData::GetAllCollidingSpriteNum(), Push(), and cMultiSelect::SetObject().
template<class T > void ObjectManager< T >::DeleteAllObjectContents ()
uses Delete instead of Free()
Definition at line 126 of file ObjectManager.h.
References DEBUGLOG.
Referenced by ObjectManager< string >::~ObjectManager().
template<class T > void ObjectManager< T >::FreeAllObjectContents ()
uses free();
Definition at line 144 of file ObjectManager.h.
References DEBUGLOG.
Referenced by ObjectManager< string >::~ObjectManager().
template<class T> int ObjectManager< T >::hasa (T * o)
Definition at line 79 of file ObjectManager.h.
Referenced by cLevelEditor::EventHandler(), cMultiSelect::GetAllCollidingObjects(), cLevelData::GetAllCollidingSpriteNum(), and cMultiSelect::SetObject().
template<class T > void ObjectManager< T >::Remove (int n)
Definition at line 94 of file ObjectManager.h.
Referenced by cMultiSelect::SetObject().
template<class T > void ObjectManager< T >::RemoveAllObjects ()
Remove from OM but don't delete from memory.
Definition at line 115 of file ObjectManager.h.
Referenced by cLevelEditor::EventHandler(), and cMultiSelect::Release().
Member Data Documentation
template<class T> SDL_bool ObjectManager< T >::delete_or_free_objects
delete them or free them? (depends of new was used or SDL_malloc-equiv)
Definition at line 62 of file ObjectManager.h.
Referenced by ObjectManager< string >::~ObjectManager().
template<class T> unsigned int ObjectManager< T >::objcount
Definition at line 61 of file ObjectManager.h.
Referenced by cLevel::Draw(), cMultiSelect::DrawOutlineAroundMultiSelect_Tiles(), cConsole::FindMatch(), cLevelData::GetAllCollidingSpriteNum(), cLevelData::GetCollidingSprite(), cLevelData::GetCollidingSpriteNum(), help(), cMultiSelect::Move(), ObjectManager< string >::ObjectManager(), PositionCheck(), cLevel::SaveMapObjects(), cMultiSelect::SetObjects(), and ObjectManager< string >::~ObjectManager().
template<class T> T** ObjectManager< T >::objects
Definition at line 64 of file ObjectManager.h.
Referenced by cLevelData::DeleteSprite(), cLevel::Draw(), cMultiSelect::DrawOutlineAroundMultiSelect_Tiles(), cConsole::FindMatch(), cLevelData::GetAllCollidingSpriteNum(), cLevelEditor::GetCollidingObject(), cLevelData::GetCollidingSprite(), cLevelData::GetCollidingSpriteNum(), help(), cMultiSelect::Move(), ObjectManager< string >::ObjectManager(), PositionCheck(), cLevel::SaveMapObjects(), and ObjectManager< string >::~ObjectManager().
template<class T> SDL_bool ObjectManager< T >::obliterate_objects_at_destructor
this sets to only delete the manager of the objects/ or should we also delete the objects too???
Definition at line 60 of file ObjectManager.h.
Referenced by ObjectManager< string >::ObjectManager(), and ObjectManager< string >::~ObjectManager().
The documentation for this class was generated from the following file:
include/ObjectManager.h