Meatball: cLevelEditor Class Reference
cLevelEditor Class Reference
Level Editor
The Leveleditor as an ingame implementation.
#include <include/leveleditor.h>
Public Member Functions
cLevelEditor (void)
~cLevelEditor (void)
void HeldKey_Handler ()
void HeldKey_fastcopy ()
void HeldKey_movecamera ()
void EventHandler ()
void Draw ()
void Draw (SDL_Renderer *renderer)
void Update (void)
Updates all the Leveleditor stuff.
void SetCopyObject (cMVelSprite *nObject)
Draws all the Leveleditor stuff.
void SetCopyObject (void)
void SetMoveObject (cMVelSprite *nObject)
Sets an Object for Mouse Movement.
void SetMoveObject (void)
void OutlineHoveredObject (SDL_Renderer *renderer, Uint32 Color)
Draw the outline of the hovered Object.
void PasteObject (void)
Paste's an Object if SetCopyObject was set.
void PasteObject (double x, double y)
Paste's an Object on the given position if SetCopyObject was set.
void DeleteObject (void)
Delete's an Object.
void DeleteObject (double x, double y)
Delete's an Object on the given position.
void SetFastCopyObject (cMVelSprite *nObject)
Sets the to-be-FastCopied Object.
void SetFastCopyObject (void)
void Release_Command (void)
Releases every command.
cMVelSprite * GetCollidingObject (double x, double y)
Gets the Current Colliding Object types : the Objects which should be checked look at the Editor type defines.
Public Member Functions inherited from MiniEngine
virtual void PreUpdate (void)
Does general things.
virtual void PostUpdate (void)
virtual void PreDraw (void)
virtual void PostDraw (void)
virtual void Do ()
virtual void Input ()
Static Public Member Functions
static void OutlineObject (SDL_Renderer *renderer, Uint32 Color, SDL_Rect *orect)
Public Attributes
SDL_Rect HoveredObject
The Object Size which should get Hovered.
cMVelSprite * Object
The currently used object for moving.
cMVelSprite * CopyObject
The Object used for Copying.
cMVelSprite * lastCopiedObject
int Mouse_w
The additional Mouse position when moving.
int Mouse_h
cMultiSelect * MultiSelect
Static Public Attributes
static Uint8 Mouse_command = MOUSE_COMMAND_NOTHING
The Mouse Command (moving,copying etc..)
Detailed Description
The Leveleditor as an ingame implementation.
Definition at line 35 of file leveleditor.h.
Constructor & Destructor Documentation
cLevelEditor::cLevelEditor (void)
Definition at line 30 of file leveleditor.cpp.
References CopyObject, lastCopiedObject, Mouse_command, MOUSE_COMMAND_NOTHING, Mouse_h, Mouse_w, MultiSelect, and Object.
cLevelEditor::~cLevelEditor (void)
Definition at line 44 of file leveleditor.cpp.
References MultiSelect.
Member Function Documentation
void cLevelEditor::DeleteObject (void)
Delete's an Object.
Definition at line 273 of file leveleditor.cpp.
References DEBUGLOG, pMouse, cBasicSprite::posx, and cBasicSprite::posy.
Referenced by EventHandler(), and HeldKey_Handler().
void cLevelEditor::DeleteObject (double x, double y)
Delete's an Object on the given position.
Definition at line 279 of file leveleditor.cpp.
References DEBUGLOG, DeletEnemy(), cLevelData::DeleteSprite(), GetCollidingEnemyNum(), cLevelData::GetCollidingSpriteNum(), cLevel::pLevelData_Layer1, and SetRect().
void cLevelEditor::Draw (void) virtual
Reimplemented from MiniEngine.
Definition at line 111 of file leveleditor.cpp.
References Renderer.
void cLevelEditor::Draw (SDL_Renderer * renderer)
Definition at line 115 of file leveleditor.cpp.
References cPlayer::Draw(), cBasicSprite::Draw(), DrawEnemies(), cMultiSelect::DrawOutlineAroundMultiSelect_Tiles(), FillRectAlpha(), Mouse_command, MOUSE_COMMAND_FASTCOPY, MOUSE_COMMAND_MOVING_MULTISELECT_TILES, MOUSE_COMMAND_SELECT_MULTISELECT_TILES, MultiSelect, MultiSelect_COLOR, OutlineHoveredObject(), pMouse, MiniEngine::PostDraw(), cBasicSprite::posx, cBasicSprite::posy, MiniEngine::PreDraw(), cMultiSelect::rect, cMultiSelect::veryfirst_mouseXOffset, and cMultiSelect::veryfirst_mouseYOffset.
cMVelSprite * cLevelEditor::GetCollidingObject (double x, double y)
Gets the Current Colliding Object types : the Objects which should be checked look at the Editor type defines.
Definition at line 336 of file leveleditor.cpp.
References cLevelData::BasicSprites, Enemies, GetCollidingEnemyNum(), cLevelData::GetCollidingSpriteNum(), cMVelSprite::GetRect(), ObjectManager< T >::objects, cLevel::pLevelData_Layer1, pPlayer, RectIntersect(), and SetRect().
Referenced by EventHandler(), SetCopyObject(), SetMoveObject(), and Update().
void cLevelEditor::HeldKey_fastcopy ()
Definition at line 607 of file leveleditor.cpp.
References CopyObject, cBasicSprite::height, keys, Mouse_command, MOUSE_COMMAND_FASTCOPY, cCamera::Move(), PasteObject(), cBasicSprite::posx, cBasicSprite::posy, cBasicSprite::width, cCamera::x, and cCamera::y.
Referenced by HeldKey_Handler().
void cLevelEditor::HeldKey_Handler () virtual
Move camera functions
Reimplemented from MiniEngine.
Definition at line 667 of file leveleditor.cpp.
References DeleteObject(), HeldKey_fastcopy(), HeldKey_movecamera(), and keys.
void cLevelEditor::HeldKey_movecamera ()
Definition at line 642 of file leveleditor.cpp.
References keys, cCamera::Move(), pFramerate, cFramerate::speedfactor, cCamera::x, and cCamera::y.
Referenced by HeldKey_Handler().
void cLevelEditor::OutlineHoveredObject (SDL_Renderer * renderer, Uint32 Color)
Draw the outline of the hovered Object.
Definition at line 182 of file leveleditor.cpp.
References HoveredObject, and OutlineObject().
Referenced by Draw().
void cLevelEditor::OutlineObject (SDL_Renderer * renderer, Uint32 Color, SDL_Rect * orect) static
Definition at line 159 of file leveleditor.cpp.
References FillRect(), and FillRectAlpha().
Referenced by cMultiSelect::DrawOutlineAroundMultiSelect_Tiles(), and OutlineHoveredObject().
void cLevelEditor::PasteObject (void)
Paste's an Object if SetCopyObject was set.
Definition at line 237 of file leveleditor.cpp.
References pMouse, cBasicSprite::posx, and cBasicSprite::posy.
Referenced by EventHandler(), and HeldKey_fastcopy().
void cLevelEditor::PasteObject (double x, double y)
Paste's an Object on the given position if SetCopyObject was set.
Definition at line 242 of file leveleditor.cpp.
References AddEnemy(), cLevelData::AddSprite(), CopyObject, cEnemy::Enemy_type, lastCopiedObject, Mouse_command, MOUSE_COMMAND_FASTCOPY, cLevel::pLevelData_Layer1, SetFastCopyObject(), SPRITE_TYPE_ENEMY, SPRITE_TYPE_HALFMASSIVE, SPRITE_TYPE_MASSIVE, SPRITE_TYPE_PASSIVE, cBasicSprite::srcimage, cMVelSprite::type, cCamera::x, and cCamera::y.
void cLevelEditor::Release_Command (void)
Releases every command.
Definition at line 321 of file leveleditor.cpp.
References CopyObject, Mouse_command, MOUSE_COMMAND_FASTCOPY, MOUSE_COMMAND_NOTHING, and Object.
Referenced by EventHandler().
void cLevelEditor::SetCopyObject (cMVelSprite * nObject)
Draws all the Leveleditor stuff.
Sets the to-be-Copied Object
Definition at line 188 of file leveleditor.cpp.
References CopyObject, SPRITE_TYPE_PLAYER, and cMVelSprite::type.
void cLevelEditor::SetCopyObject (void)
Definition at line 204 of file leveleditor.cpp.
References GetCollidingObject(), pMouse, cBasicSprite::posx, and cBasicSprite::posy.
Referenced by EventHandler(), and SetFastCopyObject().
void cLevelEditor::SetFastCopyObject (cMVelSprite * nObject)
Sets the to-be-FastCopied Object.
Definition at line 307 of file leveleditor.cpp.
References Mouse_command, MOUSE_COMMAND_FASTCOPY, and SetCopyObject().
void cLevelEditor::SetFastCopyObject (void)
Definition at line 314 of file leveleditor.cpp.
References Mouse_command, MOUSE_COMMAND_FASTCOPY, and SetCopyObject().
Referenced by EventHandler(), and PasteObject().
void cLevelEditor::SetMoveObject (cMVelSprite * nObject)
Sets an Object for Mouse Movement.
Definition at line 214 of file leveleditor.cpp.
References Mouse_command, MOUSE_COMMAND_MOVING_SINGLE_TILE, Mouse_h, Mouse_w, Object, pMouse, cBasicSprite::posx, cBasicSprite::posy, cCamera::x, and cCamera::y.
void cLevelEditor::SetMoveObject (void)
Definition at line 229 of file leveleditor.cpp.
References GetCollidingObject(), pMouse, cBasicSprite::posx, and cBasicSprite::posy.
Referenced by EventHandler().
void cLevelEditor::Update (void) virtual
Updates all the Leveleditor stuff.
Reimplemented from MiniEngine.
Definition at line 49 of file leveleditor.cpp.
References GetCollidingObject(), cMVelSprite::GetRect(), HoveredObject, Mouse_command, MOUSE_COMMAND_FASTCOPY, MOUSE_COMMAND_MOVING_MULTISELECT_TILES, MOUSE_COMMAND_MOVING_SINGLE_TILE, MOUSE_COMMAND_NOTHING, MOUSE_COMMAND_SELECT_MULTISELECT_TILES, Mouse_h, Mouse_w, cMultiSelect::Move(), MultiSelect, Object, pMouse, MiniEngine::PostUpdate(), cBasicSprite::posx, cBasicSprite::posy, MiniEngine::PreUpdate(), cMultiSelect::rect, cMultiSelect::rectX_origin, cMultiSelect::rectY_origin, cBasicSprite::SetPos(), SetRect(), cMVelSprite::Startposx, cMVelSprite::Startposy, cCamera::x, and cCamera::y.
Member Data Documentation
cMVelSprite* cLevelEditor::CopyObject
The Object used for Copying.
Definition at line 106 of file leveleditor.h.
Referenced by cLevelEditor(), EventHandler(), HeldKey_fastcopy(), PasteObject(), Release_Command(), and SetCopyObject().
SDL_Rect cLevelEditor::HoveredObject
The Object Size which should get Hovered.
Definition at line 101 of file leveleditor.h.
Referenced by OutlineHoveredObject(), and Update().
cMVelSprite* cLevelEditor::lastCopiedObject
Definition at line 107 of file leveleditor.h.
Referenced by cLevelEditor(), and PasteObject().
Uint8 cLevelEditor::Mouse_command = MOUSE_COMMAND_NOTHING static
The Mouse Command (moving,copying etc..)
Definition at line 110 of file leveleditor.h.
Referenced by cLevelEditor(), Draw(), EventHandler(), HeldKey_fastcopy(), cMultiSelect::InitTiles(), PasteObject(), cMultiSelect::PrepareToMove(), Release_Command(), SetFastCopyObject(), SetMoveObject(), and Update().
int cLevelEditor::Mouse_h
Definition at line 113 of file leveleditor.h.
Referenced by cLevelEditor(), SetMoveObject(), and Update().
int cLevelEditor::Mouse_w
The additional Mouse position when moving.
Definition at line 113 of file leveleditor.h.
Referenced by cLevelEditor(), SetMoveObject(), and Update().
cMultiSelect* cLevelEditor::MultiSelect
Definition at line 115 of file leveleditor.h.
Referenced by cLevelEditor(), Draw(), EventHandler(), Update(), and ~cLevelEditor().
cMVelSprite* cLevelEditor::Object
The currently used object for moving.
Definition at line 104 of file leveleditor.h.
Referenced by cLevelEditor(), Release_Command(), SetMoveObject(), and Update().
The documentation for this class was generated from the following files:
include/leveleditor.h
leveleditor.cpp