Meatball: cConsole Class Reference
cConsole Class Reference
Console
For Live In-game editing to the Game World and Variables.
#include <include/console.h>
Public Member Functions
cConsole (void)
Gets the current working path, Loads the Background image to the Image Manager, Creates the console font, Push() all cCMDs to cConsole::CMDList,.
~cConsole (void)
Delete the Background, close the font, Delete all commands from CMDList.
void EventHandler (void)
Handles console input.
SDL_bool CMDHandler (string cInput)
The Command Handler parses the input line for it's base (command) and it's parameters It then checks with all registered commands for a match If there's a match it will call the registered command's handler function with the parameters as a string argument.
cCMD * FindMatch (string &cmd)
void Update (void)
Updates background, Updates logic to draw the cursor or not (blinking underscore)
void Draw (SDL_Renderer *renderer)
Draws the BG, the input display and history displays, the blinking cursor.
void Draw ()
string ParseBase (string str)
Strips the input line for only the base (first word) Strips by finding the first space character.
string ParseParm (string str)
Finds the parameter by skipping the first word and first space character in the string The rest goes into the Parameter string, which is returned.
SDL_bool helpCMD (string &str)
void ClearHistory_SurfacesAndTextures ()
void BlinkCursor ()
void CreateTextOnSurfaces ()
void SetRects ()
void CreateTexturesAndRender (SDL_Renderer *renderer)
void FreeAllUsedSurfaces ()
Public Member Functions inherited from MiniEngine
virtual void PreUpdate (void)
Does general things.
virtual void PostUpdate (void)
virtual void PreDraw (void)
virtual void PostDraw (void)
virtual void Do ()
virtual void Input ()
virtual void HeldKey_Handler ()
Public Attributes
cCMD * CMDList
string strcpy [NUM_LINES]
string consoleInput_str
int histcounter
fs::path full_path
double consoleInput_x
double consoleInput_y
SDL_bool DrawCur
double ttDrawCur
cBasicSprite * BG
TTF_Font * Console_font
double history_y = topHistoryLine_Y
SDL_Rect consoleInput_rect
SDL_Rect strcpy_rect [11]
SDL_Rect cursor_rect
SDL_Surface * consoleInput_surface
SDL_Texture * consoleInput_tex
SDL_Surface * sc_surface [HISTORY_LINES]
SDL_Texture * sc_tex [HISTORY_LINES]
SDL_Surface * cursor_surface
SDL_Texture * cursor_tex
Detailed Description
For Live In-game editing to the Game World and Variables.
Definition at line 74 of file console.h.
Constructor & Destructor Documentation
cConsole::cConsole (void)
Gets the current working path, Loads the Background image to the Image Manager, Creates the console font, Push() all cCMDs to cConsole::CMDList,.
[Console Commands]
[Console Commands]
Definition at line 38 of file console.cpp.
References cImageManager::Add(), allSoundsVol(), cBasicSprite::cBasicSprite(), cd(), clearcon(), CmdAddAlias(), colorkey, cFont::CreateFont(), FONT_DIR, cImageManager::GetPointer(), help(), HISTORY_LINES, IMan, LoadImage(), loadmap(), ls(), musicVol(), pFont, PIXMAPS_DIR, play(), Push(), QuitAll(), Renderer, SetMx(), SetMxy(), SetMy(), SetScreenScaleX(), SetScreenScaleXY(), SetScreenScaleY(), ShowFPS(), soundVol(), window_height, and window_width.
cConsole::~cConsole (void)
Delete the Background, close the font, Delete all commands from CMDList.
Definition at line 102 of file console.cpp.
References cCMD::next.
Member Function Documentation
void cConsole::BlinkCursor ()
Definition at line 251 of file console.cpp.
References cFont::CreateText(), and pFont.
void cConsole::ClearHistory_SurfacesAndTextures ()
Definition at line 361 of file console.cpp.
References HISTORY_LINES.
SDL_bool cConsole::CMDHandler (string cInput)
The Command Handler parses the input line for it's base (command) and it's parameters It then checks with all registered commands for a match If there's a match it will call the registered command's handler function with the parameters as a string argument.
Returns
SDL_FALSE on no match or base empty.SDL_TRUE on a match
Definition at line 386 of file console.cpp.
References cCMD::handler.
void cConsole::CreateTextOnSurfaces ()
Definition at line 264 of file console.cpp.
References cFont::CreateText(), and pFont.
void cConsole::CreateTexturesAndRender (SDL_Renderer * renderer)
Definition at line 309 of file console.cpp.
void cConsole::Draw (SDL_Renderer * renderer)
Draws the BG, the input display and history displays, the blinking cursor.
Definition at line 225 of file console.cpp.
References cPlayer::Draw(), DrawBullets(), DrawEnemies(), and DrawParticleEmitter().
Referenced by wait_for_input().
void cConsole::Draw (void) virtual
Reimplemented from MiniEngine.
Definition at line 838 of file console.cpp.
References cPlayer::Draw(), and Renderer.
cCMD * cConsole::FindMatch (string & cmd)
Definition at line 408 of file console.cpp.
References cCMD::command, cCMD::next, ObjectManager< T >::objcount, and ObjectManager< T >::objects.
void cConsole::FreeAllUsedSurfaces ()
Definition at line 332 of file console.cpp.
SDL_bool cConsole::helpCMD (string & str)
Definition at line 467 of file console.cpp.
References console_print().
Referenced by help().
string cConsole::ParseBase (string str)
Strips the input line for only the base (first word) Strips by finding the first space character.
Definition at line 436 of file console.cpp.
string cConsole::ParseParm (string str)
Finds the parameter by skipping the first word and first space character in the string The rest goes into the Parameter string, which is returned.
Definition at line 452 of file console.cpp.
void cConsole::SetRects ()
Definition at line 283 of file console.cpp.
References CONSOLE_HISTORY_VERTICAL_SEPERATION_PIXELS, SetRect(), and topHistoryLine_Y.
void cConsole::Update (void) virtual
Updates background, Updates logic to draw the cursor or not (blinking underscore)
Reimplemented from MiniEngine.
Definition at line 203 of file console.cpp.
References Renderer.
Referenced by wait_for_input().
Member Data Documentation
cBasicSprite* cConsole::BG
Definition at line 112 of file console.h.
cCMD* cConsole::CMDList
Definition at line 98 of file console.h.
Referenced by help().
TTF_Font* cConsole::Console_font
Definition at line 114 of file console.h.
SDL_Rect cConsole::consoleInput_rect
Definition at line 118 of file console.h.
string cConsole::consoleInput_str
Definition at line 102 of file console.h.
Referenced by clearcon(), help(), and ls().
SDL_Surface* cConsole::consoleInput_surface
Definition at line 120 of file console.h.
SDL_Texture* cConsole::consoleInput_tex
Definition at line 121 of file console.h.
double cConsole::consoleInput_x
Definition at line 107 of file console.h.
double cConsole::consoleInput_y
Definition at line 107 of file console.h.
SDL_Rect cConsole::cursor_rect
Definition at line 118 of file console.h.
SDL_Surface* cConsole::cursor_surface
Definition at line 124 of file console.h.
SDL_Texture* cConsole::cursor_tex
Definition at line 125 of file console.h.
SDL_bool cConsole::DrawCur
Definition at line 109 of file console.h.
fs::path cConsole::full_path
Definition at line 104 of file console.h.
Referenced by cd(), and ls().
int cConsole::histcounter
Definition at line 103 of file console.h.
Referenced by clearcon().
double cConsole::history_y = topHistoryLine_Y
Definition at line 116 of file console.h.
SDL_Surface* cConsole::sc_surface[HISTORY_LINES]
Definition at line 122 of file console.h.
SDL_Texture* cConsole::sc_tex[HISTORY_LINES]
Definition at line 123 of file console.h.
string cConsole::strcpy[NUM_LINES]
Definition at line 100 of file console.h.
Referenced by clearcon(), console_print(), and moveConsoleHistoryLinesUp().
SDL_Rect cConsole::strcpy_rect[11]
Definition at line 118 of file console.h.
double cConsole::ttDrawCur
Definition at line 110 of file console.h.
The documentation for this class was generated from the following files:
include/console.h
console.cpp