Meatball: cLevelData Class Reference
cLevelData Class Reference
Levels
#include <include/level.h>
Public Member Functions
cLevelData (void)
~cLevelData (void)
void AddSprite (cMVelSprite *Sprite)
Adds an Sprite to the Leveldata.
int GetCollidingSpriteNum (SDL_Rect *Crect)
Gets the first overlapping Collision.
SDL_bool GetAllCollidingSpriteNum (SDL_Rect *Crect, ObjectManager< cMVelSprite > *obj_man)
cBasicSprite * GetCollidingSprite (SDL_Rect *Crect)
void DeleteSprite (unsigned int number)
Delets an given Sprite.
Public Attributes
ObjectManager< cMVelSprite > BasicSprites
The Basic Sprites.
Uint8 BG_red
Background Color.
Uint8 BG_green
Uint8 BG_blue
string Musicfile
Background Image not implemented.
Detailed Description
Definition at line 13 of file level.h.
Constructor & Destructor Documentation
cLevelData::cLevelData (void)
Definition at line 13 of file level.cpp.
References BG_blue, BG_green, BG_red, and Musicfile.
cLevelData::~cLevelData (void)
Definition at line 28 of file level.cpp.
References BasicSprites, and ObjectManager< T >::~ObjectManager().
Member Function Documentation
void cLevelData::AddSprite (cMVelSprite * Sprite)
Adds an Sprite to the Leveldata.
Definition at line 53 of file level.cpp.
References ObjectManager< T >::add(), and BasicSprites.
Referenced by cLevel::ParseLine(), and cLevelEditor::PasteObject().
void cLevelData::DeleteSprite (unsigned int number)
Delets an given Sprite.
Definition at line 133 of file level.cpp.
References BasicSprites, and ObjectManager< T >::objects.
Referenced by cLevelEditor::DeleteObject().
SDL_bool cLevelData::GetAllCollidingSpriteNum (SDL_Rect * Crect, ObjectManager< cMVelSprite > * obj_man)
Definition at line 83 of file level.cpp.
References ObjectManager< T >::add(), BasicSprites, cMVelSprite::GetRect(), ObjectManager< T >::hasa(), ObjectManager< T >::objcount, ObjectManager< T >::objects, and RectIntersect().
Referenced by cMultiSelect::GetAllCollidingObjects().
cBasicSprite * cLevelData::GetCollidingSprite (SDL_Rect * Crect)
Definition at line 112 of file level.cpp.
References BasicSprites, cMVelSprite::GetRect(), ObjectManager< T >::objcount, ObjectManager< T >::objects, and RectIntersect().
int cLevelData::GetCollidingSpriteNum (SDL_Rect * Crect)
Gets the first overlapping Collision.
Definition at line 61 of file level.cpp.
References BasicSprites, cMVelSprite::GetRect(), ObjectManager< T >::objcount, ObjectManager< T >::objects, and RectIntersect().
Referenced by cLevelEditor::DeleteObject(), and cLevelEditor::GetCollidingObject().
Member Data Documentation
ObjectManager<cMVelSprite> cLevelData::BasicSprites
The Basic Sprites.
Basic Sprite Count
Definition at line 23 of file level.h.
Referenced by AddSprite(), DeleteSprite(), cLevel::Draw(), GetAllCollidingSpriteNum(), cLevelEditor::GetCollidingObject(), GetCollidingSprite(), GetCollidingSpriteNum(), PositionCheck(), cLevel::SaveMapObjects(), and ~cLevelData().
Uint8 cLevelData::BG_blue
Definition at line 25 of file level.h.
Referenced by cLevelData().
Uint8 cLevelData::BG_green
Definition at line 25 of file level.h.
Referenced by cLevelData().
Uint8 cLevelData::BG_red
Background Color.
Definition at line 25 of file level.h.
Referenced by cLevelData().
string cLevelData::Musicfile
Background Image not implemented.
The Music
Definition at line 30 of file level.h.
Referenced by cLevelData(), Game::Init(), cLevel::ParseLine(), play(), cLevel::SaveMusicFile(), and cLevel::Update().
The documentation for this class was generated from the following files:
include/level.h
level.cpp