Meatball: TextObject Class Reference
TextObject Class Reference
To write Text requires the cFont class to be activated.
#include <include/TextObject.h>
Public Member Functions
TextObject ()
Update the surface with the object's internal text and font.
~TextObject ()
TextObject (string text)
TextObject (string text, TTF_Font *font)
Update's the surface and internal font and text members.
TextObject (int x, int y)
TextObject (int x, int y, string text)
TextObject (int x, int y, string text, TTF_Font *font)
void initDefaultColors ()
void SetBGColor (SDL_Color color)
void SetFGColor (SDL_Color color)
void SetColors (SDL_Color fg, SDL_Color bg)
void RenderDifferentFont (TTF_Font *font)
Write text with a different font This won't change the text object's default font.
void preRender ()
void Render ()
Makes the surface and updates the Rect.
void Render (TTF_Font *font)
void Render_shaded ()
void Render_solid ()
void Render_blended ()
void SetFont (cFont *handle)
void SetPos (int x, int y)
void Update ()
void UpdateRect ()
void UpdateRect (int x, int y)
Set the active font engine handle.
void Draw ()
void Draw (SDL_Renderer *)
Public Member Functions inherited from GraphicsObject
GraphicsObject ()
~GraphicsObject ()
Public Attributes
string text
TTF_Font * font
SDL_Color fgColor
SDL_Color bgColor
SDL_bool drawtxt
Public Attributes inherited from GraphicsObject
SDL_Surface * surface
SDL_Rect rect
SDL_Texture * texture
Detailed Description
To write Text requires the cFont class to be activated.
Definition at line 7 of file TextObject.h.
Constructor & Destructor Documentation
TextObject::TextObject ()
Update the surface with the object's internal text and font.
Definition at line 92 of file TextObject.cpp.
References drawtxt, font, initDefaultColors(), GraphicsObject::surface, text, and GraphicsObject::texture.
TextObject::~TextObject ()
Definition at line 116 of file TextObject.cpp.
TextObject::TextObject (string text)
Definition at line 102 of file TextObject.cpp.
References drawtxt, initDefaultColors(), and text.
TextObject::TextObject (string text, TTF_Font * font)
Update's the surface and internal font and text members.
Definition at line 122 of file TextObject.cpp.
References drawtxt, font, initDefaultColors(), and text.
TextObject::TextObject (int x, int y)
Definition at line 130 of file TextObject.cpp.
References drawtxt, initDefaultColors(), and SetPos().
TextObject::TextObject (int x, int y, string text)
Definition at line 137 of file TextObject.cpp.
References drawtxt, initDefaultColors(), SetPos(), and text.
TextObject::TextObject (int x, int y, string text, TTF_Font * font)
Definition at line 145 of file TextObject.cpp.
References drawtxt, font, initDefaultColors(), SetPos(), and text.
Member Function Documentation
void TextObject::Draw (void)
Definition at line 86 of file TextObject.cpp.
References Renderer.
Referenced by ControlsMenu::Draw(), OptionsMenu::Draw(), and MainMenu::UpdateGraphics().
void TextObject::Draw (SDL_Renderer * renderer)
Definition at line 80 of file TextObject.cpp.
References GraphicsObject::rect, and GraphicsObject::texture.
void TextObject::initDefaultColors ()
Definition at line 18 of file TextObject.cpp.
References bgColor, fgColor, and SetColor().
Referenced by TextObject().
void TextObject::preRender ()
Definition at line 23 of file TextObject.cpp.
References GraphicsObject::surface, and GraphicsObject::texture.
Referenced by Render(), Render_blended(), Render_shaded(), and Render_solid().
void TextObject::Render ()
Makes the surface and updates the Rect.
Definition at line 37 of file TextObject.cpp.
References bgColor, cFont::CreateText(), fgColor, font, FONT_TYPE_BLENDED, preRender(), Renderer, GraphicsObject::surface, text, GraphicsObject::texture, and UpdateRect().
Referenced by ControlsMenu::ControlsMenu(), MainMenu::MainMenu(), OptionsMenu::OptionsMenu(), RenderDifferentFont(), ControlsMenu::Update(), and Update().
void TextObject::Render (TTF_Font * font)
Definition at line 70 of file TextObject.cpp.
References bgColor, cFont::CreateText(), fgColor, font, FONT_TYPE_BLENDED, preRender(), Renderer, GraphicsObject::surface, text, GraphicsObject::texture, and UpdateRect().
void TextObject::Render_blended ()
Definition at line 45 of file TextObject.cpp.
References bgColor, cFont::CreateText(), fgColor, font, FONT_TYPE_BLENDED, preRender(), Renderer, GraphicsObject::surface, text, GraphicsObject::texture, and UpdateRect().
void TextObject::Render_shaded ()
Definition at line 53 of file TextObject.cpp.
References bgColor, cFont::CreateText(), fgColor, font, FONT_TYPE_SHADED, preRender(), Renderer, GraphicsObject::surface, text, GraphicsObject::texture, and UpdateRect().
Referenced by ControlsMenu::ControlsMenu().
void TextObject::Render_solid ()
Definition at line 61 of file TextObject.cpp.
References bgColor, cFont::CreateText(), fgColor, font, FONT_TYPE_SOLID, preRender(), Renderer, GraphicsObject::surface, text, GraphicsObject::texture, and UpdateRect().
void TextObject::RenderDifferentFont (TTF_Font * font)
Write text with a different font This won't change the text object's default font.
Definition at line 111 of file TextObject.cpp.
References Render().
void TextObject::SetBGColor (SDL_Color color)
Definition at line 3 of file TextObject.cpp.
References bgColor.
Referenced by ControlsMenu::ControlsMenu().
void TextObject::SetColors (SDL_Color fg, SDL_Color bg)
Definition at line 12 of file TextObject.cpp.
References bgColor, and fgColor.
void TextObject::SetFGColor (SDL_Color color)
Definition at line 7 of file TextObject.cpp.
References fgColor.
Referenced by ControlsMenu::ControlsMenu(), MainMenu::MainMenu(), and OptionsMenu::OptionsMenu().
void TextObject::SetFont (cFont * handle)
void TextObject::SetPos (int x, int y)
Definition at line 174 of file TextObject.cpp.
References GraphicsObject::rect.
Referenced by TextObject().
void TextObject::Update (void)
Definition at line 180 of file TextObject.cpp.
References drawtxt, Render(), and UpdateRect().
Referenced by ControlsMenu::Update(), OptionsMenu::Update(), and MainMenu::UpdateGraphics().
void TextObject::UpdateRect ()
Definition at line 168 of file TextObject.cpp.
References GraphicsObject::rect, SetRect(), and GraphicsObject::surface.
Referenced by Render(), Render_blended(), Render_shaded(), Render_solid(), and Update().
void TextObject::UpdateRect (int x, int y)
Set the active font engine handle.
Definition at line 163 of file TextObject.cpp.
References GraphicsObject::rect, SetRect(), and GraphicsObject::surface.
Member Data Documentation
SDL_Color TextObject::bgColor
Definition at line 13 of file TextObject.h.
Referenced by initDefaultColors(), Render(), Render_blended(), Render_shaded(), Render_solid(), SetBGColor(), and SetColors().
SDL_bool TextObject::drawtxt
Definition at line 14 of file TextObject.h.
Referenced by TextObject(), and Update().
SDL_Color TextObject::fgColor
Definition at line 12 of file TextObject.h.
Referenced by initDefaultColors(), Render(), Render_blended(), Render_shaded(), Render_solid(), SetColors(), and SetFGColor().
TTF_Font* TextObject::font
Definition at line 11 of file TextObject.h.
Referenced by Render(), Render_blended(), Render_shaded(), Render_solid(), and TextObject().
string TextObject::text
Definition at line 10 of file TextObject.h.
Referenced by Render(), Render_blended(), Render_shaded(), Render_solid(), TextObject(), and ControlsMenu::Update().
The documentation for this class was generated from the following files:
include/TextObject.h
TextObject.cpp