Meatball: cWeapon_Laser_X1 Class Reference
cWeapon_Laser_X1 Class Reference
Guns
#include <include/weapon.h>
Public Member Functions
cWeapon_Laser_X1 (unsigned int Origin, unsigned int Power, int Lifetime)
~cWeapon_Laser_X1 (void)
void Fire (void)
Fires an Bullet.
Public Member Functions inherited from cWeapon
cWeapon (unsigned int nOrigin, unsigned int nPower, int nLifetime)
~cWeapon (void)
virtual void Update (void)
Updates the Weapon.
virtual SDL_bool can_Fire (void)
Checks if the timer has run out.
Public Member Functions inherited from cBasicSprite
DLLINTERFACE cBasicSprite (SDL_Renderer *renderer, SDL_Surface *new_image, double x, double y)
DLLINTERFACE ~cBasicSprite (void)
DLLINTERFACE void SetImage (SDL_Renderer *renderer, SDL_Surface *new_image, SDL_bool OverrideSize=SDL_TRUE)
DLLINTERFACE void SetSize (double nwidth, double nheight)
DLLINTERFACE void AddSize (double naddwidth, double naddheight)
DLLINTERFACE void SetPos (double x, double y)
DLLINTERFACE void SetAlpha (Uint8 Alpha)
DLLINTERFACE void SetColorKey (Uint32 Colorkey)
DLLINTERFACE Uint32 GetAlpha (void)
DLLINTERFACE Uint32 GetColorkey (void)
DLLINTERFACE double GetSizeWidth (void)
DLLINTERFACE double GetSizeHeight (void)
DLLINTERFACE void Move (double move_x, double move_y)
DLLINTERFACE void Draw (SDL_Renderer *renderer)
DLLINTERFACE void UpdateTexture (SDL_Renderer *renderer)
DLLINTERFACE void DestroyTexture (void)
virtual DLLINTERFACE void Update (SDL_Renderer *renderer)
Additional Inherited Members
Public Attributes inherited from cWeapon
int direction
The Supported directions 0 = left 1 = right.
unsigned int Weapon_type
The Weapon Type.
unsigned int Origin
Should be Player,Enemy or Static (todo)
unsigned int Power
The damage the one who gets hit takes.
int Lifetime
The Lifetime (-1 = infinite)
double timer
Time before you can shoot once again If you change the Weapon it's resetted.
Mix_Chunk * sound_Fire
The Weapon Fire Sound.
Detailed Description
Definition at line 94 of file weapon.h.
Constructor & Destructor Documentation
cWeapon_Laser_X1::cWeapon_Laser_X1 (unsigned int Origin, unsigned int Power, int Lifetime)
Definition at line 103 of file weapon.cpp.
References cSoundManager::Add(), cAudio::LoadSound(), pAudio, SMan, SOUNDS_DIR, WEAPON_LASER_X1, and cWeapon::Weapon_type.
cWeapon_Laser_X1::~cWeapon_Laser_X1 (void)
Definition at line 112 of file weapon.cpp.
Member Function Documentation
void cWeapon_Laser_X1::Fire (void) virtual
Fires an Bullet.
Reimplemented from cWeapon.
Definition at line 117 of file weapon.cpp.
References AddBullet(), BULLET_LASER_X1, cWeapon::direction, cSoundManager::GetPointer(), cWeapon::Origin, pAudio, cAudio::PlaySound(), cBasicSprite::posx, cBasicSprite::posy, SMan, and cWeapon::timer.
The documentation for this class was generated from the following files:
include/weapon.h
weapon.cpp