Meatball: cPlayer Class Reference
cPlayer Class Reference
Working with the Player
Keep track of the player.
#include <include/player.h>
Public Member Functions
cPlayer (double nposx=0, double nposy=0)
~cPlayer (void)
void init (void)
Loads the Player images.
void Update (void)
Updates the Player.
void Draw (SDL_Renderer *renderer)
Draws the Player.
void Reset (void)
Resets.
void Jump (int power=5)
Jump with the given Power.
void ChangeActiveWeapon (unsigned int Weapon_type)
Change the Active Weapon.
void Fire (void)
Fires the specified Bullet.
void Get_Hit (unsigned int damage)
The Player gets hit by an Bullet or something else.
void Die (void)
The Player dies.
Public Member Functions inherited from cMVelSprite
cMVelSprite (SDL_Surface *new_image, double x, double y, double nvelx=0, double nvely=0)
~cMVelSprite (void)
void Update (void)
void Draw (SDL_Renderer *renderer)
SDL_Rect GetRect (SDL_bool with_camerapos=SDL_FALSE)
Use SDL_TRUE to get the RECT with camera position coordinates calculated also.
Public Member Functions inherited from cVelocitySprite
DLLINTERFACE cVelocitySprite (SDL_Renderer *renderer, SDL_Surface *new_image, double x, double y, double nvelx=0, double nvely=0)
DLLINTERFACE ~cVelocitySprite (void)
virtual DLLINTERFACE void SetVelocity (double nvelx, double nvely)
virtual DLLINTERFACE void SetVelocityX (double nvelx)
virtual DLLINTERFACE void SetVelocityY (double nvely)
DLLINTERFACE void AddVelocity (double addvelx, double addvely, double maxvelx=0, double maxvely=0)
DLLINTERFACE void Update (SDL_Renderer *renderer, SDL_bool nMove=SDL_TRUE)
Public Member Functions inherited from cBasicSprite
DLLINTERFACE cBasicSprite (SDL_Renderer *renderer, SDL_Surface *new_image, double x, double y)
DLLINTERFACE ~cBasicSprite (void)
DLLINTERFACE void SetImage (SDL_Renderer *renderer, SDL_Surface *new_image, SDL_bool OverrideSize=SDL_TRUE)
DLLINTERFACE void SetSize (double nwidth, double nheight)
DLLINTERFACE void AddSize (double naddwidth, double naddheight)
DLLINTERFACE void SetPos (double x, double y)
DLLINTERFACE void SetAlpha (Uint8 Alpha)
DLLINTERFACE void SetColorKey (Uint32 Colorkey)
DLLINTERFACE Uint32 GetAlpha (void)
DLLINTERFACE Uint32 GetColorkey (void)
DLLINTERFACE double GetSizeWidth (void)
DLLINTERFACE double GetSizeHeight (void)
DLLINTERFACE void Move (double move_x, double move_y)
DLLINTERFACE void Draw (SDL_Renderer *renderer)
DLLINTERFACE void UpdateTexture (SDL_Renderer *renderer)
DLLINTERFACE void DestroyTexture (void)
virtual DLLINTERFACE void Update (SDL_Renderer *renderer)
Public Attributes
SDL_Surface * images [5]
The images
0 = Standing Left
1 = Standing Right
2 = Standing Looking up
3 = Ducking
.
cWeapon * pWeapon
The Player Weapon.
int direction
0 = facing left
1 = facing right
2 = facing up
3 = facing down
we need to add angle shots too..
we'll add when player possesses these abilities
int onGround
0 : falling
1 : onground massive
2 : onground halfmassive
int state
0 = Staying (not doing anything :)
1 = Moving,Walking
2 = Jumping
3 = Falling
4 = Flying
double jump_timer
If you press the Jump Button before you touch the ground you have this time to touch the ground and then jump.
int jump_timer_power
Power of the Jump Timer given when pressed the Jump Button.
double jumpvel
unsigned int actWeapon
The Weapon which the Player has in his hands (Active Weapon)
see Weapon definitions.
unsigned int Health
The Health
if == 0 the player dies and the level restarts ;O.
unsigned int updown_pressed
Up or Down -> Left or Right.
Public Attributes inherited from cMVelSprite
int type
The Type 0 = No Type
1 = Player
2 = Sprite Massive
3 = Sprite Passive
4 = Sprite Halfmassive
5 = Sprite Bullet
6 = ?
7 = ?
double Startposy
Start Position.
double Startposx
Collisiondata * Collision
Public Attributes inherited from cVelocitySprite
double velx
double vely
Public Attributes inherited from cBasicSprite
SDL_Texture * texture
SDL_Surface * image
The final stretched/zoomed image to draw if visible == 0 the image won't be drawn.
Uint8 alpha
Alpha 0 (completely not visible) - 255 (completely visible) Read Only.
double posx
double posy
double width
double height
Size for stretching/zooming.
SDL_bool visible
SDL_bool spawned
unsigned int ID
SDL_Surface * startimage
The first image which was set Read only.
SDL_Surface * srcimage
The image which is currently set Read only.
SDL_Rect rect
The rects for all images Read only.
SDL_Rect srcrect
SDL_Rect startrect
SDL_bool drawimg
If this is 1 the image needs to be redrawn to maintain the width and height Read only.
unsigned int Spritetype
What sprite type is this 1 = Basic, 2 = Velocity, 3 = Angle, 4 = Acceleration.
Detailed Description
Keep track of the player.
Draw, update the player. Change his active weapon. Jump(), Fire() bullets, Die, track directions and whether he's on the ground, health,
Definition at line 30 of file player.h.
Constructor & Destructor Documentation
cPlayer::cPlayer (double nposx = 0, double nposy = 0)
Definition at line 15 of file player.cpp.
References actWeapon, direction, Health, jump_timer, jump_timer_power, jumpvel, NONE, onGround, pWeapon, RIGHT, SPRITE_TYPE_PLAYER, state, STATE_STAYING, cMVelSprite::type, updown_pressed, and WEAPON_PISTOL.
cPlayer::~cPlayer (void)
Definition at line 37 of file player.cpp.
References pWeapon.
Member Function Documentation
void cPlayer::ChangeActiveWeapon (unsigned int Weapon_type)
Change the Active Weapon.
Definition at line 342 of file player.cpp.
References actWeapon, pWeapon, SPRITE_TYPE_PLAYER, WEAPON_LASER_X1, WEAPON_MACHINEGUN, and WEAPON_PISTOL.
Referenced by Game::Keydown_Events(), and Reset().
void cPlayer::Die (void)
The Player dies.
Definition at line 428 of file player.cpp.
Referenced by Get_Hit().
void cPlayer::Draw (SDL_Renderer * renderer)
Draws the Player.
Definition at line 266 of file player.cpp.
References cBasicSprite::image, pCamera, cBasicSprite::posx, cBasicSprite::posy, cBasicSprite::rect, cBasicSprite::texture, cBasicSprite::visible, cCamera::x, and cCamera::y.
Referenced by MiniEngine::Draw(), cLevelEditor::Draw(), and cConsole::Draw().
void cPlayer::Fire (void)
Fires the specified Bullet.
Definition at line 372 of file player.cpp.
References AddParticleEmitter(), cWeapon::can_Fire(), cWeapon::direction, direction, cWeapon::Fire(), cBasicSprite::height, LEFT, cBasicSprite::posx, cBasicSprite::posy, pWeapon, RIGHT, cBasicSprite::SetPos(), cVelocitySprite::velx, cVelocitySprite::vely, and cBasicSprite::width.
Referenced by Game::Keydown_Events(), Game::MouseButtonDown_Events(), and Game::Player_Input().
void cPlayer::Get_Hit (unsigned int damage)
The Player gets hit by an Bullet or something else.
Definition at line 415 of file player.cpp.
References Die(), and Health.
void cPlayer::init (void)
Loads the Player images.
Definition at line 48 of file player.cpp.
References cImageManager::Add(), colorkey, DOWN, cImageManager::GetPointer(), images, IMan, LEFT, LoadImage(), PIXMAPS_DIR, pWeapon, RIGHT, SPRITE_TYPE_PLAYER, and UP.
Referenced by Game::Init().
void cPlayer::Jump (int power = 5)
Jump with the given Power.
Definition at line 302 of file player.cpp.
References JUMP_KEYS_HELD, jump_timer, jump_timer_power, pFramerate, cFramerate::speedfactor, state, STATE_FALLING, STATE_JUMPING, STATE_STAYING, STATE_WALKING, and cVelocitySprite::vely.
Referenced by Game::Keydown_Events(), Game::MouseButtonDown_Events(), and Update().
void cPlayer::Reset (void)
Resets.
Definition at line 283 of file player.cpp.
References ChangeActiveWeapon(), direction, onGround, cBasicSprite::posx, cBasicSprite::posy, RIGHT, cMVelSprite::Startposx, cMVelSprite::Startposy, cVelocitySprite::velx, cVelocitySprite::vely, and WEAPON_PISTOL.
Referenced by Game::Init().
void cPlayer::Update (void)
Updates the Player.
Definition at line 70 of file player.cpp.
References cVelocitySprite::AddVelocity(), ALL_COLLISIONS_UD, Collisiondata::collide, cMVelSprite::Collision, Collisiondata::direction, direction, DOWN, cBasicSprite::height, Collisiondata::iCollisionType, images, Jump(), JUMP_KEYS_HELD, jump_timer, jump_timer_power, jumpvel, LEFT, MAX_FALL_VELOCITY, mode, MODE_CONSOLE, MOVELEFT_KEYS_HELD, MOVERIGHT_KEYS_HELD, onGround, pCamera, pFramerate, PositionCheck(), cBasicSprite::posx, cBasicSprite::posy, pWeapon, Renderer, RIGHT, cBasicSprite::SetImage(), cBasicSprite::SetPos(), cVelocitySprite::SetVelocity(), cFramerate::speedfactor, SPRITE_TYPE_ENEMY, SPRITE_TYPE_HALFMASSIVE, SPRITE_TYPE_MASSIVE, state, STATE_FALLING, STATE_JUMPING, STATE_STAYING, STATE_WALKING, cMVelSprite::type, UP, cWeapon::Update(), cBasicSprite::Update(), cVelocitySprite::velx, cVelocitySprite::vely, WALK_VELOCITY, cBasicSprite::width, window_height, window_width, cCamera::x, and cCamera::y.
Referenced by UpdatePlayer().
Member Data Documentation
unsigned int cPlayer::actWeapon
The Weapon which the Player has in his hands (Active Weapon)
see Weapon definitions.
Definition at line 114 of file player.h.
Referenced by ChangeActiveWeapon(), and cPlayer().
int cPlayer::direction
0 = facing left
1 = facing right
2 = facing up
3 = facing down
we need to add angle shots too..
we'll add when player possesses these abilities
Definition at line 82 of file player.h.
Referenced by cPlayer(), Fire(), Game::Player_Input(), Reset(), and Update().
unsigned int cPlayer::Health
The Health
if == 0 the player dies and the level restarts ;O.
Definition at line 119 of file player.h.
Referenced by cPlayer(), and Get_Hit().
SDL_Surface* cPlayer::images[5]
The images
0 = Standing Left
1 = Standing Right
2 = Standing Looking up
3 = Ducking
.
Definition at line 69 of file player.h.
Referenced by init(), and Update().
double cPlayer::jump_timer
If you press the Jump Button before you touch the ground you have this time to touch the ground and then jump.
Definition at line 102 of file player.h.
Referenced by cPlayer(), Jump(), and Update().
int cPlayer::jump_timer_power
Power of the Jump Timer given when pressed the Jump Button.
Definition at line 107 of file player.h.
Referenced by cPlayer(), Jump(), and Update().
double cPlayer::jumpvel
Definition at line 109 of file player.h.
Referenced by cPlayer(), and Update().
int cPlayer::onGround
0 : falling
1 : onground massive
2 : onground halfmassive
Definition at line 88 of file player.h.
Referenced by cPlayer(), Reset(), and Update().
cWeapon* cPlayer::pWeapon
The Player Weapon.
Definition at line 72 of file player.h.
Referenced by ChangeActiveWeapon(), cPlayer(), Fire(), init(), Update(), and ~cPlayer().
int cPlayer::state
0 = Staying (not doing anything :)
1 = Moving,Walking
2 = Jumping
3 = Falling
4 = Flying
Definition at line 96 of file player.h.
Referenced by cPlayer(), Jump(), and Update().
unsigned int cPlayer::updown_pressed
Up or Down -> Left or Right.
Definition at line 121 of file player.h.
Referenced by cPlayer(), and Game::Player_Input().
The documentation for this class was generated from the following files:
include/player.h
player.cpp