Meatball: MainMenu Class Reference
MainMenu Class Reference
#include <include/MainMenu.h>
Public Member Functions
MainMenu ()
~MainMenu ()
void FadeOutBG ()
void PostDraw ()
void Update ()
void Collisions ()
void UpdateGraphics ()
void UpdateHardware ()
void UpdateLogic ()
void Do ()
void EventHandler ()
Public Member Functions inherited from MiniEngine
virtual void PreUpdate (void)
Does general things.
virtual void PostUpdate (void)
virtual void PreDraw (void)
virtual void Draw (void)
virtual void Input ()
virtual void HeldKey_Handler ()
Public Attributes
cBasicSprite * Button_Start
cBasicSprite * Button_Exit
cBasicSprite * Menu_Background
cBasicSprite * Light1
OptionsMenu optionsmenu
TTF_Font * myfont
TextObject * tOptions
SDL_bool Light_reverse
Static Public Attributes
static int submode = MAIN
Detailed Description
Definition at line 24 of file MainMenu.h.
Constructor & Destructor Documentation
MainMenu::MainMenu ()
[Adding a Sprite]
[Adding a Sprite]
Definition at line 7 of file MainMenu.cpp.
References cSoundManager::Add(), cImageManager::Add(), Button_Exit, Button_Start, colorkey, cFont::CreateFont(), done, FONT_DIR, cImageManager::GetPointer(), cBasicSprite::height, IMan, Light1, Light_reverse, LoadImage(), cAudio::LoadSound(), MAIN, Menu_Background, MUSIC_DIR, myfont, pAudio, pFont, PIXMAPS_DIR, cAudio::PlayMusik(), TextObject::Render(), Renderer, SetColor(), TextObject::SetFGColor(), cBasicSprite::SetSize(), SMan, SOUNDS_DIR, submode, tOptions, window_height, and window_width.
MainMenu::~MainMenu ()
Definition at line 49 of file MainMenu.cpp.
References Button_Exit, Button_Start, Light1, Menu_Background, myfont, and tOptions.
Member Function Documentation
void MainMenu::Collisions ()
Todo:
The Alpha adjustments here could be turned into API calls.
Definition at line 105 of file MainMenu.cpp.
References Button_Exit, Button_Start, cBasicSprite::GetAlpha(), MouseCollidesWith(), pFramerate, cBasicSprite::rect, cBasicSprite::SetAlpha(), and cFramerate::speedfactor.
Referenced by Update().
void MainMenu::Do () virtual
Reimplemented from MiniEngine.
Definition at line 218 of file MainMenu.cpp.
References OptionsMenu::Do(), EventHandler(), cAudio::FadeOutMusic(), cSoundManager::GetPointer(), Game::Init(), MAIN, mode, MODE_GAME, OPTIONS, optionsmenu, pAudio, cAudio::PlaySound(), PostDraw(), SMan, SOUNDS_DIR, submode, and Update().
Referenced by DoGame().
void MainMenu::EventHandler (void) virtual
[Mouse Collision Check]
[Mouse Collision Check]
Reimplemented from MiniEngine.
Definition at line 280 of file MainMenu.cpp.
References Button_Exit, Button_Start, done, event, mode, MODE_GAME, MODE_QUIT, MouseCollidesWith(), OPTIONS, GraphicsObject::rect, cBasicSprite::rect, SDL_ToggleFS(), submode, tOptions, UniversalEventHandler(), and Window.
Referenced by Do().
void MainMenu::FadeOutBG ()
Definition at line 249 of file MainMenu.cpp.
References DEBUGLOG, PostDraw(), and UpdateGraphics().
void MainMenu::PostDraw (void) virtual
Reimplemented from MiniEngine.
Definition at line 273 of file MainMenu.cpp.
References Renderer.
Referenced by Do(), and FadeOutBG().
void MainMenu::Update (void) virtual
Reimplemented from MiniEngine.
Definition at line 155 of file MainMenu.cpp.
References Collisions(), UpdateGraphics(), UpdateHardware(), and UpdateLogic().
Referenced by Do().
void MainMenu::UpdateGraphics ()
Definition at line 75 of file MainMenu.cpp.
References Button_Exit, Button_Start, TextObject::Draw(), cBasicSprite::Draw(), Menu_Background, pFramerate, pMouse, Renderer, cFramerate::SetSpeedFactor(), tOptions, TextObject::Update(), and cBasicSprite::Update().
Referenced by FadeOutBG(), and Update().
void MainMenu::UpdateHardware ()
Definition at line 69 of file MainMenu.cpp.
References pAudio, pMouse, Renderer, cAudio::Update(), and cMouseCursor::Update().
Referenced by Update().
void MainMenu::UpdateLogic ()
Definition at line 163 of file MainMenu.cpp.
References cBasicSprite::GetAlpha(), Light1, Light_reverse, pFramerate, cBasicSprite::SetAlpha(), and cFramerate::speedfactor.
Referenced by Update().
Member Data Documentation
cBasicSprite * MainMenu::Button_Exit
Definition at line 31 of file MainMenu.h.
Referenced by Collisions(), EventHandler(), MainMenu(), UpdateGraphics(), and ~MainMenu().
cBasicSprite* MainMenu::Button_Start
Definition at line 31 of file MainMenu.h.
Referenced by Collisions(), EventHandler(), MainMenu(), UpdateGraphics(), and ~MainMenu().
cBasicSprite* MainMenu::Light1
Definition at line 34 of file MainMenu.h.
Referenced by MainMenu(), UpdateLogic(), and ~MainMenu().
SDL_bool MainMenu::Light_reverse
Definition at line 41 of file MainMenu.h.
Referenced by MainMenu(), and UpdateLogic().
cBasicSprite* MainMenu::Menu_Background
Definition at line 32 of file MainMenu.h.
Referenced by MainMenu(), UpdateGraphics(), and ~MainMenu().
TTF_Font* MainMenu::myfont
Definition at line 37 of file MainMenu.h.
Referenced by MainMenu(), and ~MainMenu().
OptionsMenu MainMenu::optionsmenu
Definition at line 36 of file MainMenu.h.
Referenced by Do().
int MainMenu::submode = MAIN static
Definition at line 40 of file MainMenu.h.
Referenced by OptionsMenu::Collisions(), Do(), EventHandler(), OptionsMenu::EventHandler(), and MainMenu().
TextObject* MainMenu::tOptions
Definition at line 38 of file MainMenu.h.
Referenced by EventHandler(), MainMenu(), UpdateGraphics(), and ~MainMenu().
The documentation for this class was generated from the following files:
include/MainMenu.h
MainMenu.cpp