Meatball: cMParticle Class Reference
cMParticle Class Reference
The Particle class.
#include <include/effects.h>
Public Member Functions
cMParticle (double x, double y, double nangle=0, double nspeed=0)
~cMParticle (void)
void Update (void)
void Draw (SDL_Renderer *renderer)
void HandleCollision (int direction)
Public Member Functions inherited from cMAngleSprite
cMAngleSprite (SDL_Surface *new_image, double x, double y, double nangle=0, double nspeed=0)
~cMAngleSprite (void)
void Update (void)
void Draw (SDL_Renderer *renderer)
SDL_Rect GetRect (SDL_bool with_camerapos=SDL_FALSE)
Public Member Functions inherited from cAngleSprite
DLLINTERFACE cAngleSprite (SDL_Renderer *renderer, SDL_Surface *new_image, double x, double y, double nangle=0, double nspeed=0, SDL_bool nanglerotate=SDL_TRUE)
DLLINTERFACE ~cAngleSprite (void)
DLLINTERFACE void SetDirection (double nangle=-1, double nspeed=-1)
DLLINTERFACE void AddDirection (double nangle)
DLLINTERFACE void SetSpeed (double nspeed)
DLLINTERFACE void AddSpeed (double nspeed)
DLLINTERFACE void Update (SDL_Renderer *, SDL_bool nMove=SDL_TRUE)
Public Member Functions inherited from cBasicSprite
DLLINTERFACE cBasicSprite (SDL_Renderer *renderer, SDL_Surface *new_image, double x, double y)
DLLINTERFACE ~cBasicSprite (void)
DLLINTERFACE void SetImage (SDL_Renderer *renderer, SDL_Surface *new_image, SDL_bool OverrideSize=SDL_TRUE)
DLLINTERFACE void SetSize (double nwidth, double nheight)
DLLINTERFACE void AddSize (double naddwidth, double naddheight)
DLLINTERFACE void SetPos (double x, double y)
DLLINTERFACE void SetAlpha (Uint8 Alpha)
DLLINTERFACE void SetColorKey (Uint32 Colorkey)
DLLINTERFACE Uint32 GetAlpha (void)
DLLINTERFACE Uint32 GetColorkey (void)
DLLINTERFACE double GetSizeWidth (void)
DLLINTERFACE double GetSizeHeight (void)
DLLINTERFACE void Move (double move_x, double move_y)
DLLINTERFACE void Draw (SDL_Renderer *renderer)
DLLINTERFACE void UpdateTexture (SDL_Renderer *renderer)
DLLINTERFACE void DestroyTexture (void)
virtual DLLINTERFACE void Update (SDL_Renderer *renderer)
Public Attributes
double red
The Color and Alpha.
double green
double blue
double alpha
double fadeoutspeed
The fade-out speed.
double Randomness
The Direction Randomness.
SDL_bool active
Does the Particle collides and has gravity.
Public Attributes inherited from cMAngleSprite
int type
The Type
0 = No Type
1 = Player
2 = Sprite Massive
3 = Sprite Passive
4 = Sprite Halfmassive
5 = Sprite Bullet
6 = ?
7 = ?
.
double Startposy
Start Position.
double Startposx
Collisiondata * Collision
Public Attributes inherited from cAngleSprite
double angle
double speed
double dirx
The Direction calculated by SetDirection for 360° image moving Read Only.
double diry
SDL_bool anglerotate
If SDL_TRUE the image will be rotated to the angle Read only.
Public Attributes inherited from cBasicSprite
SDL_Texture * texture
SDL_Surface * image
The final stretched/zoomed image to draw if visible == 0 the image won't be drawn.
Uint8 alpha
Alpha 0 (completely not visible) - 255 (completely visible) Read Only.
double posx
double posy
double width
double height
Size for stretching/zooming.
SDL_bool visible
SDL_bool spawned
unsigned int ID
SDL_Surface * startimage
The first image which was set Read only.
SDL_Surface * srcimage
The image which is currently set Read only.
SDL_Rect rect
The rects for all images Read only.
SDL_Rect srcrect
SDL_Rect startrect
SDL_bool drawimg
If this is 1 the image needs to be redrawn to maintain the width and height Read only.
unsigned int Spritetype
What sprite type is this 1 = Basic, 2 = Velocity, 3 = Angle, 4 = Acceleration.
Detailed Description
The Particle class.
Definition at line 14 of file effects.h.
Constructor & Destructor Documentation
cMParticle::cMParticle (double x, double y, double nangle = 0, double nspeed = 0)
Parameters
nangle = 0
nspeed = 0
Definition at line 9 of file effects.cpp.
References active, alpha, blue, fadeoutspeed, green, cBasicSprite::height, Randomness, cBasicSprite::rect, red, SPRITE_TYPE_PARTICLE, cMAngleSprite::type, and cBasicSprite::width.
cMParticle::~cMParticle (void)
Definition at line 32 of file effects.cpp.
Member Function Documentation
void cMParticle::Draw (SDL_Renderer * renderer)
Definition at line 125 of file effects.cpp.
References alpha, blue, DrawPixel(), green, pCamera, cBasicSprite::posx, cBasicSprite::posy, red, cBasicSprite::visible, cCamera::x, and cCamera::y.
Referenced by cMParticleEmitter::Draw().
void cMParticle::HandleCollision (int direction)
Definition at line 136 of file effects.cpp.
References active, cAngleSprite::AddDirection(), cAngleSprite::AddSpeed(), cAngleSprite::angle, DOWN, LEFT, RIGHT, cAngleSprite::speed, and UP.
Referenced by Update().
void cMParticle::Update (void)
Angle Directions : 0 = Right 90 = Down 180 = Left 270 = Up
Definition at line 37 of file effects.cpp.
References active, cAngleSprite::AddDirection(), cAngleSprite::AddSpeed(), alpha, cAngleSprite::angle, Collisiondata::collide, cMAngleSprite::Collision, DEBUGLOG, Collisiondata::direction, DOWN, fadeoutspeed, HandleCollision(), LEFT, pFramerate, Random(), Randomness, RIGHT, cAngleSprite::SetDirection(), cAngleSprite::speed, cFramerate::speedfactor, UP, cMAngleSprite::Update(), and cBasicSprite::visible.
Referenced by cMParticleEmitter::Update().
Member Data Documentation
SDL_bool cMParticle::active
Does the Particle collides and has gravity.
Definition at line 36 of file effects.h.
Referenced by cMParticle(), HandleCollision(), and Update().
double cMParticle::alpha
Definition at line 27 of file effects.h.
Referenced by cMParticle(), Draw(), cMParticleEmitter::InitParticles(), and Update().
double cMParticle::blue
Definition at line 27 of file effects.h.
Referenced by cMParticle(), Draw(), and cMParticleEmitter::InitParticles().
double cMParticle::fadeoutspeed
The fade-out speed.
Definition at line 30 of file effects.h.
Referenced by cMParticle(), cMParticleEmitter::InitParticles(), and Update().
double cMParticle::green
Definition at line 27 of file effects.h.
Referenced by cMParticle(), Draw(), and cMParticleEmitter::InitParticles().
double cMParticle::Randomness
The Direction Randomness.
Definition at line 33 of file effects.h.
Referenced by cMParticle(), cMParticleEmitter::InitParticles(), and Update().
double cMParticle::red
The Color and Alpha.
Definition at line 27 of file effects.h.
Referenced by cMParticle(), Draw(), and cMParticleEmitter::InitParticles().
The documentation for this class was generated from the following files:
include/effects.h
effects.cpp