Meatball: cAF373 Class Reference
cAF373 Class Reference
#include <include/AF-373.h>
Public Member Functions
cAF373 (double nposx, double nposy)
~cAF373 (void)
void init (void)
void Update (void)
void Draw (SDL_Renderer *renderer)
void Die (void)
void Fire (int fdirection)
int AI_PlayerSearch (int sdirection)
void AI_Idle (void)
Public Member Functions inherited from cEnemy
cEnemy (double nposx, double nposy)
~cEnemy (void)
virtual void Jump (int power=5)
Public Member Functions inherited from cMVelSprite
cMVelSprite (SDL_Surface *new_image, double x, double y, double nvelx=0, double nvely=0)
~cMVelSprite (void)
void Update (void)
void Draw (SDL_Renderer *renderer)
SDL_Rect GetRect (SDL_bool with_camerapos=SDL_FALSE)
Use SDL_TRUE to get the RECT with camera position coordinates calculated also.
Public Member Functions inherited from cVelocitySprite
DLLINTERFACE cVelocitySprite (SDL_Renderer *renderer, SDL_Surface *new_image, double x, double y, double nvelx=0, double nvely=0)
DLLINTERFACE ~cVelocitySprite (void)
virtual DLLINTERFACE void SetVelocity (double nvelx, double nvely)
virtual DLLINTERFACE void SetVelocityX (double nvelx)
virtual DLLINTERFACE void SetVelocityY (double nvely)
DLLINTERFACE void AddVelocity (double addvelx, double addvely, double maxvelx=0, double maxvely=0)
DLLINTERFACE void Update (SDL_Renderer *renderer, SDL_bool nMove=SDL_TRUE)
Public Member Functions inherited from cBasicSprite
DLLINTERFACE cBasicSprite (SDL_Renderer *renderer, SDL_Surface *new_image, double x, double y)
DLLINTERFACE ~cBasicSprite (void)
DLLINTERFACE void SetImage (SDL_Renderer *renderer, SDL_Surface *new_image, SDL_bool OverrideSize=SDL_TRUE)
DLLINTERFACE void SetSize (double nwidth, double nheight)
DLLINTERFACE void AddSize (double naddwidth, double naddheight)
DLLINTERFACE void SetPos (double x, double y)
DLLINTERFACE void SetAlpha (Uint8 Alpha)
DLLINTERFACE void SetColorKey (Uint32 Colorkey)
DLLINTERFACE Uint32 GetAlpha (void)
DLLINTERFACE Uint32 GetColorkey (void)
DLLINTERFACE double GetSizeWidth (void)
DLLINTERFACE double GetSizeHeight (void)
DLLINTERFACE void Move (double move_x, double move_y)
DLLINTERFACE void Draw (SDL_Renderer *renderer)
DLLINTERFACE void UpdateTexture (SDL_Renderer *renderer)
DLLINTERFACE void DestroyTexture (void)
virtual DLLINTERFACE void Update (SDL_Renderer *renderer)
Public Attributes
SDL_Surface * images [2]
The images 0 = Left 1 = Right.
cWeapon * pWeapon
int onGround
0 : falling 1 : onground massive 2 : onground halfmassive
int AI_direction
The Direction the AI wants to move uses the defined directions.
double AI_movingtime
The time the Ai should move if <= 0 AI_direction is set to idle (-1)
int state
0 = Staying (not doing anything) 1 = Moving,Walking 2 = Jumping 3 = Falling 4 = Flying
Public Attributes inherited from cEnemy
int direction
0 = facing left 1 = facing right 2 = facing up 3 = facing down
unsigned int Enemy_type
The Enemy Type.
unsigned int Enemy_state
The Enemy State.
unsigned int health
The Health.
double max_speed
Maximum Speed.
double Acceleration
The Acceleration.
Public Attributes inherited from cMVelSprite
int type
The Type 0 = No Type
1 = Player
2 = Sprite Massive
3 = Sprite Passive
4 = Sprite Halfmassive
5 = Sprite Bullet
6 = ?
7 = ?
double Startposy
Start Position.
double Startposx
Collisiondata * Collision
Public Attributes inherited from cVelocitySprite
double velx
double vely
Public Attributes inherited from cBasicSprite
SDL_Texture * texture
SDL_Surface * image
The final stretched/zoomed image to draw if visible == 0 the image won't be drawn.
Uint8 alpha
Alpha 0 (completely not visible) - 255 (completely visible) Read Only.
double posx
double posy
double width
double height
Size for stretching/zooming.
SDL_bool visible
SDL_bool spawned
unsigned int ID
SDL_Surface * startimage
The first image which was set Read only.
SDL_Surface * srcimage
The image which is currently set Read only.
SDL_Rect rect
The rects for all images Read only.
SDL_Rect srcrect
SDL_Rect startrect
SDL_bool drawimg
If this is 1 the image needs to be redrawn to maintain the width and height Read only.
unsigned int Spritetype
What sprite type is this 1 = Basic, 2 = Velocity, 3 = Angle, 4 = Acceleration.
Detailed Description
Definition at line 10 of file AF-373.h.
Constructor & Destructor Documentation
cAF373::cAF373 (double nposx, double nposy)
Definition at line 8 of file AF-373.cpp.
References AI_direction, AI_movingtime, DOWN, images, onGround, pWeapon, state, and STATE_FALLING.
cAF373::~cAF373 (void)
Definition at line 27 of file AF-373.cpp.
References pWeapon.
Member Function Documentation
void cAF373::AI_Idle (void)
Definition at line 358 of file AF-373.cpp.
References AI_direction, AI_movingtime, LEFT, pFramerate, Random(), RIGHT, and cFramerate::speedfactor.
Referenced by Update().
int cAF373::AI_PlayerSearch (int sdirection)
Definition at line 319 of file AF-373.cpp.
References Collisiondata::collide, cMVelSprite::Collision, DEBUGLOG, cBasicSprite::height, Collisiondata::iCollisionType, LEFT, PositionCheck(), cBasicSprite::posx, cBasicSprite::posy, RIGHT, SPRITE_TYPE_PLAYER, cMVelSprite::type, and cBasicSprite::width.
Referenced by Update().
void cAF373::Die (void) virtual
Reimplemented from cEnemy.
Definition at line 279 of file AF-373.cpp.
References DEBUGLOG.
void cAF373::Draw (SDL_Renderer * renderer) virtual
Reimplemented from cEnemy.
Definition at line 262 of file AF-373.cpp.
References cBasicSprite::image, pCamera, cBasicSprite::posx, cBasicSprite::posy, cBasicSprite::rect, cBasicSprite::texture, cBasicSprite::visible, cCamera::x, and cCamera::y.
void cAF373::Fire (int fdirection)
Definition at line 284 of file AF-373.cpp.
References AddParticleEmitter(), cWeapon::can_Fire(), cWeapon::direction, cWeapon::Fire(), cBasicSprite::height, LEFT, cBasicSprite::posx, cBasicSprite::posy, pWeapon, Random(), RIGHT, cBasicSprite::SetPos(), and cBasicSprite::width.
Referenced by Update().
void cAF373::init (void) virtual
Reimplemented from cEnemy.
Definition at line 35 of file AF-373.cpp.
References cImageManager::Add(), colorkey, cEnemy::direction, ENEMY_AF373, cEnemy::Enemy_type, cImageManager::GetPointer(), images, IMan, LEFT, LoadImage(), PIXMAPS_DIR, pWeapon, Renderer, RIGHT, cBasicSprite::SetImage(), cVelocitySprite::SetVelocity(), and SPRITE_TYPE_ENEMY.
void cAF373::Update (void) virtual
Reimplemented from cEnemy.
Definition at line 62 of file AF-373.cpp.
References cVelocitySprite::AddVelocity(), AI_direction, AI_Idle(), AI_movingtime, AI_PlayerSearch(), Collisiondata::collide, cMVelSprite::Collision, cEnemy::direction, DOWN, Fire(), cBasicSprite::height, Collisiondata::iCollisionType, images, LEFT, onGround, pCamera, pFramerate, PositionCheck(), cBasicSprite::posx, cBasicSprite::posy, pWeapon, Renderer, RIGHT, cBasicSprite::SetImage(), cBasicSprite::SetPos(), cVelocitySprite::SetVelocity(), cFramerate::speedfactor, state, STATE_FALLING, STATE_STAYING, STATE_WALKING, cMVelSprite::type, cEnemy::Update(), cWeapon::Update(), cVelocitySprite::velx, cVelocitySprite::vely, cBasicSprite::width, window_height, window_width, cCamera::x, and cCamera::y.
Member Data Documentation
int cAF373::AI_direction
The Direction the AI wants to move uses the defined directions.
Definition at line 47 of file AF-373.h.
Referenced by AI_Idle(), cAF373(), and Update().
double cAF373::AI_movingtime
The time the Ai should move if <= 0 AI_direction is set to idle (-1)
Definition at line 52 of file AF-373.h.
Referenced by AI_Idle(), cAF373(), and Update().
SDL_Surface* cAF373::images[2]
The images 0 = Left 1 = Right.
Definition at line 33 of file AF-373.h.
Referenced by cAF373(), init(), and Update().
int cAF373::onGround
0 : falling 1 : onground massive 2 : onground halfmassive
Definition at line 42 of file AF-373.h.
Referenced by cAF373(), and Update().
cWeapon* cAF373::pWeapon
Definition at line 36 of file AF-373.h.
Referenced by cAF373(), Fire(), init(), Update(), and ~cAF373().
int cAF373::state
0 = Staying (not doing anything) 1 = Moving,Walking 2 = Jumping 3 = Falling 4 = Flying
Definition at line 60 of file AF-373.h.
Referenced by cAF373(), and Update().
The documentation for this class was generated from the following files:
include/AF-373.h
AF-373.cpp