Meatball: cMouseCursor Class Reference
cMouseCursor Class Reference
Sprite
#include <Engine/include/sprite.h>
Public Member Functions
DLLINTERFACE cMouseCursor (SDL_Renderer *renderer, double x, double y, SDL_Surface *new_image)
virtual DLLINTERFACE ~cMouseCursor (void)
DLLINTERFACE SDL_bool CollisonCheck (double x, double y)
Point Collisioncheck.
DLLINTERFACE SDL_bool CollisonCheck (SDL_Rect *Crect)
Checks if the MouseCursor is in the rect.
DLLINTERFACE void Update (SDL_Renderer *renderer)
DLLINTERFACE void hide ()
DLLINTERFACE void show ()
Public Member Functions inherited from cBasicSprite
DLLINTERFACE cBasicSprite (SDL_Renderer *renderer, SDL_Surface *new_image, double x, double y)
DLLINTERFACE ~cBasicSprite (void)
DLLINTERFACE void SetImage (SDL_Renderer *renderer, SDL_Surface *new_image, SDL_bool OverrideSize=SDL_TRUE)
DLLINTERFACE void SetSize (double nwidth, double nheight)
DLLINTERFACE void AddSize (double naddwidth, double naddheight)
DLLINTERFACE void SetPos (double x, double y)
DLLINTERFACE void SetAlpha (Uint8 Alpha)
DLLINTERFACE void SetColorKey (Uint32 Colorkey)
DLLINTERFACE Uint32 GetAlpha (void)
DLLINTERFACE Uint32 GetColorkey (void)
DLLINTERFACE double GetSizeWidth (void)
DLLINTERFACE double GetSizeHeight (void)
DLLINTERFACE void Move (double move_x, double move_y)
DLLINTERFACE void Draw (SDL_Renderer *renderer)
DLLINTERFACE void UpdateTexture (SDL_Renderer *renderer)
DLLINTERFACE void DestroyTexture (void)
Additional Inherited Members
Public Attributes inherited from cBasicSprite
SDL_Texture * texture
SDL_Surface * image
The final stretched/zoomed image to draw if visible == 0 the image won't be drawn.
Uint8 alpha
Alpha 0 (completely not visible) - 255 (completely visible) Read Only.
double posx
double posy
double width
double height
Size for stretching/zooming.
SDL_bool visible
SDL_bool spawned
unsigned int ID
SDL_Surface * startimage
The first image which was set Read only.
SDL_Surface * srcimage
The image which is currently set Read only.
SDL_Rect rect
The rects for all images Read only.
SDL_Rect srcrect
SDL_Rect startrect
SDL_bool drawimg
If this is 1 the image needs to be redrawn to maintain the width and height Read only.
unsigned int Spritetype
What sprite type is this 1 = Basic, 2 = Velocity, 3 = Angle, 4 = Acceleration.
Detailed Description
Definition at line 199 of file sprite.h.
Constructor & Destructor Documentation
cMouseCursor::cMouseCursor (SDL_Renderer * renderer, double x, double y, SDL_Surface * new_image)
Definition at line 678 of file sprite.cpp.
References SPRITE_MOUSECURSOR, and cBasicSprite::Spritetype.
cMouseCursor::~cMouseCursor (void) virtual
Definition at line 683 of file sprite.cpp.
Member Function Documentation
SDL_bool cMouseCursor::CollisonCheck (double x, double y)
Point Collisioncheck.
Definition at line 688 of file sprite.cpp.
References cBasicSprite::posx, and cBasicSprite::posy.
Referenced by MouseCollidesWith().
SDL_bool cMouseCursor::CollisonCheck (SDL_Rect * Crect)
Checks if the MouseCursor is in the rect.
Definition at line 698 of file sprite.cpp.
References cBasicSprite::posx, cBasicSprite::posy, RectIntersect(), and SetRect().
void cMouseCursor::hide ()
Definition at line 722 of file sprite.cpp.
References cBasicSprite::visible.
Referenced by OptionsMenu::Collisions().
void cMouseCursor::show ()
Definition at line 727 of file sprite.cpp.
References cBasicSprite::visible.
Referenced by OptionsMenu::Collisions().
void cMouseCursor::Update (SDL_Renderer * renderer) virtual
Reimplemented from cBasicSprite.
Definition at line 711 of file sprite.cpp.
References cBasicSprite::SetPos(), and cBasicSprite::Update().
Referenced by MiniEngine::PreUpdate(), OptionsMenu::PreUpdate(), and MainMenu::UpdateHardware().
The documentation for this class was generated from the following files:
Engine/include/sprite.h
Engine/sprite.cpp