Meatball: cFont Class Reference
cFont Class Reference
Font
#include <Engine/include/font.h>
Public Member Functions
DLLINTERFACE cFont (void)
DLLINTERFACE ~cFont (void)
DLLINTERFACE SDL_Surface * CreateText (const char *text, TTF_Font *font, unsigned int type=FONT_TYPE_BLENDED)
DLLINTERFACE TTF_Font * CreateFont (const char *Font_File, unsigned int ptsize=16, unsigned int style=TTF_STYLE_NORMAL)
Creates an Font from an .ttf file default pointsize is 16 default style is TTF_STYLE_NORMAL.
DLLINTERFACE void SetFontStyle (TTF_Font *font, unsigned int style=TTF_STYLE_NORMAL)
Sets the Style of an Font styles : TTF_STYLE_NORMAL TTF_STYLE_BOLD TTF_STYLE_ITALIC TTF_STYLE_UNDERLINE.
Static Public Member Functions
static DLLINTERFACE SDL_Surface * CreateText (const char *text, TTF_Font *font, unsigned int type, SDL_Color Text_Color, SDL_Color Background_Color)
Creates the text in an Surface types : 1 = Blended 2 = Shaded 3 = Solid.
Public Attributes
SDL_Color coldefText
SDL_Color coldefBackground
Detailed Description
Definition at line 28 of file font.h.
Constructor & Destructor Documentation
cFont::cFont (void)
Definition at line 4 of file font.cpp.
References coldefBackground, coldefText, and SetColor().
cFont::~cFont (void)
Definition at line 15 of file font.cpp.
Member Function Documentation
TTF_Font * cFont::CreateFont (const char * Font_File, unsigned int ptsize = 16, unsigned int style = TTF_STYLE_NORMAL)
Creates an Font from an .ttf file default pointsize is 16 default style is TTF_STYLE_NORMAL.
Definition at line 56 of file font.cpp.
References SetFontStyle().
Referenced by cConsole::cConsole(), ControlsMenu::ControlsMenu(), initEngine(), MainMenu::MainMenu(), and OptionsMenu::OptionsMenu().
SDL_Surface * cFont::CreateText (const char * text, TTF_Font * font, unsigned int type, SDL_Color Text_Color, SDL_Color Background_Color) static
Creates the text in an Surface types : 1 = Blended 2 = Shaded 3 = Solid.
Definition at line 28 of file font.cpp.
Referenced by cConsole::BlinkCursor(), CreateText(), cConsole::CreateTextOnSurfaces(), FramerateDraw(), TextObject::Render(), TextObject::Render_blended(), TextObject::Render_shaded(), and TextObject::Render_solid().
DLLINTERFACE SDL_Surface* cFont::CreateText (const char * text, TTF_Font * font, unsigned int type = FONT_TYPE_BLENDED) inline
Definition at line 45 of file font.h.
References coldefBackground, coldefText, and CreateText().
void cFont::SetFontStyle (TTF_Font * font, unsigned int style = TTF_STYLE_NORMAL)
Sets the Style of an Font styles : TTF_STYLE_NORMAL TTF_STYLE_BOLD TTF_STYLE_ITALIC TTF_STYLE_UNDERLINE.
Definition at line 75 of file font.cpp.
Referenced by CreateFont().
Member Data Documentation
SDL_Color cFont::coldefBackground
Definition at line 65 of file font.h.
Referenced by cFont(), and CreateText().
SDL_Color cFont::coldefText
Definition at line 65 of file font.h.
Referenced by cFont(), and CreateText().
The documentation for this class was generated from the following files:
Engine/include/font.h
Engine/font.cpp