Meatball: cPreferences Class Reference
cPreferences Class Reference
The Preferences.
#include <include/preferences.h>
Public Member Functions
cPreferences (void)
~cPreferences (void)
void Load (void)
Loads the user Settings if no user Settings file exists loads the default settings.
void Load (string filename)
Loads an given Preferences file.
void Save (void)
Saves the Current Settings to the User Settungs File.
void Default (void)
Loads the default settings.
void Update (void)
Sets the in-game settings to the Current Settings.
void Apply (void)
Sets the Current Settings to the in-game settings.
Public Attributes
cSettings * pSettings
The Settings.
Private Member Functions
void Parse (char *command, int line)
int ParseLine (char **parts, unsigned int count, unsigned int line)
Detailed Description
The Preferences.
Definition at line 44 of file preferences.h.
Constructor & Destructor Documentation
cPreferences::cPreferences (void)
Definition at line 68 of file preferences.cpp.
cPreferences::~cPreferences (void)
Definition at line 74 of file preferences.cpp.
Member Function Documentation
void cPreferences::Apply (void)
Sets the Current Settings to the in-game settings.
Definition at line 200 of file preferences.cpp.
References cSettings::Apply(), pGameSettings, and cSettings::Update().
Referenced by ControlsMenu::Collisions(), OptionsMenu::Collisions(), ControlsMenu::EventHandler(), OptionsMenu::EventHandler(), and initEngine().
void cPreferences::Default (void)
Loads the default settings.
Definition at line 181 of file preferences.cpp.
References DEBUGLOG, DEF_PREF_NAME, and FileValid().
void cPreferences::Load (void)
Loads the user Settings if no user Settings file exists loads the default settings.
Definition at line 85 of file preferences.cpp.
References DEBUGLOG, DEF_PREF_NAME, FileValid(), and USER_PREF_NAME.
Referenced by initEngine().
void cPreferences::Load (string filename)
Loads an given Preferences file.
Definition at line 107 of file preferences.cpp.
References DEBUGLOG.
void cPreferences::Parse (char * command, int line) private
Definition at line 207 of file preferences.cpp.
int cPreferences::ParseLine (char ** parts, unsigned int count, unsigned int line) private
Definition at line 254 of file preferences.cpp.
References DEBUGLOG.
void cPreferences::Save (void)
Saves the Current Settings to the User Settungs File.
Definition at line 129 of file preferences.cpp.
References PREF_VERSION, and USER_PREF_NAME.
void cPreferences::Update (void)
Sets the in-game settings to the Current Settings.
Definition at line 194 of file preferences.cpp.
References pGameSettings.
Member Data Documentation
cSettings* cPreferences::pSettings
The Settings.
Definition at line 70 of file preferences.h.
Referenced by ControlsMenu::ControlsMenu(), CreateWindow(), ControlsMenu::GetInput(), OptionsMenu::OptionsMenu(), ControlsMenu::Update(), and OptionsMenu::Update().
The documentation for this class was generated from the following files:
include/preferences.h
preferences.cpp