Meatball: cMultiSelect Class Reference
cMultiSelect Class Reference
#include <include/MultiSelect.h>
Public Member Functions
void DrawOutlineAroundMultiSelect_Tiles (SDL_Renderer *renderer, Uint32 Color)
void SetObject (cMVelSprite *nObject)
Add to OM array.
void SetObjects (void)
void Move (void)
void InitTiles (SDL_bool release=SDL_FALSE)
void PrepareToMove ()
SDL_bool GetAllCollidingObjects (SDL_Rect *crect, ObjectManager< cMVelSprite > *obj_man)
SDL_bool Release ()
Releases any MultiSelect_ selected object.
Public Attributes
SDL_bool multiple_objects_selected
double veryfirst_mouseXOffset
these very first ones are because I want to show the grid around selected tiles all the way until the point that the tiles actually start moving
double veryfirst_mouseYOffset
double mouseXOffset
double mouseYOffset
double camXOffset
double camYOffset
SDL_Rect rect
double rectX_origin
double rectY_origin
SDL_bool rect_XDirection
SDL_bool rect_YDirection
ObjectManager< cMVelSprite > OM
Detailed Description
Definition at line 9 of file MultiSelect.h.
Member Function Documentation
void cMultiSelect::DrawOutlineAroundMultiSelect_Tiles (SDL_Renderer * renderer, Uint32 Color)
Definition at line 11 of file MultiSelect.cpp.
References cMVelSprite::GetRect(), multiple_objects_selected, ObjectManager< T >::objcount, ObjectManager< T >::objects, OM, and cLevelEditor::OutlineObject().
Referenced by cLevelEditor::Draw().
SDL_bool cMultiSelect::GetAllCollidingObjects (SDL_Rect * crect, ObjectManager< cMVelSprite > * obj_man)
Definition at line 74 of file MultiSelect.cpp.
References ObjectManager< T >::add(), cLevelData::GetAllCollidingSpriteNum(), cMVelSprite::GetRect(), ObjectManager< T >::hasa(), cLevel::pLevelData_Layer1, and RectIntersect().
Referenced by SetObjects().
void cMultiSelect::InitTiles (SDL_bool release = SDL_FALSE)
Definition at line 110 of file MultiSelect.cpp.
References cLevelEditor::Mouse_command, MOUSE_COMMAND_SELECT_MULTISELECT_TILES, mouseXOffset, mouseYOffset, pMouse, cBasicSprite::posx, cBasicSprite::posy, rect, rectX_origin, rectY_origin, and Release().
Referenced by cLevelEditor::EventHandler().
void cMultiSelect::Move (void)
Definition at line 59 of file MultiSelect.cpp.
References camXOffset, camYOffset, mouseXOffset, mouseYOffset, ObjectManager< T >::objcount, ObjectManager< T >::objects, OM, pMouse, cBasicSprite::posx, cBasicSprite::posy, cBasicSprite::SetPos(), cMVelSprite::Startposx, cMVelSprite::Startposy, cCamera::x, and cCamera::y.
Referenced by cLevelEditor::Update().
void cMultiSelect::PrepareToMove ()
Definition at line 131 of file MultiSelect.cpp.
References camXOffset, camYOffset, cLevelEditor::Mouse_command, MOUSE_COMMAND_MOVING_MULTISELECT_TILES, mouseXOffset, mouseYOffset, pMouse, cBasicSprite::posx, cBasicSprite::posy, veryfirst_mouseXOffset, veryfirst_mouseYOffset, cCamera::x, and cCamera::y.
Referenced by cLevelEditor::EventHandler().
SDL_bool cMultiSelect::Release ()
Releases any MultiSelect_ selected object.
Returns
SDL_TRUE if there were objects to remove, SDL_FALSE if there wasnt
Definition at line 142 of file MultiSelect.cpp.
References multiple_objects_selected, OM, and ObjectManager< T >::RemoveAllObjects().
Referenced by cLevelEditor::EventHandler(), and InitTiles().
void cMultiSelect::SetObject (cMVelSprite * nObject)
Add to OM array.
Definition at line 38 of file MultiSelect.cpp.
References ObjectManager< T >::add(), ObjectManager< T >::hasa(), multiple_objects_selected, OM, and ObjectManager< T >::Remove().
Referenced by cLevelEditor::EventHandler().
void cMultiSelect::SetObjects (void)
Definition at line 30 of file MultiSelect.cpp.
References GetAllCollidingObjects(), multiple_objects_selected, ObjectManager< T >::objcount, OM, and rect.
Referenced by cLevelEditor::EventHandler().
Member Data Documentation
double cMultiSelect::camXOffset
Definition at line 42 of file MultiSelect.h.
Referenced by Move(), and PrepareToMove().
double cMultiSelect::camYOffset
Definition at line 42 of file MultiSelect.h.
Referenced by Move(), and PrepareToMove().
double cMultiSelect::mouseXOffset
Definition at line 41 of file MultiSelect.h.
Referenced by InitTiles(), Move(), and PrepareToMove().
double cMultiSelect::mouseYOffset
Definition at line 41 of file MultiSelect.h.
Referenced by InitTiles(), Move(), and PrepareToMove().
SDL_bool cMultiSelect::multiple_objects_selected
Definition at line 35 of file MultiSelect.h.
Referenced by DrawOutlineAroundMultiSelect_Tiles(), cLevelEditor::EventHandler(), Release(), SetObject(), and SetObjects().
ObjectManager<cMVelSprite> cMultiSelect::OM
Definition at line 52 of file MultiSelect.h.
Referenced by DrawOutlineAroundMultiSelect_Tiles(), cLevelEditor::EventHandler(), Move(), Release(), SetObject(), and SetObjects().
SDL_Rect cMultiSelect::rect
Definition at line 44 of file MultiSelect.h.
Referenced by cLevelEditor::Draw(), InitTiles(), SetObjects(), and cLevelEditor::Update().
SDL_bool cMultiSelect::rect_XDirection
Definition at line 48 of file MultiSelect.h.
SDL_bool cMultiSelect::rect_YDirection
Definition at line 49 of file MultiSelect.h.
double cMultiSelect::rectX_origin
Definition at line 46 of file MultiSelect.h.
Referenced by InitTiles(), and cLevelEditor::Update().
double cMultiSelect::rectY_origin
Definition at line 46 of file MultiSelect.h.
Referenced by InitTiles(), and cLevelEditor::Update().
double cMultiSelect::veryfirst_mouseXOffset
these very first ones are because I want to show the grid around selected tiles all the way until the point that the tiles actually start moving
Definition at line 39 of file MultiSelect.h.
Referenced by cLevelEditor::Draw(), and PrepareToMove().
double cMultiSelect::veryfirst_mouseYOffset
Definition at line 39 of file MultiSelect.h.
Referenced by cLevelEditor::Draw(), and PrepareToMove().
The documentation for this class was generated from the following files:
include/MultiSelect.h
MultiSelect.cpp