Meatball: cAudio Class Reference
cAudio Class Reference
Audio
#include <Engine/include/audio.h>
Public Member Functions
DLLINTERFACE cAudio (SDL_bool playMusic=SDL_TRUE, SDL_bool playSounds=SDL_TRUE, Uint8 MusicVol=80, Uint8 SoundVol=110)
DLLINTERFACE ~cAudio (void)
DLLINTERFACE void InitAudio (void)
Initializes the Audio with the specified settings.
DLLINTERFACE void ReserveChannels (int num)
Reserves Channels for default mixing.
DLLINTERFACE void AllocateChannels (int num)
Channels for Mixing.
DLLINTERFACE Mix_Chunk * LoadSound (const char *filename, int sVolume=-2)
Loads an sound if volume is -1 the default sound volume will be used if volume is -2 no volume will be set.
DLLINTERFACE int PlaySound (Mix_Chunk *sound, int channel=-1, int sVolume=-1)
Plays an Sound chunk if channel is -1 the sound will be played on the next free channel if volume is -1 the default volume will be used if volume is -2 no volume will be set.
DLLINTERFACE void PlayMusik (const char *filename, int loops=-1, SDL_bool force=SDL_TRUE)
if no forcing the file will be played after the current Music file if loops is -1 music will be looped infinity Can play WAVE, MOD, MIDI, OGG (with ogg vorbis), mp3 (with smpeg)
DLLINTERFACE void LoadMusic (const char *filename)
DLLINTERFACE void StopMusic (void)
Stops playing Music.
DLLINTERFACE void FadeOutMusic (unsigned int ms)
Fades the music out for the given miliseconds.
DLLINTERFACE void PauseMusic (void)
Pauses playing Music.
DLLINTERFACE void ResumeMusic (void)
Resumes Paused Music.
DLLINTERFACE void HaltSounds (int channel=-1)
Halt playback on specified channels or all if -1 set.
DLLINTERFACE void PauseSounds (int channel=-1)
Stops specified Sounds/Channels or all if -1 set.
DLLINTERFACE void ResumeSounds (int channel=-1)
Resume Playing specified sounds if got stopped or all if -1 set.
DLLINTERFACE void DeleteSounds (void)
Deletes The Temporary Sound Buffer .
DLLINTERFACE void FadeOutSounds (int milliseconds=2000, int channel=-1)
Fades Sounds out if channel is -1 fades all sounds out.
DLLINTERFACE int SetSoundVolume (Mix_Chunk *chunk, Uint8 iVolume)
Set a specific sound's volume with it's chunk ptr.
DLLINTERFACE int GetSoundVolume (Mix_Chunk *chunk)
DLLINTERFACE int SetAllSoundsVolume (Uint8 iVolume)
Sets All the Sounds default Volume
Returns avg_volume
DLLINTERFACE int SetMusicVolume (Uint8 iVolume)
Sets the Music default Volume.
DLLINTERFACE void Update (void)
Checks if no music is played.
DLLINTERFACE SDL_bool MusicPlaying ()
Public Attributes
Mix_Music * Music
int iHz
int iBuffer
int iChannels
int Sounds_Played
int Music_Played
Uint8 Sound_Volume
Uint8 Music_Volume
SDL_bool bSounds
SDL_bool bMusic
SDL_bool bDebug
SDL_bool bInitialised
Detailed Description
Definition at line 23 of file audio.h.
Constructor & Destructor Documentation
cAudio::cAudio (SDL_bool playMusic = SDL_TRUE, SDL_bool playSounds = SDL_TRUE, Uint8 MusicVol = 80, Uint8 SoundVol = 110)
Definition at line 7 of file audio.cpp.
cAudio::~cAudio (void)
Definition at line 30 of file audio.cpp.
Member Function Documentation
void cAudio::AllocateChannels (int num)
Channels for Mixing.
Do not use !
Definition at line 93 of file audio.cpp.
DLLINTERFACE void cAudio::DeleteSounds (void)
Deletes The Temporary Sound Buffer .
void cAudio::FadeOutMusic (unsigned int ms)
Fades the music out for the given miliseconds.
Definition at line 232 of file audio.cpp.
Referenced by MainMenu::Do().
void cAudio::FadeOutSounds (int milliseconds = 2000, int channel = -1)
Fades Sounds out if channel is -1 fades all sounds out.
Definition at line 271 of file audio.cpp.
int cAudio::GetSoundVolume (Mix_Chunk * chunk)
Definition at line 276 of file audio.cpp.
Referenced by soundVol().
void cAudio::HaltSounds (int channel = -1)
Halt playback on specified channels or all if -1 set.
Definition at line 254 of file audio.cpp.
void cAudio::InitAudio (void)
Initializes the Audio with the specified settings.
Initialising prefered Audio System specs with Mixer Standard format (Stereo)
format : Output sample format. channels : Number of sound channels in output. Set to 2 for stereo, 1 for mono. This chunksize : Bytes used per output sample.
Definition at line 47 of file audio.cpp.
Referenced by initEngine().
void cAudio::LoadMusic (const char * filename)
Definition at line 191 of file audio.cpp.
Mix_Chunk * cAudio::LoadSound (const char * filename, int sVolume = -2)
Loads an sound if volume is -1 the default sound volume will be used if volume is -2 no volume will be set.
Definition at line 105 of file audio.cpp.
Referenced by cWeapon_Laser_X1::cWeapon_Laser_X1(), cWeapon_Machinegun::cWeapon_Machinegun(), cWeapon_Pistol::cWeapon_Pistol(), MainMenu::MainMenu(), and OptionsMenu::OptionsMenu().
SDL_bool cAudio::MusicPlaying ()
Definition at line 327 of file audio.cpp.
Referenced by Game::Init(), and OptionsMenu::Update().
void cAudio::PauseMusic (void)
Pauses playing Music.
Definition at line 241 of file audio.cpp.
void cAudio::PauseSounds (int channel = -1)
Stops specified Sounds/Channels or all if -1 set.
Definition at line 259 of file audio.cpp.
void cAudio::PlayMusik (const char * filename, int loops = -1, SDL_bool force = SDL_TRUE)
if no forcing the file will be played after the current Music file if loops is -1 music will be looped infinity Can play WAVE, MOD, MIDI, OGG (with ogg vorbis), mp3 (with smpeg)
Definition at line 199 of file audio.cpp.
Referenced by Game::Init(), MainMenu::MainMenu(), Playlist::musicover(), play(), OptionsMenu::Update(), and cLevel::Update().
int cAudio::PlaySound (Mix_Chunk * sound, int channel = -1, int sVolume = -1)
Plays an Sound chunk if channel is -1 the sound will be played on the next free channel if volume is -1 the default volume will be used if volume is -2 no volume will be set.
Definition at line 144 of file audio.cpp.
Referenced by MainMenu::Do(), cWeapon_Pistol::Fire(), cWeapon_Machinegun::Fire(), cWeapon_Laser_X1::Fire(), and playSoundEffect().
void cAudio::ReserveChannels (int num)
Reserves Channels for default mixing.
Definition at line 83 of file audio.cpp.
void cAudio::ResumeMusic (void)
Resumes Paused Music.
Definition at line 249 of file audio.cpp.
void cAudio::ResumeSounds (int channel = -1)
Resume Playing specified sounds if got stopped or all if -1 set.
Definition at line 265 of file audio.cpp.
int cAudio::SetAllSoundsVolume (Uint8 iVolume)
Sets All the Sounds default Volume
Returns avg_volume
Doesn't really Work :|.
Definition at line 301 of file audio.cpp.
Referenced by allSoundsVol(), and OptionsMenu::Update().
int cAudio::SetMusicVolume (Uint8 iVolume)
Sets the Music default Volume.
Definition at line 313 of file audio.cpp.
Referenced by musicVol(), and OptionsMenu::Update().
int cAudio::SetSoundVolume (Mix_Chunk * chunk, Uint8 iVolume)
Set a specific sound's volume with it's chunk ptr.
Definition at line 289 of file audio.cpp.
Referenced by soundVol().
void cAudio::StopMusic (void)
Stops playing Music.
Definition at line 224 of file audio.cpp.
void cAudio::Update (void)
Checks if no music is played.
Definition at line 332 of file audio.cpp.
Referenced by OptionsMenu::PreUpdate(), and MainMenu::UpdateHardware().
Member Data Documentation
SDL_bool cAudio::bDebug
Definition at line 126 of file audio.h.
SDL_bool cAudio::bInitialised
Definition at line 127 of file audio.h.
SDL_bool cAudio::bMusic
Definition at line 126 of file audio.h.
Referenced by cSettings::Apply(), and initEngine().
SDL_bool cAudio::bSounds
Definition at line 126 of file audio.h.
Referenced by cSettings::Apply(), and initEngine().
int cAudio::iBuffer
Definition at line 121 of file audio.h.
int cAudio::iChannels
Definition at line 121 of file audio.h.
int cAudio::iHz
Definition at line 121 of file audio.h.
Mix_Music* cAudio::Music
Definition at line 119 of file audio.h.
Referenced by Game::Init().
int cAudio::Music_Played
Definition at line 122 of file audio.h.
Uint8 cAudio::Music_Volume
Definition at line 124 of file audio.h.
Referenced by initEngine(), and musicVol().
Uint8 cAudio::Sound_Volume
Definition at line 124 of file audio.h.
Referenced by cSettings::Apply(), initEngine(), and soundVol().
int cAudio::Sounds_Played
Definition at line 122 of file audio.h.
The documentation for this class was generated from the following files:
Engine/include/audio.h
Engine/audio.cpp