Meatball: cTCPNet Class Reference
cTCPNet Class Reference
Networking
The TCP SDL_Net Class.
#include <Engine/include/net.h>
Public Member Functions
DLLINTERFACE cTCPNet (unsigned int nport=9877)
DLLINTERFACE ~cTCPNet (void)
DLLINTERFACE int Server_Start (void)
Starts an Server returns 0 if already connected or an error.
DLLINTERFACE int Server_ConnectionCheck (void)
Checks for an connecting request from an remote client used internally.
DLLINTERFACE int Client_Connect (string &address)
Connects to an server returns 0 if there were no success and 1 on success.
DLLINTERFACE int Read_Message (TCPsocket sock, string &message)
Reads the Message Returns 0 if an error occured or not connected to anyone.
DLLINTERFACE void Send_Message_Auto (const string message)
Sends the Message to all Connections you have uses Send_message if you're an Client else Server_SenGlobalMessage if you're an Server.
DLLINTERFACE void Server_SendGlobalMessage (const string message)
Sends an Message to ervery Client.
DLLINTERFACE int Send_Message (TCPsocket sock, const string message)
Sends an Message Returns 0 if an error occured or not connected to anyone.
DLLINTERFACE int Shutdown (void)
Closes every Connection returns 0 if there were no connections or opened sockets.
DLLINTERFACE int Check_Sockets (void)
Checks if an message arrived returns the number of messages.
DLLINTERFACE int Alloc_Socketset (void)
Allocates an Socketset for buffer message checking used internally.
DLLINTERFACE void Free_Socketset (void)
Frees the Socketset.
DLLINTERFACE Uint32 Client_GetIP (void)
Returns the Server IP in an integer without points returns 0 if not succesfully Connected ir not an client.
DLLINTERFACE Uint16 GetPort (void)
Returns the currently used port returns 0 if not succesfully hosted or not an connected client.
DLLINTERFACE void SetPort (Uint16 nport)
Sets the used port for Hosting and Connecting Should only be used if not Connected (Idle)
DLLINTERFACE void Server_NoNewConnections (void)
Disables new Connections Connected Server Only.
DLLINTERFACE void Server_DisconnectClient (TCPsocket sock)
Disconnects an specific Client Connected Server Only.
DLLINTERFACE void Update (void)
Checks for messages and closes the connection if the remote user disconnected The messages are handled by the handlemessage(string message) function.
DLLINTERFACE char * c_strNC (const string &theString)
1.8
Public Attributes
vector< cClient > clients
The Clients if the current state is Server theres no maximum else if client the first Client is the Remote Server you're Connected to.
IPaddress ip
undefined - is it only temporary ?!?
TCPsocket csocket
Your Connection Socket.
Uint16 port
The Standard port used.
int state
The Current Network state : 0 = Idle 1 = Hosting Not Connected to anyone 2 = Hosting Connected 3 = Client Connected.
SDLNet_SocketSet socketset
Detailed Description
The TCP SDL_Net Class.
Definition at line 71 of file net.h.
Constructor & Destructor Documentation
cTCPNet::cTCPNet (unsigned int nport = 9877)
Definition at line 54 of file net.cpp.
References csocket, ip, port, socketset, state, and STATE_IDLE.
cTCPNet::~cTCPNet (void)
Definition at line 68 of file net.cpp.
References Shutdown().
Member Function Documentation
int cTCPNet::Alloc_Socketset (void)
Allocates an Socketset for buffer message checking used internally.
Definition at line 512 of file net.cpp.
References clients, csocket, Free_Socketset(), Shutdown(), socketset, state, STATE_CLIENT_CONNECTED, STATE_HOSTING_CONNECTED, and STATE_HOSTING_EMPTY.
Referenced by Client_Connect(), Server_ConnectionCheck(), Server_DisconnectClient(), and Server_Start().
char * cTCPNet::c_strNC (const string & theString)
1.8
Adds the terminating NULL in an char *
Definition at line 728 of file net.cpp.
Referenced by Send_Message().
int cTCPNet::Check_Sockets (void)
Checks if an message arrived returns the number of messages.
Definition at line 489 of file net.cpp.
References Shutdown(), and socketset.
Referenced by Update().
int cTCPNet::Client_Connect (string & address)
Connects to an server returns 0 if there were no success and 1 on success.
Definition at line 161 of file net.cpp.
References Alloc_Socketset(), csocket, ip, port, state, STATE_CLIENT_CONNECTED, and STATE_IDLE.
Uint32 cTCPNet::Client_GetIP (void)
Returns the Server IP in an integer without points returns 0 if not succesfully Connected ir not an client.
Definition at line 573 of file net.cpp.
References ip, state, and STATE_CLIENT_CONNECTED.
void cTCPNet::Free_Socketset (void)
Frees the Socketset.
Definition at line 561 of file net.cpp.
References socketset.
Referenced by Alloc_Socketset(), and Shutdown().
Uint16 cTCPNet::GetPort (void)
Returns the currently used port returns 0 if not succesfully hosted or not an connected client.
Definition at line 586 of file net.cpp.
References port.
int cTCPNet::Read_Message (TCPsocket sock, string & message)
Reads the Message Returns 0 if an error occured or not connected to anyone.
Definition at line 214 of file net.cpp.
References MAX_BUFFER_SIZE, Server_DisconnectClient(), Shutdown(), state, STATE_CLIENT_CONNECTED, STATE_HOSTING_EMPTY, and STATE_IDLE.
Referenced by Update().
int cTCPNet::Send_Message (TCPsocket sock, const string message)
Sends an Message Returns 0 if an error occured or not connected to anyone.
Definition at line 369 of file net.cpp.
References c_strNC(), Server_DisconnectClient(), Shutdown(), state, STATE_CLIENT_CONNECTED, and STATE_HOSTING_EMPTY.
Referenced by Send_Message_Auto(), and Server_SendGlobalMessage().
void cTCPNet::Send_Message_Auto (const string message)
Sends the Message to all Connections you have uses Send_message if you're an Client else Server_SenGlobalMessage if you're an Server.
Definition at line 330 of file net.cpp.
References csocket, Send_Message(), Server_SendGlobalMessage(), state, STATE_CLIENT_CONNECTED, and STATE_HOSTING_CONNECTED.
int cTCPNet::Server_ConnectionCheck (void)
Checks for an connecting request from an remote client used internally.
Definition at line 118 of file net.cpp.
References Alloc_Socketset(), clients, csocket, port, state, STATE_HOSTING_CONNECTED, and STATE_HOSTING_EMPTY.
Referenced by Update().
void cTCPNet::Server_DisconnectClient (TCPsocket sock)
Disconnects an specific Client Connected Server Only.
Definition at line 623 of file net.cpp.
References Alloc_Socketset(), clients, Shutdown(), state, and STATE_HOSTING_CONNECTED.
Referenced by Read_Message(), and Send_Message().
void cTCPNet::Server_NoNewConnections (void)
Disables new Connections Connected Server Only.
Definition at line 609 of file net.cpp.
References csocket, state, and STATE_HOSTING_CONNECTED.
void cTCPNet::Server_SendGlobalMessage (const string message)
Sends an Message to ervery Client.
Definition at line 345 of file net.cpp.
References clients, Send_Message(), state, and STATE_HOSTING_CONNECTED.
Referenced by Send_Message_Auto().
int cTCPNet::Server_Start (void)
Starts an Server returns 0 if already connected or an error.
Definition at line 76 of file net.cpp.
References Alloc_Socketset(), csocket, ip, port, state, STATE_HOSTING_EMPTY, and STATE_IDLE.
void cTCPNet::SetPort (Uint16 nport)
Sets the used port for Hosting and Connecting Should only be used if not Connected (Idle)
Definition at line 594 of file net.cpp.
References port, state, and STATE_IDLE.
int cTCPNet::Shutdown (void)
Closes every Connection returns 0 if there were no connections or opened sockets.
Definition at line 438 of file net.cpp.
References clients, csocket, Free_Socketset(), ip, state, STATE_CLIENT_CONNECTED, STATE_HOSTING_CONNECTED, STATE_HOSTING_EMPTY, and STATE_IDLE.
Referenced by Alloc_Socketset(), Check_Sockets(), Read_Message(), Send_Message(), Server_DisconnectClient(), and ~cTCPNet().
void cTCPNet::Update (void)
Checks for messages and closes the connection if the remote user disconnected The messages are handled by the handlemessage(string message) function.
Definition at line 661 of file net.cpp.
References Check_Sockets(), clients, csocket, NetMessageHandler(), Read_Message(), Server_ConnectionCheck(), state, STATE_CLIENT_CONNECTED, STATE_HOSTING_CONNECTED, STATE_HOSTING_EMPTY, and STATE_IDLE.
Member Data Documentation
vector<cClient> cTCPNet::clients
The Clients if the current state is Server theres no maximum else if client the first Client is the Remote Server you're Connected to.
Definition at line 169 of file net.h.
Referenced by Alloc_Socketset(), Server_ConnectionCheck(), Server_DisconnectClient(), Server_SendGlobalMessage(), Shutdown(), and Update().
TCPsocket cTCPNet::csocket
Your Connection Socket.
Definition at line 174 of file net.h.
Referenced by Alloc_Socketset(), Client_Connect(), cTCPNet(), Send_Message_Auto(), Server_ConnectionCheck(), Server_NoNewConnections(), Server_Start(), Shutdown(), and Update().
IPaddress cTCPNet::ip
undefined - is it only temporary ?!?
Definition at line 172 of file net.h.
Referenced by Client_Connect(), Client_GetIP(), cTCPNet(), Server_Start(), and Shutdown().
Uint16 cTCPNet::port
The Standard port used.
Definition at line 176 of file net.h.
Referenced by Client_Connect(), cTCPNet(), GetPort(), Server_ConnectionCheck(), Server_Start(), and SetPort().
SDLNet_SocketSet cTCPNet::socketset
Definition at line 186 of file net.h.
Referenced by Alloc_Socketset(), Check_Sockets(), cTCPNet(), and Free_Socketset().
int cTCPNet::state
The Current Network state : 0 = Idle 1 = Hosting Not Connected to anyone 2 = Hosting Connected 3 = Client Connected.
Definition at line 184 of file net.h.
Referenced by Alloc_Socketset(), Client_Connect(), Client_GetIP(), cTCPNet(), Read_Message(), Send_Message(), Send_Message_Auto(), Server_ConnectionCheck(), Server_DisconnectClient(), Server_NoNewConnections(), Server_SendGlobalMessage(), Server_Start(), SetPort(), Shutdown(), and Update().
The documentation for this class was generated from the following files:
Engine/include/net.h
Engine/net.cpp