Meatball: cLevel Class Reference
cLevel Class Reference
Levels
Basic Level Class This time maybe with Alpha,glimming and Animation support ?
#include <include/level.h>
Public Member Functions
cLevel (void)
~cLevel (void)
void PrintSaveHeader ()
void SavePlayerPos ()
void SaveMusicFile ()
void SaveMapObjects ()
void SaveMapEnemies ()
void Load (string filename)
Loads an Level.
void Unload (void)
Unloads the Level.
void Save (void)
Saves the Current Level.
void Update (void)
Updates the Level.
void Draw (void)
Draws the Level.
Public Attributes
string levelfile
The Level File.
cLevelData * pLevelData_Layer1
The Level Data.
cLevelData * pLevelData_Layer2
Private Member Functions
void Parse (char *command, int line)
Cuts the parts out and sends it to the ParseLine function.
int ParseLine (char **parts, unsigned int count, unsigned int line)
Parses the Command and also reports any Error.
Private Attributes
char row [300]
unsigned int i
std::ofstream * ofs
Detailed Description
Basic Level Class This time maybe with Alpha,glimming and Animation support ?
Definition at line 54 of file level.h.
Constructor & Destructor Documentation
cLevel::cLevel (void)
Definition at line 144 of file level.cpp.
References levelfile, and pLevelData_Layer1.
cLevel::~cLevel (void)
Definition at line 150 of file level.cpp.
References Unload().
Member Function Documentation
void cLevel::Draw (void)
Draws the Level.
Definition at line 337 of file level.cpp.
References cLevelData::BasicSprites, cMVelSprite::Draw(), i, ObjectManager< T >::objcount, ObjectManager< T >::objects, pLevelData_Layer1, Renderer, and cMVelSprite::Update().
Referenced by MiniEngine::PreDraw().
void cLevel::Load (string filename)
Loads an Level.
Definition at line 155 of file level.cpp.
References DEBUGLOG, DeleteAllBullets(), DeleteAllEnemies(), DeleteAllParticleEmitter(), FileValid(), i, LEVEL_DIR, levelfile, Parse(), pFramerate, pLevelData_Layer1, cFramerate::Reset(), and Unload().
Referenced by Game::Init(), and loadmap().
void cLevel::Parse (char * command, int line) private
Cuts the parts out and sends it to the ParseLine function.
Definition at line 366 of file level.cpp.
References i, and ParseLine().
Referenced by Load().
int cLevel::ParseLine (char ** parts, unsigned int count, unsigned int line) private
Parses the Command and also reports any Error.
Definition at line 419 of file level.cpp.
References cImageManager::Add(), AddEnemy(), cLevelData::AddSprite(), colorkey, DEBUGLOG, ENEMY_AF373, FileValid(), cImageManager::GetPointer(), IMan, is_valid_number(), levelfile, LoadImage(), MUSIC_DIR, cLevelData::Musicfile, PIXMAPS_DIR, pLevelData_Layer1, cBasicSprite::SetPos(), SPRITE_TYPE_HALFMASSIVE, SPRITE_TYPE_MASSIVE, SPRITE_TYPE_PASSIVE, cMVelSprite::Startposx, cMVelSprite::Startposy, cMVelSprite::type, and window_height.
Referenced by Parse().
void cLevel::PrintSaveHeader ()
Definition at line 233 of file level.cpp.
References Get_Curr_Date(), ofs, and row.
Referenced by Save().
void cLevel::Save (void)
Saves the Current Level.
Definition at line 203 of file level.cpp.
References DEBUGLOG, FileValid(), LEVEL_DIR, levelfile, ofs, PrintSaveHeader(), SaveMapEnemies(), SaveMapObjects(), SaveMusicFile(), and SavePlayerPos().
Referenced by cLevelEditor::EventHandler().
void cLevel::SaveMapEnemies ()
Definition at line 296 of file level.cpp.
References DEBUGLOG, Enemies, ENEMY_AF373, i, ofs, and row.
Referenced by Save().
void cLevel::SaveMapObjects ()
Definition at line 254 of file level.cpp.
References cLevelData::BasicSprites, DEBUGLOG, cImageManager::GetIdentifier(), i, IMan, ObjectManager< T >::objcount, ObjectManager< T >::objects, ofs, PIXMAPS_DIR, pLevelData_Layer1, cBasicSprite::posx, cBasicSprite::posy, row, SPRITE_TYPE_HALFMASSIVE, SPRITE_TYPE_MASSIVE, SPRITE_TYPE_PASSIVE, cBasicSprite::srcimage, cMVelSprite::type, and window_height.
Referenced by Save().
void cLevel::SaveMusicFile ()
Definition at line 248 of file level.cpp.
References cLevelData::Musicfile, ofs, pLevelData_Layer1, and row.
Referenced by Save().
void cLevel::SavePlayerPos ()
Definition at line 242 of file level.cpp.
References ofs, row, cMVelSprite::Startposx, cMVelSprite::Startposy, and window_height.
Referenced by Save().
void cLevel::Unload (void)
Unloads the Level.
Definition at line 192 of file level.cpp.
References levelfile, and pLevelData_Layer1.
Referenced by Load(), and ~cLevel().
void cLevel::Update (void)
Updates the Level.
Definition at line 324 of file level.cpp.
References MUSIC_DIR, cLevelData::Musicfile, pAudio, cAudio::PlayMusik(), and pLevelData_Layer1.
Referenced by Game::Update().
Member Data Documentation
unsigned int cLevel::i private
Definition at line 100 of file level.h.
Referenced by Draw(), Load(), Parse(), SaveMapEnemies(), and SaveMapObjects().
string cLevel::levelfile
The Level File.
Definition at line 86 of file level.h.
Referenced by cLevel(), Load(), ParseLine(), Save(), and Unload().
std::ofstream* cLevel::ofs private
Definition at line 101 of file level.h.
Referenced by PrintSaveHeader(), Save(), SaveMapEnemies(), SaveMapObjects(), SaveMusicFile(), and SavePlayerPos().
cLevelData* cLevel::pLevelData_Layer1
The Level Data.
Definition at line 89 of file level.h.
Referenced by cLevel(), cLevelEditor::DeleteObject(), Draw(), cMultiSelect::GetAllCollidingObjects(), cLevelEditor::GetCollidingObject(), Game::Init(), Load(), ParseLine(), cLevelEditor::PasteObject(), play(), PositionCheck(), SaveMapObjects(), SaveMusicFile(), Unload(), and Update().
cLevelData* cLevel::pLevelData_Layer2
Definition at line 90 of file level.h.
char cLevel::row[300] private
Definition at line 99 of file level.h.
Referenced by PrintSaveHeader(), SaveMapEnemies(), SaveMapObjects(), SaveMusicFile(), and SavePlayerPos().
The documentation for this class was generated from the following files:
include/level.h
level.cpp