Meatball: OptionsMenu Class Reference
OptionsMenu Class Reference
#include <include/OptionsMenu.h>
Public Member Functions
OptionsMenu ()
~OptionsMenu ()
void Do ()
void PreUpdate ()
Does general things.
void Update ()
void Draw ()
void EventHandler ()
void Collisions ()
void LiveInput ()
Public Member Functions inherited from MiniEngine
virtual void PostUpdate (void)
virtual void PreDraw (void)
virtual void PostDraw (void)
virtual void Input ()
virtual void HeldKey_Handler ()
Public Attributes
Uint8 status
ControlsMenu controls_menu
TTF_Font * optionsfont
TextObject * tExit
TextObject * tMusicVol
TextObject * tSoundVol
TextObject * tControls
TextObject * tFullscreen
TextObject * tScreenWidth
TextObject * tScreenHeight
TextObject * tScreenBpp
Slider * sMusicVol
Slider * sSoundVol
double ttDrawCur
SDL_bool DrawCur
string livestring
unsigned int CurrentScreen
Static Public Attributes
static Screens curscreen =OPTIONS_SCREEN
Detailed Description
Definition at line 56 of file OptionsMenu.h.
Constructor & Destructor Documentation
OptionsMenu::OptionsMenu ()
Definition at line 18 of file OptionsMenu.cpp.
References cSoundManager::Add(), BROWSING, cFont::CreateFont(), FONT_DIR, Slider::getPixelValueFromTargetValue(), cAudio::LoadSound(), cSettings::mvol, optionsfont, Slider::panel_x, pAudio, pFont, cPreferences::pSettings, GraphicsObject::rect, TextObject::Render(), Slider::SetAdjusterXOffset(), SetColor(), TextObject::SetFGColor(), SMan, sMusicVol, SOUNDS_DIR, sSoundVol, status, GraphicsObject::surface, cSettings::svol, tControls, tExit, tMusicVol, tSoundVol, and window_height.
OptionsMenu::~OptionsMenu ()
Definition at line 52 of file OptionsMenu.cpp.
References optionsfont, sMusicVol, sSoundVol, tControls, tExit, tMusicVol, and tSoundVol.
Member Function Documentation
void OptionsMenu::Collisions ()
Definition at line 242 of file OptionsMenu.cpp.
References Slider::Activate(), Slider::adjuster_rect, cPreferences::Apply(), BROWSING, CONTROLS_SCREEN, curscreen, DEBUGLOG, event, cMouseCursor::hide(), MAIN, MouseCollidesWith(), pMouse, GraphicsObject::rect, cMouseCursor::show(), SLIDING_MVOL, SLIDING_SVOL, sMusicVol, sSoundVol, status, MainMenu::submode, tControls, and tExit.
Referenced by EventHandler().
void OptionsMenu::Do () virtual
Reimplemented from MiniEngine.
Definition at line 69 of file OptionsMenu.cpp.
References controls_menu, CONTROLS_SCREEN, curscreen, ControlsMenu::Draw(), Draw(), ControlsMenu::EventHandler(), EventHandler(), OPTIONS_SCREEN, PreUpdate(), ControlsMenu::Update(), and Update().
Referenced by MainMenu::Do().
void OptionsMenu::Draw (void) virtual
Reimplemented from MiniEngine.
Definition at line 127 of file OptionsMenu.cpp.
References Slider::Draw(), TextObject::Draw(), cBasicSprite::Draw(), pMouse, MiniEngine::PostDraw(), Renderer, sMusicVol, sSoundVol, tControls, tExit, tMusicVol, and tSoundVol.
Referenced by Do().
void OptionsMenu::EventHandler (void) virtual
Reimplemented from MiniEngine.
Definition at line 205 of file OptionsMenu.cpp.
References cPreferences::Apply(), Collisions(), done, event, MAIN, MODE_QUIT, MainMenu::submode, and UniversalEventHandler().
Referenced by Do().
void OptionsMenu::LiveInput (void)
Definition at line 149 of file OptionsMenu.cpp.
References done, event, livestring, mode, and oldmode.
void OptionsMenu::PreUpdate (void) virtual
Does general things.
Reimplemented from MiniEngine.
Definition at line 87 of file OptionsMenu.cpp.
References pAudio, pFramerate, pMouse, Renderer, cFramerate::SetSpeedFactor(), cAudio::Update(), and cMouseCursor::Update().
Referenced by Do(), and Update().
void OptionsMenu::Update (void) virtual
Reimplemented from MiniEngine.
Definition at line 93 of file OptionsMenu.cpp.
References Slider::getTargetValue(), MUSIC_DIR, cAudio::MusicPlaying(), cSettings::mvol, pAudio, cAudio::PlayMusik(), playSoundEffect(), pMouse, cBasicSprite::posx, PreUpdate(), cPreferences::pSettings, cAudio::SetAllSoundsVolume(), cAudio::SetMusicVolume(), Slider::Slide(), SLIDING_MVOL, SLIDING_SVOL, sMusicVol, sSoundVol, status, cSettings::svol, tControls, tExit, tMusicVol, tSoundVol, and TextObject::Update().
Referenced by Do().
Member Data Documentation
ControlsMenu OptionsMenu::controls_menu
Definition at line 64 of file OptionsMenu.h.
Referenced by Do().
unsigned int OptionsMenu::CurrentScreen
Definition at line 90 of file OptionsMenu.h.
Screens OptionsMenu::curscreen =OPTIONS_SCREEN static
Definition at line 61 of file OptionsMenu.h.
Referenced by ControlsMenu::Collisions(), Collisions(), Do(), and ControlsMenu::EventHandler().
SDL_bool OptionsMenu::DrawCur
Definition at line 88 of file OptionsMenu.h.
string OptionsMenu::livestring
Definition at line 89 of file OptionsMenu.h.
Referenced by LiveInput().
TTF_Font* OptionsMenu::optionsfont
Definition at line 77 of file OptionsMenu.h.
Referenced by OptionsMenu(), and ~OptionsMenu().
Slider* OptionsMenu::sMusicVol
Definition at line 85 of file OptionsMenu.h.
Referenced by Collisions(), Draw(), OptionsMenu(), Update(), and ~OptionsMenu().
Slider * OptionsMenu::sSoundVol
Definition at line 85 of file OptionsMenu.h.
Referenced by Collisions(), Draw(), OptionsMenu(), Update(), and ~OptionsMenu().
Uint8 OptionsMenu::status
Definition at line 60 of file OptionsMenu.h.
Referenced by Collisions(), OptionsMenu(), and Update().
TextObject* OptionsMenu::tControls
Definition at line 80 of file OptionsMenu.h.
Referenced by Collisions(), Draw(), OptionsMenu(), Update(), and ~OptionsMenu().
TextObject* OptionsMenu::tExit
Definition at line 79 of file OptionsMenu.h.
Referenced by Collisions(), Draw(), OptionsMenu(), Update(), and ~OptionsMenu().
TextObject* OptionsMenu::tFullscreen
Definition at line 83 of file OptionsMenu.h.
TextObject * OptionsMenu::tMusicVol
Definition at line 79 of file OptionsMenu.h.
Referenced by Draw(), OptionsMenu(), Update(), and ~OptionsMenu().
TextObject * OptionsMenu::tScreenBpp
Definition at line 83 of file OptionsMenu.h.
TextObject * OptionsMenu::tScreenHeight
Definition at line 83 of file OptionsMenu.h.
TextObject * OptionsMenu::tScreenWidth
Definition at line 83 of file OptionsMenu.h.
TextObject * OptionsMenu::tSoundVol
Definition at line 79 of file OptionsMenu.h.
Referenced by Draw(), OptionsMenu(), Update(), and ~OptionsMenu().
double OptionsMenu::ttDrawCur
Definition at line 87 of file OptionsMenu.h.
The documentation for this class was generated from the following files:
include/OptionsMenu.h
OptionsMenu.cpp