Meatball: MiniEngine Class Reference
MiniEngine Class Reference
A base class from which the main Steam Rollers can derive from.
#include <include/MiniEngine.h>
Public Member Functions
virtual void PreUpdate (void)
Does general things.
virtual void PostUpdate (void)
virtual void Update (void)
virtual void PreDraw (void)
virtual void PostDraw (void)
virtual void Draw (void)
virtual void Do ()
virtual void Input ()
virtual void EventHandler ()
virtual void HeldKey_Handler ()
Detailed Description
A base class from which the main Steam Rollers can derive from.
MiniEngine has genericized processes for general gameplay. Like tracking events, (EventHandler()), Tracking Held Keys (HeldKey_Handler()), General Updates (Update()), and Drawing (Draw()).
Note
Draw and Update have attached pre and post Routines. These will allow you to A) Use my generalized routines for before+After your modules specific Code. B) Seperate your module specific code from the Main juice. This allows for more clarity in what code is specific and what isn't to the whole Shabang.
See Also
Steam
Definition at line 23 of file MiniEngine.h.
Member Function Documentation
void MiniEngine::Do () virtual
Reimplemented in OptionsMenu, and MainMenu.
Definition at line 17 of file MiniEngine.cpp.
References Draw(), Input(), paused, and Update().
Referenced by DoGame().
void MiniEngine::Draw (void) virtual
Reimplemented in cConsole, OptionsMenu, cLevelEditor, and ControlsMenu.
Definition at line 62 of file MiniEngine.cpp.
References cPlayer::Draw(), DrawBullets(), DrawEnemies(), DrawParticleEmitter(), PostDraw(), PreDraw(), and Renderer.
Referenced by Do().
virtual void MiniEngine::EventHandler (void) inline virtual
Reimplemented in cConsole, OptionsMenu, MainMenu, cLevelEditor, ControlsMenu, and Game.
Definition at line 35 of file MiniEngine.h.
Referenced by Input().
virtual void MiniEngine::HeldKey_Handler () inline virtual
Reimplemented in cLevelEditor, and Game.
Definition at line 36 of file MiniEngine.h.
Referenced by Input().
virtual void MiniEngine::Input () inline virtual
Definition at line 34 of file MiniEngine.h.
References EventHandler(), and HeldKey_Handler().
Referenced by Do().
void MiniEngine::PostDraw (void) virtual
Reimplemented in MainMenu.
Definition at line 56 of file MiniEngine.cpp.
References FramerateDraw(), and Renderer.
Referenced by Draw(), ControlsMenu::Draw(), cLevelEditor::Draw(), and OptionsMenu::Draw().
void MiniEngine::PostUpdate (void) virtual
Definition at line 44 of file MiniEngine.cpp.
Referenced by Update(), Game::Update(), and cLevelEditor::Update().
void MiniEngine::PreDraw (void) virtual
Definition at line 50 of file MiniEngine.cpp.
References cLevel::Draw(), and Renderer.
Referenced by Draw(), and cLevelEditor::Draw().
void MiniEngine::PreUpdate (void) virtual
Does general things.
Reimplemented in OptionsMenu.
Definition at line 29 of file MiniEngine.cpp.
References Renderer, cFramerate::SetSpeedFactor(), cCamera::Update(), and cMouseCursor::Update().
Referenced by Update(), Game::Update(), and cLevelEditor::Update().
void MiniEngine::Update (void) virtual
Reimplemented in cConsole, OptionsMenu, cLevelEditor, MainMenu, ControlsMenu, and Game.
Definition at line 38 of file MiniEngine.cpp.
References PostUpdate(), and PreUpdate().
Referenced by Do().
The documentation for this class was generated from the following files:
include/MiniEngine.h
MiniEngine.cpp