Meatball: cSoundManager Class Reference
cSoundManager Class Reference
Sound Manager
#include <Engine/include/snd_manager.h>
Classes
struct SoundItem
Public Member Functions
DLLINTERFACE cSoundManager (void)
DLLINTERFACE ~cSoundManager (void)
DLLINTERFACE Mix_Chunk * GetPointer (const std::string nIdentifier)
DLLINTERFACE Mix_Chunk * GetPointer (unsigned int nId)
DLLINTERFACE Mix_Chunk * Copy (string nIdentifier)
DLLINTERFACE string GetIdentifier (Mix_Chunk *nItem)
DLLINTERFACE unsigned int GetSize (void)
Returns the Current Size /Count of the Items.
DLLINTERFACE void Add (Mix_Chunk *nItem, const string nIdentifier="Unknown")
Adds an Sound Should always have an Identifier.
DLLINTERFACE Mix_Chunk * operator[] (unsigned int nId)
DLLINTERFACE Mix_Chunk * operator[] (const string nIdentifier)
DLLINTERFACE string operator[] (Mix_Chunk *nItem)
DLLINTERFACE void DeleteAll (void)
Private Attributes
unsigned int Count
vector< SoundItem > SoundItems
Detailed Description
Definition at line 30 of file snd_manager.h.
Constructor & Destructor Documentation
cSoundManager::cSoundManager (void)
Definition at line 4 of file snd_manager.cpp.
References Count.
cSoundManager::~cSoundManager (void)
Definition at line 9 of file snd_manager.cpp.
References DeleteAll().
Member Function Documentation
void cSoundManager::Add (Mix_Chunk * nItem, const string nIdentifier = "Unknown")
Adds an Sound Should always have an Identifier.
Definition at line 64 of file snd_manager.cpp.
References Count, cSoundManager::SoundItem::CountId, GetPointer(), cSoundManager::SoundItem::Identifier, cSoundManager::SoundItem::Item, and SoundItems.
Referenced by cWeapon_Laser_X1::cWeapon_Laser_X1(), cWeapon_Machinegun::cWeapon_Machinegun(), cWeapon_Pistol::cWeapon_Pistol(), MainMenu::MainMenu(), and OptionsMenu::OptionsMenu().
DLLINTERFACE Mix_Chunk* cSoundManager::Copy (string nIdentifier)
void cSoundManager::DeleteAll (void)
Definition at line 83 of file snd_manager.cpp.
References Count, and SoundItems.
Referenced by ~cSoundManager().
string cSoundManager::GetIdentifier (Mix_Chunk * nItem)
Definition at line 44 of file snd_manager.cpp.
References SoundItems.
Referenced by operator[]().
Mix_Chunk * cSoundManager::GetPointer (const std::string nIdentifier)
Definition at line 15 of file snd_manager.cpp.
References SoundItems.
Referenced by Add(), MainMenu::Do(), cWeapon_Pistol::Fire(), cWeapon_Machinegun::Fire(), cWeapon_Laser_X1::Fire(), operator[](), playSoundEffect(), and soundVol().
Mix_Chunk * cSoundManager::GetPointer (unsigned int nId)
Definition at line 28 of file snd_manager.cpp.
References Count, and SoundItems.
unsigned int cSoundManager::GetSize (void)
Returns the Current Size /Count of the Items.
Definition at line 58 of file snd_manager.cpp.
References SoundItems.
DLLINTERFACE Mix_Chunk* cSoundManager::operator[] (unsigned int nId) inline
Definition at line 53 of file snd_manager.h.
References GetPointer().
DLLINTERFACE Mix_Chunk* cSoundManager::operator[] (const string nIdentifier) inline
Definition at line 58 of file snd_manager.h.
References GetPointer().
DLLINTERFACE string cSoundManager::operator[] (Mix_Chunk * nItem) inline
Definition at line 63 of file snd_manager.h.
References GetIdentifier().
Member Data Documentation
unsigned int cSoundManager::Count private
Definition at line 79 of file snd_manager.h.
Referenced by Add(), cSoundManager(), DeleteAll(), and GetPointer().
vector<SoundItem> cSoundManager::SoundItems private
Definition at line 80 of file snd_manager.h.
Referenced by Add(), DeleteAll(), GetIdentifier(), GetPointer(), and GetSize().
The documentation for this class was generated from the following files:
Engine/include/snd_manager.h
Engine/snd_manager.cpp