Meatball: cImageManager Class Reference
cImageManager Class Reference
Image Manager
#include <Engine/include/img_manager.h>
Classes
struct ImageItem
Public Member Functions
DLLINTERFACE cImageManager (void)
DLLINTERFACE ~cImageManager (void)
DLLINTERFACE SDL_Surface * GetPointer (const std::string nIdentifier)
DLLINTERFACE SDL_Surface * GetPointer (unsigned int nId)
DLLINTERFACE SDL_Surface * Copy (string nIdentifier)
DLLINTERFACE string GetIdentifier (SDL_Surface *nItem)
DLLINTERFACE unsigned int GetSize (void)
Returns the Current Size /Count of the Items.
DLLINTERFACE void Add (SDL_Surface *nItem, const string nIdentifier="Unknown")
Adds an Image Should always have an Identifier.
DLLINTERFACE SDL_Surface * operator[] (unsigned int nId)
DLLINTERFACE SDL_Surface * operator[] (const string nIdentifier)
DLLINTERFACE string operator[] (SDL_Surface *nItem)
DLLINTERFACE void DeleteAll (void)
Private Attributes
unsigned int Count
vector< ImageItem > ImageItems
Detailed Description
Definition at line 30 of file img_manager.h.
Constructor & Destructor Documentation
cImageManager::cImageManager (void)
Definition at line 4 of file img_manager.cpp.
References Count.
cImageManager::~cImageManager (void)
Definition at line 9 of file img_manager.cpp.
References DeleteAll().
Member Function Documentation
void cImageManager::Add (SDL_Surface * nItem, const string nIdentifier = "Unknown")
Adds an Image Should always have an Identifier.
Definition at line 82 of file img_manager.cpp.
References Count, cImageManager::ImageItem::CountId, GetPointer(), cImageManager::ImageItem::Identifier, ImageItems, and cImageManager::ImageItem::Item.
Referenced by cConsole::cConsole(), cAF373::init(), cPlayer::init(), MainMenu::MainMenu(), cLevel::ParseLine(), PreloadBulletimages(), and SetupMouse().
SDL_Surface * cImageManager::Copy (string nIdentifier)
Definition at line 44 of file img_manager.cpp.
References CreateSurface(), and ImageItems.
void cImageManager::DeleteAll (void)
Definition at line 101 of file img_manager.cpp.
References Count, and ImageItems.
Referenced by ~cImageManager().
string cImageManager::GetIdentifier (SDL_Surface * nItem)
Definition at line 62 of file img_manager.cpp.
References ImageItems.
Referenced by operator[](), and cLevel::SaveMapObjects().
SDL_Surface * cImageManager::GetPointer (const std::string nIdentifier)
Definition at line 15 of file img_manager.cpp.
References ImageItems.
Referenced by Add(), cConsole::cConsole(), cAF373::init(), cPlayer::init(), cBullet::init(), MainMenu::MainMenu(), operator[](), cLevel::ParseLine(), and SetupMouse().
SDL_Surface * cImageManager::GetPointer (unsigned int nId)
Definition at line 28 of file img_manager.cpp.
References Count, and ImageItems.
unsigned int cImageManager::GetSize (void)
Returns the Current Size /Count of the Items.
Definition at line 76 of file img_manager.cpp.
References ImageItems.
DLLINTERFACE SDL_Surface* cImageManager::operator[] (unsigned int nId) inline
Definition at line 53 of file img_manager.h.
References GetPointer().
DLLINTERFACE SDL_Surface* cImageManager::operator[] (const string nIdentifier) inline
Definition at line 58 of file img_manager.h.
References GetPointer().
DLLINTERFACE string cImageManager::operator[] (SDL_Surface * nItem) inline
Definition at line 63 of file img_manager.h.
References GetIdentifier().
Member Data Documentation
unsigned int cImageManager::Count private
Definition at line 79 of file img_manager.h.
Referenced by Add(), cImageManager(), DeleteAll(), and GetPointer().
vector<ImageItem> cImageManager::ImageItems private
Definition at line 80 of file img_manager.h.
Referenced by Add(), Copy(), DeleteAll(), GetIdentifier(), GetPointer(), and GetSize().
The documentation for this class was generated from the following files:
Engine/include/img_manager.h
Engine/img_manager.cpp