Meatball: cEnemy Class Reference
cEnemy Class Reference
#include <include/enemy.h>
Public Member Functions
cEnemy (double nposx, double nposy)
~cEnemy (void)
virtual void init (void)
virtual void Update (void)
virtual void Draw (SDL_Renderer *renderer)
virtual void Jump (int power=5)
virtual void Die (void)
Public Member Functions inherited from cMVelSprite
cMVelSprite (SDL_Surface *new_image, double x, double y, double nvelx=0, double nvely=0)
~cMVelSprite (void)
void Update (void)
void Draw (SDL_Renderer *renderer)
SDL_Rect GetRect (SDL_bool with_camerapos=SDL_FALSE)
Use SDL_TRUE to get the RECT with camera position coordinates calculated also.
Public Member Functions inherited from cVelocitySprite
DLLINTERFACE cVelocitySprite (SDL_Renderer *renderer, SDL_Surface *new_image, double x, double y, double nvelx=0, double nvely=0)
DLLINTERFACE ~cVelocitySprite (void)
virtual DLLINTERFACE void SetVelocity (double nvelx, double nvely)
virtual DLLINTERFACE void SetVelocityX (double nvelx)
virtual DLLINTERFACE void SetVelocityY (double nvely)
DLLINTERFACE void AddVelocity (double addvelx, double addvely, double maxvelx=0, double maxvely=0)
DLLINTERFACE void Update (SDL_Renderer *renderer, SDL_bool nMove=SDL_TRUE)
Public Member Functions inherited from cBasicSprite
DLLINTERFACE cBasicSprite (SDL_Renderer *renderer, SDL_Surface *new_image, double x, double y)
DLLINTERFACE ~cBasicSprite (void)
DLLINTERFACE void SetImage (SDL_Renderer *renderer, SDL_Surface *new_image, SDL_bool OverrideSize=SDL_TRUE)
DLLINTERFACE void SetSize (double nwidth, double nheight)
DLLINTERFACE void AddSize (double naddwidth, double naddheight)
DLLINTERFACE void SetPos (double x, double y)
DLLINTERFACE void SetAlpha (Uint8 Alpha)
DLLINTERFACE void SetColorKey (Uint32 Colorkey)
DLLINTERFACE Uint32 GetAlpha (void)
DLLINTERFACE Uint32 GetColorkey (void)
DLLINTERFACE double GetSizeWidth (void)
DLLINTERFACE double GetSizeHeight (void)
DLLINTERFACE void Move (double move_x, double move_y)
DLLINTERFACE void Draw (SDL_Renderer *renderer)
DLLINTERFACE void UpdateTexture (SDL_Renderer *renderer)
DLLINTERFACE void DestroyTexture (void)
virtual DLLINTERFACE void Update (SDL_Renderer *renderer)
Public Attributes
int direction
0 = facing left 1 = facing right 2 = facing up 3 = facing down
unsigned int Enemy_type
The Enemy Type.
unsigned int Enemy_state
The Enemy State.
unsigned int health
The Health.
double max_speed
Maximum Speed.
double Acceleration
The Acceleration.
Public Attributes inherited from cMVelSprite
int type
The Type 0 = No Type
1 = Player
2 = Sprite Massive
3 = Sprite Passive
4 = Sprite Halfmassive
5 = Sprite Bullet
6 = ?
7 = ?
double Startposy
Start Position.
double Startposx
Collisiondata * Collision
Public Attributes inherited from cVelocitySprite
double velx
double vely
Public Attributes inherited from cBasicSprite
SDL_Texture * texture
SDL_Surface * image
The final stretched/zoomed image to draw if visible == 0 the image won't be drawn.
Uint8 alpha
Alpha 0 (completely not visible) - 255 (completely visible) Read Only.
double posx
double posy
double width
double height
Size for stretching/zooming.
SDL_bool visible
SDL_bool spawned
unsigned int ID
SDL_Surface * startimage
The first image which was set Read only.
SDL_Surface * srcimage
The image which is currently set Read only.
SDL_Rect rect
The rects for all images Read only.
SDL_Rect srcrect
SDL_Rect startrect
SDL_bool drawimg
If this is 1 the image needs to be redrawn to maintain the width and height Read only.
unsigned int Spritetype
What sprite type is this 1 = Basic, 2 = Velocity, 3 = Angle, 4 = Acceleration.
Detailed Description
Definition at line 23 of file enemy.h.
Constructor & Destructor Documentation
cEnemy::cEnemy (double nposx, double nposy)
Definition at line 11 of file enemy.cpp.
References ENEMY_AI_STATE_UNKNOWN, Enemy_state, Enemy_type, ENEMY_UNDEFINED, cBasicSprite::SetPos(), SPRITE_TYPE_ENEMY, and cMVelSprite::type.
cEnemy::~cEnemy (void)
Definition at line 22 of file enemy.cpp.
Member Function Documentation
void cEnemy::Die (void) virtual
Reimplemented in cAF373.
Definition at line 47 of file enemy.cpp.
void cEnemy::Draw (SDL_Renderer * renderer) virtual
Reimplemented in cAF373.
Definition at line 37 of file enemy.cpp.
void cEnemy::init (void) virtual
Reimplemented in cAF373.
Definition at line 27 of file enemy.cpp.
Referenced by AddEnemy().
void cEnemy::Jump (int power = 5) virtual
Parameters
power = 5
Definition at line 42 of file enemy.cpp.
void cEnemy::Update (void) virtual
Reimplemented in cAF373.
Definition at line 32 of file enemy.cpp.
References cMVelSprite::Update().
Referenced by cAF373::Update().
Member Data Documentation
double cEnemy::Acceleration
The Acceleration.
Definition at line 59 of file enemy.h.
int cEnemy::direction
0 = facing left 1 = facing right 2 = facing up 3 = facing down
Definition at line 44 of file enemy.h.
Referenced by cAF373::init(), and cAF373::Update().
unsigned int cEnemy::Enemy_state
The Enemy State.
Definition at line 50 of file enemy.h.
Referenced by cEnemy().
unsigned int cEnemy::Enemy_type
The Enemy Type.
Definition at line 47 of file enemy.h.
Referenced by cEnemy(), cAF373::init(), and cLevelEditor::PasteObject().
unsigned int cEnemy::health
The Health.
Definition at line 53 of file enemy.h.
double cEnemy::max_speed
Maximum Speed.
Definition at line 56 of file enemy.h.
The documentation for this class was generated from the following files:
include/enemy.h
enemy.cpp