Meatball: include/effects.h File Reference
effects.h File Reference
#include "Globals.h"
#include "sprite.h"
Classes
class cMParticle
The Particle class.
class cMParticleEmitter
The Particle Emitter class.
Functions
void AddParticleEmitter (double x, double y, double nSpeed, Uint8 nred, Uint8 ngreen, Uint8 nblue, double nfadeoutspeed, unsigned int power, double nRandomness, double fixedDirection=-1)
Adds an Particle Emitter Power : Amount of Particles Randomness : Amount of Random Movement
if Fixed Direction is set all spawned Particles will have those direction when spawned.
void UpdateParticleEmitter (void)
Updates all Particle Emitter.
void DrawParticleEmitter (SDL_Renderer *renderer)
Draws all Particle Emitter.
void DeleteAllParticleEmitter (void)
Delete's every Particle Emitter.
Variables
cFramerate * pFramerate
cCamera * pCamera
cMParticleEmitter ** ParticleEmitter
The dynamic Particle Emittter Array.
unsigned int ParticleEmitterCount
Function Documentation
void AddParticleEmitter (double x, double y, double nSpeed, Uint8 nred, Uint8 ngreen, Uint8 nblue, double nfadeoutspeed, unsigned int power, double nRandomness, double fixedDirection = -1)
Adds an Particle Emitter Power : Amount of Particles Randomness : Amount of Random Movement
if Fixed Direction is set all spawned Particles will have those direction when spawned.
Parameters
fixedDirection = -1
Definition at line 307 of file effects.cpp.
References cMParticleEmitter::alpha, cMParticleEmitter::angle, cMParticleEmitter::blue, cMParticleEmitter::fadeoutspeed, cMParticleEmitter::green, cMParticleEmitter::InitParticles(), ParticleEmitterCount, cMParticleEmitter::posx, cMParticleEmitter::posy, cMParticleEmitter::Randomness, cMParticleEmitter::red, cMParticleEmitter::speed, cMParticleEmitter::visible, and cBasicSprite::visible.
Referenced by cBullet::Explode(), cAF373::Fire(), cPlayer::Fire(), and Game::Keydown_Events().
void DeleteAllParticleEmitter (void)
Delete's every Particle Emitter.
Definition at line 384 of file effects.cpp.
References ParticleEmitter, and ParticleEmitterCount.
Referenced by cLevel::Load(), and QuitGame().
void DrawParticleEmitter (SDL_Renderer * renderer)
Draws all Particle Emitter.
Definition at line 367 of file effects.cpp.
References cMParticleEmitter::Draw(), and ParticleEmitterCount.
Referenced by MiniEngine::Draw(), and cConsole::Draw().
void UpdateParticleEmitter (void)
Updates all Particle Emitter.
Definition at line 354 of file effects.cpp.
References ParticleEmitterCount, and cMParticleEmitter::Update().
Referenced by Game::Update().
Variable Documentation
cMParticleEmitter** ParticleEmitter
The dynamic Particle Emittter Array.
Definition at line 6 of file effects.cpp.
Referenced by DeleteAllParticleEmitter().
unsigned int ParticleEmitterCount
Definition at line 7 of file effects.cpp.
Referenced by AddParticleEmitter(), DeleteAllParticleEmitter(), DrawParticleEmitter(), and UpdateParticleEmitter().
cFramerate* pFramerate
Definition at line 23 of file Globals.cpp.