Meatball: include/enemy.h File Reference
enemy.h File Reference
#include "Globals.h"
#include "sprite.h"
#include "ObjectManager.h"
Classes
class cEnemy
Macros
#define ENEMY_UNDEFINED 0
Enemy Types.
#define ENEMY_AF373 1
#define ENEMY_AI_STATE_UNKNOWN 0
Enemy States.
#define ENEMY_AI_STATE_WAITING 1
#define ENEMY_AI_STATE_SEARCHING 2
#define ENEMY_AI_STATE_FOLLOWING 3
#define ENEMY_AI_STATE_TARGETTING 4
#define ENEMY_AI_STATE_FIRING 5
Functions
void AddEnemy (double nposx, double nposy, unsigned int etype)
Adds an Enemy with the given type.
void UpdateEnemies (void)
Updates all Enemies.
int GetCollidingEnemyNum (SDL_Rect *Crect)
Gets the first Collision if the rect overlaps.
cEnemy * GetCollidingEnemy (SDL_Rect *Crect)
void DrawEnemies (SDL_Renderer *renderer)
Draws all Enemies.
void DeletEnemy (unsigned int number)
Seletes an given Enemy.
void DeleteAllEnemies (void)
Deletes every Enemy and frees the array.
Variables
ObjectManager< cEnemy > Enemies
Macro Definition Documentation
#define ENEMY_AF373 1
Definition at line 13 of file enemy.h.
Referenced by AddEnemy(), cAF373::init(), Game::Keydown_Events(), cLevel::ParseLine(), and cLevel::SaveMapEnemies().
#define ENEMY_AI_STATE_FIRING 5
Definition at line 21 of file enemy.h.
#define ENEMY_AI_STATE_FOLLOWING 3
Definition at line 19 of file enemy.h.
#define ENEMY_AI_STATE_SEARCHING 2
Definition at line 18 of file enemy.h.
#define ENEMY_AI_STATE_TARGETTING 4
Definition at line 20 of file enemy.h.
#define ENEMY_AI_STATE_UNKNOWN 0
Enemy States.
Definition at line 16 of file enemy.h.
Referenced by cEnemy::cEnemy().
#define ENEMY_AI_STATE_WAITING 1
Definition at line 17 of file enemy.h.
#define ENEMY_UNDEFINED 0
Enemy Types.
Definition at line 12 of file enemy.h.
Referenced by cEnemy::cEnemy().
Function Documentation
void AddEnemy (double nposx, double nposy, unsigned int etype)
Adds an Enemy with the given type.
Definition at line 52 of file enemy.cpp.
References DEBUGLOG, Enemies, ENEMY_AF373, and cEnemy::init().
Referenced by Game::Keydown_Events(), cLevel::ParseLine(), and cLevelEditor::PasteObject().
void DeleteAllEnemies (void)
Deletes every Enemy and frees the array.
Definition at line 167 of file enemy.cpp.
References Enemies.
Referenced by cLevel::Load(), and QuitGame().
void DeletEnemy (unsigned int number)
Seletes an given Enemy.
Definition at line 157 of file enemy.cpp.
References Enemies.
Referenced by cLevelEditor::DeleteObject().
void DrawEnemies (SDL_Renderer * renderer)
Draws all Enemies.
Definition at line 144 of file enemy.cpp.
References Enemies.
Referenced by MiniEngine::Draw(), cLevelEditor::Draw(), and cConsole::Draw().
cEnemy* GetCollidingEnemy (SDL_Rect * Crect)
Definition at line 123 of file enemy.cpp.
References Enemies, and RectIntersect().
int GetCollidingEnemyNum (SDL_Rect * Crect)
Gets the first Collision if the rect overlaps.
Definition at line 102 of file enemy.cpp.
References Enemies, and RectIntersect().
Referenced by cLevelEditor::DeleteObject(), and cLevelEditor::GetCollidingObject().
void UpdateEnemies (void)
Updates all Enemies.
Definition at line 85 of file enemy.cpp.
References CollideMove(), Enemies, pFramerate, and cFramerate::speedfactor.
Referenced by Game::Update().
Variable Documentation
ObjectManager<cEnemy> Enemies
Referenced by AddEnemy(), DeleteAllEnemies(), DeletEnemy(), DrawEnemies(), GetCollidingEnemy(), GetCollidingEnemyNum(), cLevelEditor::GetCollidingObject(), PositionCheck(), cLevel::SaveMapEnemies(), and UpdateEnemies().