Meatball: Image
Image
Engine
Files
file image.h
Image.
Functions
DLLINTERFACE SDL_Surface * LoadImage (const char *szFilename, Uint32 Colorkey=0, Uint8 Alpha=255)
DLLINTERFACE SDL_Surface * CreateSurface (unsigned int width, unsigned int height, Uint8 bpp=32, Uint32 flags=0)
V 1.1.1.
Detailed Description
Function Documentation
DLLINTERFACE SDL_Surface* CreateSurface (unsigned int width, unsigned int height, Uint8 bpp = 32, Uint32 flags = 0)
V 1.1.1.
CreateSurface - Creates an empty image and sets it to the best format
width,height : The Dimensions
bpp : the best way is to set here screen->format->bitsperpixel
flags : for setting specified flags
Note : You should call it after the main screen was initialized
Definition at line 46 of file image.cpp.
Referenced by cImageManager::Copy(), and cBasicSprite::Update().
DLLINTERFACE SDL_Surface* LoadImage (const char * szFilename, Uint32 Colorkey = 0, Uint8 Alpha = 255)
LoadImage - Loads an image and sets it to the best format !
Colorkey : Every Pixel that matches identical with the specified Color will be transparent .
Alpha : The transparency of the whole image .
Note : You should call it after the main screen was initialized
Definition at line 5 of file image.cpp.
Referenced by cConsole::cConsole(), cAF373::init(), cPlayer::init(), MainMenu::MainMenu(), cLevel::ParseLine(), PreloadBulletimages(), and SetupMouse().