Meatball: Gfx
Gfx
Engine
Functions
void FillRectAlpha (SDL_Renderer *renderer, int x, int y, int w, int h, Uint8 r, Uint8 g, Uint8 b, Uint8 a)
void FillRectAlpha (SDL_Renderer *renderer, int x, int y, int w, int h, Uint32 rgba)
void FillRect (SDL_Renderer *renderer, int x, int y, int w, int h, Uint8 r, Uint8 g, Uint8 b)
void FillRectAlpha (SDL_Renderer *renderer, SDL_Rect *rect, Uint32 rgba)
void FillRectAlpha (SDL_Renderer *renderer, SDL_Rect *rect, Uint8 r, Uint8 g, Uint8 b, Uint8 a)
void DrawPixel (SDL_Renderer *renderer, int x, int y, Uint8 red, Uint8 green, Uint8 blue, Uint8 alpha)
Detailed Description
Function Documentation
void DrawPixel (SDL_Renderer * renderer, int x, int y, Uint8 red, Uint8 green, Uint8 blue, Uint8 alpha)
Definition at line 69 of file gfx.cpp.
Referenced by cMParticle::Draw().
void FillRect (SDL_Renderer * renderer, int x, int y, int w, int h, Uint8 r, Uint8 g, Uint8 b)
Definition at line 21 of file gfx.cpp.
References FillRectAlpha().
Referenced by cLevelEditor::OutlineObject().
void FillRectAlpha (SDL_Renderer * renderer, int x, int y, int w, int h, Uint8 r, Uint8 g, Uint8 b, Uint8 a)
Definition at line 10 of file gfx.cpp.
Referenced by Slider::Draw(), cLevelEditor::Draw(), FillRect(), FillRectAlpha(), and cLevelEditor::OutlineObject().
void FillRectAlpha (SDL_Renderer * renderer, int x, int y, int w, int h, Uint32 rgba)
Definition at line 26 of file gfx.cpp.
References FillRectAlpha().
void FillRectAlpha (SDL_Renderer * renderer, SDL_Rect * rect, Uint32 rgba)
Definition at line 35 of file gfx.cpp.
References FillRectAlpha().
void FillRectAlpha (SDL_Renderer * renderer, SDL_Rect * rect, Uint8 r, Uint8 g, Uint8 b, Uint8 a)
Definition at line 44 of file gfx.cpp.
References FillRectAlpha().