Meatball: Video
Video
Engine
Files
file video.h
Video Initialization and other.
Classes
struct Screenscale
Functions
DLLINTERFACE int InitSDL (Uint32 flags=SDL_INIT_EVERYTHING)
DLLINTERFACE int InitWindow (SDL_Window *win, SDL_Renderer *Screen, const char *title, int width, int height, Uint32 wflags, Uint32 rflags, SDL_bool fullscreen=SDL_FALSE)
DLLINTERFACE SDL_Window * GetWindow (const char *title, int width, int height, Uint32 wflags)
DLLINTERFACE SDL_Renderer * GetRenderer (SDL_Window *win, Uint32 rflags)
DLLINTERFACE void SetWindowCaption (SDL_Window *win, const char *Caption)
DLLINTERFACE void SetWindowIcon (SDL_Window *win, SDL_Surface *Icon)
DLLINTERFACE void SetScreenScale (int sx, int sy)
DLLINTERFACE void QuitSDL (void)
Quits SDL.
Detailed Description
Function Documentation
DLLINTERFACE SDL_Renderer* GetRenderer (SDL_Window * win, Uint32 rflags)
Definition at line 100 of file video.cpp.
Referenced by CreateWindow().
DLLINTERFACE SDL_Window* GetWindow (const char * title, int width, int height, Uint32 wflags)
Definition at line 95 of file video.cpp.
Referenced by CreateWindow().
DLLINTERFACE int InitSDL (Uint32 flags = SDL_INIT_EVERYTHING)
Definition at line 6 of file video.cpp.
References Screenscale::x, and Screenscale::y.
Referenced by initEngine().
DLLINTERFACE int InitWindow (SDL_Window * win, SDL_Renderer * Screen, const char * title, int width, int height, Uint32 wflags, Uint32 rflags, SDL_bool fullscreen = SDL_FALSE)
Definition at line 69 of file video.cpp.
DLLINTERFACE void QuitSDL (void)
Quits SDL.
Definition at line 120 of file video.cpp.
Referenced by QuitGame().
DLLINTERFACE void SetScreenScale (int sx, int sy)
Definition at line 20 of file video.cpp.
References Screenscale::x, and Screenscale::y.
Referenced by SetScreenScaleXY().
DLLINTERFACE void SetWindowCaption (SDL_Window * win, const char * Caption)
Definition at line 105 of file video.cpp.
DLLINTERFACE void SetWindowIcon (SDL_Window * win, SDL_Surface * Icon)
Definition at line 110 of file video.cpp.