Meatball: Misc
Misc
Engine
Functions
DLLINTERFACE float Random (float min, float max)
Random float between min and max.
DLLINTERFACE int Random (int min, int max)
Random integer between min and max.
DLLINTERFACE int Random (int max)
Random integer between 0 and max.
DLLINTERFACE float Random (float max)
Random float between 0 and max.
DLLINTERFACE double Random (double max)
Random double between 0 and max.
DLLINTERFACE double Random (double min, double max)
Random double between min and max.
DLLINTERFACE SDL_Rect SetRect (int x, int y, unsigned int w, unsigned int h)
Returns an SDL_rect.
DLLINTERFACE SDL_Color SetColor (Uint8 Red, Uint8 Green, Uint8 Blue)
return an SDL_Color
DLLINTERFACE SDL_bool RectIntersect (const SDL_Rect *r1, const SDL_Rect *r2)
returns 1 if 1 or more points intersect
DLLINTERFACE SDL_bool FullRectIntersect (const SDL_Rect *r1, const SDL_Rect *r2)
returns 1 if the complete rect1 intersects with rect2
DLLINTERFACE std::string Get_Curr_Date ()
Detailed Description
Function Documentation
DLLINTERFACE SDL_bool FullRectIntersect (const SDL_Rect * r1, const SDL_Rect * r2)
returns 1 if the complete rect1 intersects with rect2
Definition at line 80 of file misc.cpp.
DLLINTERFACE std::string Get_Curr_Date ()
Definition at line 102 of file misc.cpp.
Referenced by cLevel::PrintSaveHeader().
DLLINTERFACE float Random (float min, float max)
Random float between min and max.
Definition at line 6 of file misc.cpp.
Referenced by cAF373::AI_Idle(), cBullet::Explode(), cAF373::Fire(), cMParticleEmitter::InitParticles(), Playlist::musicover(), Random(), and cMParticle::Update().
DLLINTERFACE int Random (int min, int max)
Random integer between min and max.
Definition at line 11 of file misc.cpp.
DLLINTERFACE int Random (int max)
Random integer between 0 and max.
Definition at line 16 of file misc.cpp.
References Random().
DLLINTERFACE float Random (float max)
Random float between 0 and max.
Definition at line 21 of file misc.cpp.
References Random().
DLLINTERFACE double Random (double max)
Random double between 0 and max.
Definition at line 26 of file misc.cpp.
References Random().
DLLINTERFACE double Random (double min, double max)
Random double between min and max.
Definition at line 31 of file misc.cpp.
References Random().
DLLINTERFACE SDL_bool RectIntersect (const SDL_Rect * r1, const SDL_Rect * r2)
returns 1 if 1 or more points intersect
Definition at line 58 of file misc.cpp.
Referenced by cMouseCursor::CollisonCheck(), cMultiSelect::GetAllCollidingObjects(), cLevelData::GetAllCollidingSpriteNum(), GetCollidingEnemy(), GetCollidingEnemyNum(), cLevelEditor::GetCollidingObject(), cLevelData::GetCollidingSprite(), cLevelData::GetCollidingSpriteNum(), and PositionCheck().
DLLINTERFACE SDL_Color SetColor (Uint8 Red, Uint8 Green, Uint8 Blue)
return an SDL_Color
Definition at line 48 of file misc.cpp.
Referenced by cFont::cFont(), ControlsMenu::ControlsMenu(), TextObject::initDefaultColors(), MainMenu::MainMenu(), and OptionsMenu::OptionsMenu().
DLLINTERFACE SDL_Rect SetRect (int x, int y, unsigned int w, unsigned int h)
Returns an SDL_rect.
Definition at line 36 of file misc.cpp.
Referenced by cBasicSprite::cBasicSprite(), cMouseCursor::CollisonCheck(), cLevelEditor::DeleteObject(), FramerateDraw(), cLevelEditor::GetCollidingObject(), cMVelSprite::GetRect(), cMAngleSprite::GetRect(), PositionCheck(), cConsole::SetRects(), Slider::Slider(), cLevelEditor::Update(), and TextObject::UpdateRect().