Meatball: Console
Console
In-game Console can track/manipulate variables and game phenomena.
Modules
Input
Console Commands
These functions are for the console commands.
Classes
class cCMD
This structure is for each Command to the Console.
class cConsole
For Live In-game editing to the Game World and Variables.
Macros
#define NUM_LINES 11
#define HISTORY_LINES 11
#define topHistoryLine_Y 23.0
#define CONSOLE_HISTORY_VERTICAL_SEPERATION_PIXELS 15.0
Functions
void moveConsoleHistoryLinesUp (int nlines=1)
Move all output up one line.
void wait_for_input ()
Queries the user to hit enter key.. kinda like a cheap [less] cmd.
void console_print (const char *str)
Self Explanatory.
void Push (cCMD *&head, string command, SDL_bool(*handler)(string &), string helpstr, string syntax)
Linked List push function.
Detailed Description
In-game Console can track/manipulate variables and game phenomena.
Macro Definition Documentation
#define CONSOLE_HISTORY_VERTICAL_SEPERATION_PIXELS 15.0
Definition at line 45 of file console.h.
Referenced by cConsole::SetRects().
#define HISTORY_LINES 11
Definition at line 42 of file console.h.
Referenced by cConsole::cConsole(), and cConsole::ClearHistory_SurfacesAndTextures().
#define NUM_LINES 11
Definition at line 40 of file console.h.
Referenced by cConsole::EventHandler(), help(), ls(), and moveConsoleHistoryLinesUp().
#define topHistoryLine_Y 23.0
Definition at line 43 of file console.h.
Referenced by cConsole::SetRects().
Function Documentation
void console_print (const char * str)
Self Explanatory.
Definition at line 843 of file console.cpp.
References moveConsoleHistoryLinesUp(), and cConsole::strcpy.
Referenced by allSoundsVol(), cd(), cConsole::EventHandler(), help(), cConsole::helpCMD(), ls(), musicVol(), play(), SetMx(), SetMxy(), SetMy(), SetScreenScaleX(), SetScreenScaleXY(), SetScreenScaleY(), and soundVol().
void moveConsoleHistoryLinesUp (int nlines = 1)
Move all output up one line.
Definition at line 795 of file console.cpp.
References NUM_LINES, and cConsole::strcpy.
Referenced by console_print().
void Push (cCMD *& head, string command, SDL_bool(*)(string &) handler, string helpstr, string syntax)
Linked List push function.
This pushes a new cCMD onto the linked list:
See Also
cConsole::CMDList
Definition at line 20 of file console.cpp.
References ObjectManager< T >::add(), cCMD::command, cCMD::handler, cCMD::helpstr, cCMD::next, and cCMD::syntax.
Referenced by cConsole::cConsole().
void wait_for_input ()
Queries the user to hit enter key.. kinda like a cheap [less] cmd.
Definition at line 818 of file console.cpp.
References cConsole::Draw(), Renderer, and cConsole::Update().
Referenced by help(), and ls().