Meatball: Guns
Guns
Weapons and Bullets information.
Modules
BULLET_TYPES
WEAPON_TYPES
Classes
class cBullet
class cWeapon
The Basic Weapon class.
class cWeapon_Pistol
class cWeapon_Machinegun
class cWeapon_Laser_X1
Functions
void PreloadBulletimages (void)
Preloads all Bullet images get the pointer with the image manager and the image path.
void AddBullet (double nposx, double nposy, int ndirection, unsigned int nBullet_type, unsigned int nOrigin, double nAddVel=0.0)
Adds an Bullet which gets controlled by the game just use Bullet type.
void UpdateBullets (void)
Updates all Bullets.
void DrawBullets (SDL_Renderer *renderer)
Draws all Bullets.
void DeleteAllBullets (void)
Deletes all Bullets (Cleans the Array)
Variables
SDL_Renderer * Renderer
cCamera * pCamera
cImageManager * IMan
int window_height
int window_width
ObjectManager< cBullet > Bullets
holds all of the bullets getting put to the screen.
cSoundManager * SMan
cFramerate * pFramerate
cAudio * pAudio
SDL_Renderer * Renderer
Detailed Description
Weapons and Bullets information.
Function Documentation
void AddBullet (double nposx, double nposy, int ndirection, unsigned int nBullet_type, unsigned int nOrigin, double nAddVel = 0.0)
Adds an Bullet which gets controlled by the game just use Bullet type.
Parameters
nAddVel = 0.0
Definition at line 262 of file bullet.cpp.
References Bullets, and cBullet::init().
Referenced by cWeapon_Pistol::Fire(), cWeapon_Machinegun::Fire(), and cWeapon_Laser_X1::Fire().
void DeleteAllBullets (void)
Deletes all Bullets (Cleans the Array)
Definition at line 304 of file bullet.cpp.
References Bullets.
Referenced by cLevel::Load(), and QuitGame().
void DrawBullets (SDL_Renderer * renderer)
Draws all Bullets.
Definition at line 296 of file bullet.cpp.
References Bullets.
Referenced by MiniEngine::Draw(), and cConsole::Draw().
void PreloadBulletimages (void)
Preloads all Bullet images get the pointer with the image manager and the image path.
Definition at line 252 of file bullet.cpp.
References cImageManager::Add(), colorkey, IMan, LoadImage(), and PIXMAPS_DIR.
Referenced by Game::Init().
void UpdateBullets (void)
Updates all Bullets.
Definition at line 283 of file bullet.cpp.
References Bullets, CollideMove(), cMVelSprite::Collision, pFramerate, cFramerate::speedfactor, cMVelSprite::type, cBullet::Update(), cVelocitySprite::velx, and cVelocitySprite::vely.
Referenced by Game::Update().
Variable Documentation
ObjectManager<cBullet> Bullets
holds all of the bullets getting put to the screen.
The array is dynamically allocated as bullets are spawned, and it maintains its largest allocated size.
Referenced by AddBullet(), DeleteAllBullets(), DrawBullets(), and UpdateBullets().
cImageManager* IMan
Definition at line 24 of file Globals.cpp.
cAudio* pAudio
Definition at line 28 of file Globals.cpp.
cCamera * pCamera
Definition at line 15 of file leveleditor.cpp.
Referenced by cAF373::Draw(), cMParticle::Draw(), cPlayer::Draw(), cBullet::Draw(), QuitGame(), cAF373::Update(), cPlayer::Update(), and cBullet::Windows_BoundsChecking().
cFramerate* pFramerate
Definition at line 23 of file Globals.cpp.
SDL_Renderer* Renderer
Definition at line 38 of file Globals.cpp.
SDL_Renderer* Renderer
Definition at line 38 of file Globals.cpp.
cSoundManager* SMan
Definition at line 25 of file Globals.cpp.
Referenced by cWeapon_Laser_X1::cWeapon_Laser_X1(), cWeapon_Machinegun::cWeapon_Machinegun(), cWeapon_Pistol::cWeapon_Pistol(), MainMenu::Do(), cWeapon_Pistol::Fire(), cWeapon_Machinegun::Fire(), cWeapon_Laser_X1::Fire(), initEngine(), MainMenu::MainMenu(), OptionsMenu::OptionsMenu(), playSoundEffect(), QuitGame(), and soundVol().
int window_height
Definition at line 37 of file Globals.cpp.
int window_width
Definition at line 36 of file Globals.cpp.