Meatball: Input
Input
Level Editor
Functions
void cLevelEditor::EventHandler ()
Detailed Description
Function Documentation
void cLevelEditor::EventHandler (void) virtual
Reimplemented from MiniEngine.
Definition at line 370 of file leveleditor.cpp.
References COPY_KEY, cLevelEditor::CopyObject, cLevelEditor::DeleteObject(), done, event, FASTCOPY_KEY, cLevelEditor::GetCollidingObject(), ObjectManager< T >::hasa(), cBasicSprite::height, cMultiSelect::InitTiles(), keys, mode, MODE_CONSOLE, MODE_GAME, cLevelEditor::Mouse_command, MOUSE_COMMAND_FASTCOPY, MOUSE_COMMAND_MOVING_MULTISELECT_TILES, MOUSE_COMMAND_NOTHING, MOUSE_COMMAND_SELECT_MULTISELECT_TILES, cCamera::Move(), cMultiSelect::multiple_objects_selected, cLevelEditor::MultiSelect, oldmode, cMultiSelect::OM, PASTE_KEY, cLevelEditor::PasteObject(), pMouse, cBasicSprite::posx, cBasicSprite::posy, cMultiSelect::PrepareToMove(), cMultiSelect::Release(), cLevelEditor::Release_Command(), ObjectManager< T >::RemoveAllObjects(), cLevel::Save(), SAVE_KEY, cLevelEditor::SetCopyObject(), cLevelEditor::SetFastCopyObject(), cLevelEditor::SetMoveObject(), cMultiSelect::SetObject(), cMultiSelect::SetObjects(), cCamera::SetPos(), UniversalEventHandler(), cBasicSprite::width, window_width, cCamera::x, and cCamera::y.