Meatball: Console Commands
Console Commands
Console
These functions are for the console commands.
Functions
SDL_bool clearcon (string &str)
Clears the console.
SDL_bool loadmap (string &str)
Load a new Level from LEVEL_DIR.
SDL_bool SetMx (string &str)
Set Meatball's X Coordinate.
SDL_bool SetMy (string &str)
Set Meatball's Y Coordinate.
SDL_bool SetMxy (string &str)
Set Meatball (X,Y) coordinate.
SDL_bool play (string &str)
Play a song from the MUSIC_DIR.
SDL_bool QuitAll (string &str)
Quit the Game.
SDL_bool ShowFPS (string &str)
Toggle FPS framerate to be displayed.
SDL_bool help (string &str)
bring up help on all commands or specific command
SDL_bool soundVol (string &str)
change the volume of a sound (0-128)
SDL_bool allSoundsVol (string &str)
Change the volume of All sounds (0-128)
SDL_bool musicVol (string &str)
Change the music volume (0-128)
SDL_bool cd (string &str)
change the current directory
SDL_bool ls (string &str)
list the directory
SDL_bool SetScreenScaleXY (string &str)
SDL_bool SetScreenScaleX (string &str)
SDL_bool SetScreenScaleY (string &str)
Detailed Description
These functions are for the console commands.
Note
The function names may differ from the actual command names you type in the console
Use the following code snippet to decipher the function names from their command names\
Format: cConsole::CMDList, "Command Name", function name, "help string", "syntax"
    Push(CMDList,   "clear",    clearcon,               "Clears all strings in console",                        "clear"                                             );
        CmdAddAlias(CMDList, "cls");
    Push(CMDList,   "loadmap",  loadmap,                "Loads a map file into the game",                       "loadmap [mapfile]"                                 );
    Push(CMDList,   "mx",       SetMx,                  "Sets Meatball's X coordinate",                         "Mx [x]"                                            );
    Push(CMDList,   "my",       SetMy,                  "Sets Meatball's Y coordinate",                         "my [y]"                                            );
    Push(CMDList,   "mxy",      SetMxy,                 "Sets Meatball's X & Y coordinate",                     "Mxy [x y]"                                         );
    Push(CMDList,   "playmus",      play,                   "Plays a music file",                                   "play [musicfile]"                                  );
    Push(CMDList,   "quit",     QuitAll,                "Quits the game",                                       "quit"                                              );
        CmdAddAlias(CMDList, "q");
    Push(CMDList,   "fps",      ShowFPS,                "Displays or hides FPS",                                "fps"                                               );
    Push(CMDList,   "help",     help,                   "Displays all commands or help for a specific command", "help [cmd]"                                        );
        CmdAddAlias(CMDList, "h");
    Push(CMDList,   "svol",     soundVol,               "Set Sounds Volumes",                                   "svol [string_id] [0-128]"                          );
    Push(CMDList,   "mvol",     musicVol,               "Set Music Volumes",                                    "mvol [0-128]"                                      );
    Push(CMDList,   "allsvol",  allSoundsVol,           "Set ALL Sounds Channel Volumes",                       "allsvol [0-128]"                                   );
    Push(CMDList,   "cd",       cd,                     "change directory",                                     "cd [dir]"                                          );
    Push(CMDList,   "ls",       ls,                     "List Directoy Contents",                               "ls [dir]"                                          );
        CmdAddAlias(CMDList, "l");
    Push(CMDList,   "sxy",      SetScreenScaleXY,       "Set X/Y Screen Scale Factor",                          "sxy [x] [y]"                                       );
    Push(CMDList,   "sx",       SetScreenScaleX,        "Set X Screen Scale Factor",                            "sx [x]"                                            );
    Push(CMDList,   "sy",       SetScreenScaleY,        "Set Y Screen Scale Factor",                            "sy [y]"                                            );
Function Documentation
SDL_bool allSoundsVol (string & str)
Change the volume of All sounds (0-128)
Definition at line 603 of file console.cpp.
References console_print(), pAudio, and cAudio::SetAllSoundsVolume().
Referenced by cConsole::cConsole().
SDL_bool cd (string & str)
change the current directory
Definition at line 850 of file console.cpp.
References console_print(), and cConsole::full_path.
Referenced by cConsole::cConsole().
SDL_bool clearcon (string & str)
Clears the console.
Definition at line 507 of file console.cpp.
References cConsole::consoleInput_str, cConsole::histcounter, and cConsole::strcpy.
Referenced by cConsole::cConsole().
SDL_bool help (string & str)
bring up help on all commands or specific command
there are now more than 10 commands... too much for a screen full... let's print 10 commands at a time then
Definition at line 741 of file console.cpp.
References cConsole::CMDList, cCMD::command, console_print(), cConsole::consoleInput_str, cConsole::helpCMD(), cCMD::next, NUM_LINES, ObjectManager< T >::objcount, ObjectManager< T >::objects, and wait_for_input().
Referenced by cConsole::cConsole().
SDL_bool loadmap (string & str)
Load a new Level from LEVEL_DIR.
Definition at line 520 of file console.cpp.
References cLevel::Load().
Referenced by cConsole::cConsole().
SDL_bool ls (string & str)
list the directory
Definition at line 862 of file console.cpp.
References console_print(), cConsole::consoleInput_str, cConsole::full_path, NUM_LINES, and wait_for_input().
Referenced by cConsole::cConsole().
SDL_bool musicVol (string & str)
Change the music volume (0-128)
Definition at line 681 of file console.cpp.
References console_print(), cAudio::Music_Volume, pAudio, and cAudio::SetMusicVolume().
Referenced by cConsole::cConsole().
SDL_bool play (string & str)
Play a song from the MUSIC_DIR.
Definition at line 708 of file console.cpp.
References console_print(), FileValid(), MUSIC_DIR, cLevelData::Musicfile, pAudio, cAudio::PlayMusik(), and cLevel::pLevelData_Layer1.
Referenced by cConsole::cConsole().
SDL_bool QuitAll (string & str)
Quit the Game.
Definition at line 811 of file console.cpp.
References done, mode, and MODE_QUIT.
Referenced by cConsole::cConsole().
SDL_bool SetMx (string & str)
Set Meatball's X Coordinate.
Definition at line 527 of file console.cpp.
References console_print(), and cBasicSprite::posx.
Referenced by cConsole::cConsole().
SDL_bool SetMxy (string & str)
Set Meatball (X,Y) coordinate.
Definition at line 558 of file console.cpp.
References console_print(), cBasicSprite::posx, cBasicSprite::posy, and cBasicSprite::SetPos().
Referenced by cConsole::cConsole().
SDL_bool SetMy (string & str)
Set Meatball's Y Coordinate.
Definition at line 542 of file console.cpp.
References console_print(), and cBasicSprite::posy.
Referenced by cConsole::cConsole().
SDL_bool SetScreenScaleX (string & str)
Definition at line 959 of file console.cpp.
References console_print(), ScreenScale, and Screenscale::x.
Referenced by cConsole::cConsole().
SDL_bool SetScreenScaleXY (string & str)
Definition at line 914 of file console.cpp.
References console_print(), ScreenScale, SetScreenScale(), Screenscale::x, and Screenscale::y.
Referenced by cConsole::cConsole().
SDL_bool SetScreenScaleY (string & str)
Definition at line 976 of file console.cpp.
References console_print(), ScreenScale, and Screenscale::y.
Referenced by cConsole::cConsole().
SDL_bool ShowFPS (string & str)
Toggle FPS framerate to be displayed.
Definition at line 727 of file console.cpp.
References fps_display.
Referenced by cConsole::cConsole().
SDL_bool soundVol (string & str)
change the volume of a sound (0-128)
Definition at line 618 of file console.cpp.
References console_print(), cSoundManager::GetPointer(), cAudio::GetSoundVolume(), pAudio, cAudio::SetSoundVolume(), SMan, and cAudio::Sound_Volume.
Referenced by cConsole::cConsole().