Meatball: include/Misc.h File Reference
Misc.h File Reference
#include "Globals.h"
Functions
int SDL_ToggleFS (SDL_Window *)
Toggle fullScreen.
SDL_bool MouseCollidesWith (SDL_Rect *Crect)
More english version of.
void UniversalEventHandler (SDL_Event *)
The Universal Event Handler handles some events that should be handled in ANY event handler, like Window Resize events for instance.
Variables
cMouseCursor * pMouse
Function Documentation
SDL_bool MouseCollidesWith (SDL_Rect * Crect)
More english version of.
Definition at line 92 of file Misc.cpp.
References cMouseCursor::CollisonCheck(), and pMouse.
Referenced by ControlsMenu::Collisions(), MainMenu::Collisions(), OptionsMenu::Collisions(), and MainMenu::EventHandler().
int SDL_ToggleFS (SDL_Window * win)
Toggle fullScreen.
Toggle fullScreen.
Returns
-1 on error, 1 on Set fullscreen successful, 0 on Set Windowed successful
Definition at line 52 of file Misc.cpp.
References IsFullScreen().
Referenced by MainMenu::EventHandler(), and UniversalEventHandler().
void UniversalEventHandler (SDL_Event *)
The Universal Event Handler handles some events that should be handled in ANY event handler, like Window Resize events for instance.
Definition at line 5 of file Misc.cpp.
References mode, MODE_QUIT, SDL_ToggleFS(), and Window.
Referenced by Game::EventHandler(), ControlsMenu::EventHandler(), cLevelEditor::EventHandler(), MainMenu::EventHandler(), OptionsMenu::EventHandler(), and cConsole::EventHandler().
Variable Documentation
cMouseCursor* pMouse
Definition at line 12 of file Globals.cpp.