Meatball: main.cpp File Reference
main.cpp File Reference
#include "Globals.h"
#include "Game.h"
#include "MainMenu.h"
#include "level.h"
#include "leveleditor.h"
#include "console.h"
#include "preferences.h"
#include "Camera.h"
#include "player.h"
#include "effects.h"
#include "bullet.h"
#include "enemy.h"
Functions
int DoGame ()
Runs the actual Game.
void initEngine ()
void CreateWindow ()
void QuitGame ()
void SetupMouse ()
int main (int argc, char **argv)
Variables
cSettings * pGameSettings
cPreferences * pPreferences
cCamera * pCamera
cPlayer * pPlayer
cLevel * pLevel
cLevelEditor * pLevelEditor
cConsole * pConsole
Function Documentation
void CreateWindow ()
Definition at line 117 of file main.cpp.
References APP_TITLE, DEBUGLOG, cSettings::Fullscreen, GetRenderer(), GetWindow(), cPreferences::pSettings, Renderer, cSettings::Screen_H, cSettings::Screen_W, Window, window_height, and window_width.
Referenced by initEngine().
int DoGame ()
Runs the actual Game.
Definition at line 42 of file main.cpp.
References MiniEngine::Do(), MainMenu::Do(), mode, MODE_CONSOLE, MODE_GAME, MODE_LEVELEDITOR, MODE_MAINMENU, and MODE_QUIT.
Referenced by main().
void initEngine ()
Definition at line 71 of file main.cpp.
References cPreferences::Apply(), cAudio::bMusic, bold_16, cAudio::bSounds, cFont::CreateFont(), CreateWindow(), FONT_DIR, IMan, cAudio::InitAudio(), InitEP(), InitSDL(), keys, cPreferences::Load(), cSettings::Music, cAudio::Music_Volume, cSettings::mvol, pAudio, pFont, pFramerate, SetColorKey(), SetSpriteSpeedfactor(), SetupMouse(), SMan, cAudio::Sound_Volume, cSettings::Sounds, cFramerate::speedfactor, and cSettings::svol.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 31 of file main.cpp.
References DoGame(), initEngine(), and QuitGame().
void QuitGame (void)
Definition at line 166 of file main.cpp.
References bold_16, DeleteAllBullets(), DeleteAllEnemies(), DeleteAllParticleEmitter(), IMan, pAudio, pCamera, pConsole, pFont, pFramerate, pGameSettings, pLevel, pLevelEditor, pMouse, pPlayer, pPreferences, QuitSDL(), Renderer, SMan, and Window.
Referenced by main().
void SetupMouse ()
Definition at line 256 of file main.cpp.
References cImageManager::Add(), colorkey, cImageManager::GetPointer(), IMan, LoadImage(), PIXMAPS_DIR, pMouse, and Renderer.
Referenced by initEngine().
Variable Documentation
cConsole* pConsole
Definition at line 21 of file main.cpp.
Referenced by QuitGame().
cLevel* pLevel
Definition at line 19 of file main.cpp.
Referenced by QuitGame().
cLevelEditor* pLevelEditor
Definition at line 20 of file main.cpp.
Referenced by QuitGame().