Meatball: Misc.cpp File Reference
Misc.cpp File Reference
#include "Misc.h"
Functions
void UniversalEventHandler (SDL_Event *event)
The Universal Event Handler handles some events that should be handled in ANY event handler, like Window Resize events for instance.
SDL_bool IsFullScreen (SDL_Window *win)
Queries the Screen to see if it's set to Fullscreen or Not.
int SDL_ToggleFS (SDL_Window *win)
Toggles On/Off FullScreen.
SDL_bool MouseCollidesWith (SDL_Rect *Crect)
Check for Collision with the Mouse for collision.
Function Documentation
SDL_bool IsFullScreen (SDL_Window * win)
Queries the Screen to see if it's set to Fullscreen or Not.
Returns
SDL_FALSE if windowed, SDL_TRUE if fullscreen
Definition at line 41 of file Misc.cpp.
Referenced by SDL_ToggleFS().
SDL_bool MouseCollidesWith (SDL_Rect * Crect)
Check for Collision with the Mouse for collision.
More english version of.
Definition at line 92 of file Misc.cpp.
References cMouseCursor::CollisonCheck(), and pMouse.
Referenced by ControlsMenu::Collisions(), MainMenu::Collisions(), OptionsMenu::Collisions(), and MainMenu::EventHandler().
int SDL_ToggleFS (SDL_Window * win)
Toggles On/Off FullScreen.
Toggle fullScreen.
Returns
-1 on error, 1 on Set fullscreen successful, 0 on Set Windowed successful
Definition at line 52 of file Misc.cpp.
References IsFullScreen().
Referenced by MainMenu::EventHandler(), and UniversalEventHandler().
void UniversalEventHandler (SDL_Event * event)
The Universal Event Handler handles some events that should be handled in ANY event handler, like Window Resize events for instance.
Definition at line 5 of file Misc.cpp.
References mode, MODE_QUIT, SDL_ToggleFS(), and Window.
Referenced by Game::EventHandler(), ControlsMenu::EventHandler(), cLevelEditor::EventHandler(), MainMenu::EventHandler(), OptionsMenu::EventHandler(), and cConsole::EventHandler().