Meatball: Playlist Namespace Reference
Playlist Namespace Reference
Conjured to do smooth transitioning of Music while I develop.
Functions
void ls_music ()
This gets all music files from the music directory.
void musicover ()
Puts them into musicfiles array.
Variables
int numsongs
Detailed Description
Conjured to do smooth transitioning of Music while I develop.
May not be a permanent thing.. who knows!
Function Documentation
void Playlist::ls_music ()
This gets all music files from the music directory.
Definition at line 18 of file playlist.cpp.
References numsongs.
Referenced by Game::Init().
void Playlist::musicover ()
Puts them into musicfiles array.
Hooked into the Mixer Song over Hook. It will randomly
pick another song to play
Definition at line 32 of file playlist.cpp.
References DEBUGLOG, MUSIC_DIR, numsongs, cAudio::PlayMusik(), and Random().
Variable Documentation
int Playlist::numsongs
Definition at line 17 of file playlist.cpp.
Referenced by ls_music(), and musicover().