/* Copyright 2011 Google */function tn_aa(a){return a in tn_ba?tn_ba[a]:tn_ba[a]=-1!=navigator.userAgent.toLowerCase().indexOf(a)}var tn_ba={},tn_ca={sa:function(a){return a.document.body.scrollTop},ta:function(a){return a.document.documentElement.scrollTop},U:function(a){return a.pageYOffset}},tn_da={sa:function(a){return a.document.body.scrollLeft},ta:function(a){return a.document.documentElement.scrollLeft},U:function(a){return a.pageXOffset}};
function tn_ea(a,b){try{if(tn_aa("safari")||tn_aa("konqueror"))return b.U(a);if(!window.opera&&"compatMode"in a.document&&"CSS1Compat"==a.document.compatMode)return b.ta(a);if((tn_aa("msie")||tn_aa("trident"))&&!window.opera)return b.sa(a)}catch(c){}return b.U(a)};function tn_a(a,b,c){this.x=a;this.y=b;this.coordinateFrame=c||null}tn_a.prototype.toString=function(){return"[P "+this.x+","+this.y+"]"};tn_a.prototype.clone=function(){return new tn_a(this.x,this.y,this.coordinateFrame)};function tn_fa(a,b){this.dx=a;this.dy=b}tn_fa.prototype.toString=function(){return"[D "+this.dx+","+this.dy+"]"};function Rect(a,b,c,d,e){this.x=a;this.y=b;this.w=c;this.h=d;this.coordinateFrame=e||null}
Rect.prototype.contains=function(a){return this.x<=a.x&&a.x<this.x+this.w&&this.y<=a.y&&a.y<this.y+this.h};Rect.prototype.toString=function(){return"[R "+this.w+"x"+this.h+"+"+this.x+"+"+this.y+"]"};Rect.prototype.clone=function(){return new Rect(this.x,this.y,this.w,this.h,this.coordinateFrame)};function tn_ga(a){function b(b){for(var c=a.offsetParent;c&&c.offsetParent;c=c.offsetParent)c.scrollLeft&&(b.x-=c.scrollLeft),c.scrollTop&&(b.y-=c.scrollTop)}if(!a)return null;var c;c=a.ownerDocument&&a.ownerDocument.parentWindow?a.ownerDocument.parentWindow:a.ownerDocument&&a.ownerDocument.defaultView?a.ownerDocument.defaultView:window;if(a.getBoundingClientRect){var d=a.getBoundingClientRect();return new Rect(d.left+tn_ea(c,tn_da),d.top+tn_ea(c,tn_ca),d.right-d.left,d.bottom-d.top,c)}if(a.ownerDocument&&
a.ownerDocument.getBoxObjectFor)return d=a.ownerDocument.getBoxObjectFor(a),c=new Rect(d.x,d.y,d.width,d.height,c),b(c),c;for(var e=d=0,f=a;f.offsetParent;f=f.offsetParent)d+=f.offsetLeft,e+=f.offsetTop;c=new Rect(d,e,a.offsetWidth,a.offsetHeight,c);b(c);return c};var tn_b=function(){for(var a=[" ","\u0120",-1,"!","\u0120",-1,"\u0120","\u0120",0,"\u0121","\u0120",-1,"\u0121","\u0120|\u0121",0,"\u0122","\u0120|\u0121",-1,"\u0120","[\u0120]",0,"\u0121","[\u0120]",-1,"\u0121","[\u0120\u0121]",0,"\u0122","[\u0120\u0121]",-1,"\u0121","[\u0120-\u0121]",0,"\u0122","[\u0120-\u0121]",-1],b=0;b<a.length;b+=3)if(a[b].search(new RegExp(a[b+1]))!=a[b+2])return!1;return!0}(),tn_ha=tn_b?"A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u00ff\u0100-\u0131\u0134-\u013e\u0141-\u0148\u014a-\u017e\u0180-\u01c3\u01cd-\u01f0\u01f4-\u01f5\u01fa-\u0217\u0250-\u02a8\u02bb-\u02c1\u0386\u0388-\u038a\u038c\u038e-\u03a1\u03a3-\u03ce\u03d0-\u03d6\u03da\u03dc\u03de\u03e0\u03e2-\u03f3\u0401-\u040c\u040e-\u044f\u0451-\u045c\u045e-\u0481\u0490-\u04c4\u04c7-\u04c8\u04cb-\u04cc\u04d0-\u04eb\u04ee-\u04f5\u04f8-\u04f9\u0531-\u0556\u0559\u0561-\u0586\u05d0-\u05ea\u05f0-\u05f2\u0621-\u063a\u0641-\u064a\u0671-\u06b7\u06ba-\u06be\u06c0-\u06ce\u06d0-\u06d3\u06d5\u06e5-\u06e6\u0905-\u0939\u093d\u0958-\u0961\u0985-\u098c\u098f-\u0990\u0993-\u09a8\u09aa-\u09b0\u09b2\u09b6-\u09b9\u09dc-\u09dd\u09df-\u09e1\u09f0-\u09f1\u0a05-\u0a0a\u0a0f-\u0a10\u0a13-\u0a28\u0a2a-\u0a30\u0a32-\u0a33\u0a35-\u0a36\u0a38-\u0a39\u0a59-\u0a5c\u0a5e\u0a72-\u0a74\u0a85-\u0a8b\u0a8d\u0a8f-\u0a91\u0a93-\u0aa8\u0aaa-\u0ab0\u0ab2-\u0ab3\u0ab5-\u0ab9\u0abd\u0ae0\u0b05-\u0b0c\u0b0f-\u0b10\u0b13-\u0b28\u0b2a-\u0b30\u0b32-\u0b33\u0b36-\u0b39\u0b3d\u0b5c-\u0b5d\u0b5f-\u0b61\u0b85-\u0b8a\u0b8e-\u0b90\u0b92-\u0b95\u0b99-\u0b9a\u0b9c\u0b9e-\u0b9f\u0ba3-\u0ba4\u0ba8-\u0baa\u0bae-\u0bb5\u0bb7-\u0bb9\u0c05-\u0c0c\u0c0e-\u0c10\u0c12-\u0c28\u0c2a-\u0c33\u0c35-\u0c39\u0c60-\u0c61\u0c85-\u0c8c\u0c8e-\u0c90\u0c92-\u0ca8\u0caa-\u0cb3\u0cb5-\u0cb9\u0cde\u0ce0-\u0ce1\u0d05-\u0d0c\u0d0e-\u0d10\u0d12-\u0d28\u0d2a-\u0d39\u0d60-\u0d61\u0e01-\u0e2e\u0e30\u0e32-\u0e33\u0e40-\u0e45\u0e81-\u0e82\u0e84\u0e87-\u0e88\u0e8a\u0e8d\u0e94-\u0e97\u0e99-\u0e9f\u0ea1-\u0ea3\u0ea5\u0ea7\u0eaa-\u0eab\u0ead-\u0eae\u0eb0\u0eb2-\u0eb3\u0ebd\u0ec0-\u0ec4\u0f40-\u0f47\u0f49-\u0f69\u10a0-\u10c5\u10d0-\u10f6\u1100\u1102-\u1103\u1105-\u1107\u1109\u110b-\u110c\u110e-\u1112\u113c\u113e\u1140\u114c\u114e\u1150\u1154-\u1155\u1159\u115f-\u1161\u1163\u1165\u1167\u1169\u116d-\u116e\u1172-\u1173\u1175\u119e\u11a8\u11ab\u11ae-\u11af\u11b7-\u11b8\u11ba\u11bc-\u11c2\u11eb\u11f0\u11f9\u1e00-\u1e9b\u1ea0-\u1ef9\u1f00-\u1f15\u1f18-\u1f1d\u1f20-\u1f45\u1f48-\u1f4d\u1f50-\u1f57\u1f59\u1f5b\u1f5d\u1f5f-\u1f7d\u1f80-\u1fb4\u1fb6-\u1fbc\u1fbe\u1fc2-\u1fc4\u1fc6-\u1fcc\u1fd0-\u1fd3\u1fd6-\u1fdb\u1fe0-\u1fec\u1ff2-\u1ff4\u1ff6-\u1ffc\u2126\u212a-\u212b\u212e\u2180-\u2182\u3041-\u3094\u30a1-\u30fa\u3105-\u312c\uac00-\ud7a3":
"A-Za-z",tn_ia=tn_b?"\u4e00-\u9fa5\u3007\u3021-\u3029":"",tn_ja=tn_b?"\u0300-\u0345\u0360-\u0361\u0483-\u0486\u0591-\u05a1\u05a3-\u05b9\u05bb-\u05bd\u05bf\u05c1-\u05c2\u05c4\u064b-\u0652\u0670\u06d6-\u06dc\u06dd-\u06df\u06e0-\u06e4\u06e7-\u06e8\u06ea-\u06ed\u0901-\u0903\u093c\u093e-\u094c\u094d\u0951-\u0954\u0962-\u0963\u0981-\u0983\u09bc\u09be\u09bf\u09c0-\u09c4\u09c7-\u09c8\u09cb-\u09cd\u09d7\u09e2-\u09e3\u0a02\u0a3c\u0a3e\u0a3f\u0a40-\u0a42\u0a47-\u0a48\u0a4b-\u0a4d\u0a70-\u0a71\u0a81-\u0a83\u0abc\u0abe-\u0ac5\u0ac7-\u0ac9\u0acb-\u0acd\u0b01-\u0b03\u0b3c\u0b3e-\u0b43\u0b47-\u0b48\u0b4b-\u0b4d\u0b56-\u0b57\u0b82-\u0b83\u0bbe-\u0bc2\u0bc6-\u0bc8\u0bca-\u0bcd\u0bd7\u0c01-\u0c03\u0c3e-\u0c44\u0c46-\u0c48\u0c4a-\u0c4d\u0c55-\u0c56\u0c82-\u0c83\u0cbe-\u0cc4\u0cc6-\u0cc8\u0cca-\u0ccd\u0cd5-\u0cd6\u0d02-\u0d03\u0d3e-\u0d43\u0d46-\u0d48\u0d4a-\u0d4d\u0d57\u0e31\u0e34-\u0e3a\u0e47-\u0e4e\u0eb1\u0eb4-\u0eb9\u0ebb-\u0ebc\u0ec8-\u0ecd\u0f18-\u0f19\u0f35\u0f37\u0f39\u0f3e\u0f3f\u0f71-\u0f84\u0f86-\u0f8b\u0f90-\u0f95\u0f97\u0f99-\u0fad\u0fb1-\u0fb7\u0fb9\u20d0-\u20dc\u20e1\u302a-\u302f\u3099\u309a":
"",tn_ka=tn_b?"0-9\u0660-\u0669\u06f0-\u06f9\u0966-\u096f\u09e6-\u09ef\u0a66-\u0a6f\u0ae6-\u0aef\u0b66-\u0b6f\u0be7-\u0bef\u0c66-\u0c6f\u0ce6-\u0cef\u0d66-\u0d6f\u0e50-\u0e59\u0ed0-\u0ed9\u0f20-\u0f29":"0-9",tn_la=tn_b?"\u00b7\u02d0\u02d1\u0387\u0640\u0e46\u0ec6\u3005\u3031-\u3035\u309d-\u309e\u30fc-\u30fe":"",tn_ma=tn_ha+tn_ia,tn_na=tn_ma+tn_ka+"\\._:"+tn_ja+tn_la+"-",tn_oa="["+tn_ma+"_:]["+tn_na+"]*",tn_pa="&"+tn_oa+";",tn_qa=tn_pa+"|&#[0-9]+;|&#x[0-9a-fA-F]+;",tn_ra='"(([^<&"]|'+tn_qa+")*)\"|'(([^<&']|"+
tn_qa+")*)'",tn_sa="("+tn_oa+")([ \t\r\n]+)?=([ \t\r\n]+)?("+tn_ra+")",tn_ta=tn_b?":A-Z_a-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd":":A-Z_a-z",tn_ua=tn_ta+(tn_b?"\\.0-9\u00b7\u0300-\u036f\u203f-\u2040-":"\\.0-9-"),tn_va="["+tn_ta+"]["+tn_ua+"]*",tn_wa="&"+tn_va+";",tn_xa=tn_wa+"|&#[0-9]+;|&#x[0-9a-fA-F]+;",tn_ya='"(([^<&"]|'+tn_xa+")*)\"|'(([^<&']|"+tn_xa+")*)'",tn_za="("+tn_va+")([ \t\r\n]+)?=([ \t\r\n]+)?("+
tn_ya+")",tn_Aa=tn_ma+tn_ka+"\\._"+tn_ja+tn_la+"-",tn_Ba="["+tn_ma+"_]["+tn_Aa+"]*";function tn_c(a){a||tn_d("Assertion failed")}function tn_e(a,b){var c=a.indexOf(b);if(-1==c)return[a];var d=[];for(d.push(a.substr(0,c));-1!=c;){var e=a.indexOf(b,c+1);-1!=e?d.push(a.substr(c+1,e-c-1)):d.push(a.substr(c+1));c=e}return d}
function tn_Ca(a,b){if(3==b.nodeType)return a.createTextNode(b.nodeValue);if(4==b.nodeType)return a.createCDATASection(b.nodeValue);if(1==b.nodeType){for(var c=a.createElement(b.nodeName),d=0;d<b.attributes.length;++d){var e=b.attributes[d],f=e.nodeName,e=e.nodeValue;c.setAttribute(f,e)}for(d=b.firstChild;d;d=d.nextSibling)f=arguments.callee(a,d),c.appendChild(f);return c}return a.createComment(b.nodeName)}function Set(){this.keys=[]}Set.prototype.size=function(){return this.keys.length};
Set.prototype.add=function(a,b){var c=b||1;this.contains(a)||(this[":"+a]=c,this.keys.push(a))};Set.prototype.set=function(a,b){var c=b||1;this.contains(a)?this[":"+a]=c:(this[":"+a]=c,this.keys.push(a))};Set.prototype.get=function(a){if(this.contains(a))return this[":"+a];var b;return b};Set.prototype.remove=function(a){this.contains(a)&&(delete this[":"+a],tn_Da(this.keys,a,!0))};Set.prototype.contains=function(a){return"undefined"!=typeof this[":"+a]};
Set.prototype.items=function(){for(var a=[],b=0;b<this.keys.length;++b){var c=this.keys[b],c=this[":"+c];a.push(c)}return a};Set.prototype.map=function(a){for(var b=0;b<this.keys.length;++b){var c=this.keys[b];a.call(this,c,this[":"+c])}};Set.prototype.clear=function(){for(var a=0;a<this.keys.length;++a)delete this[":"+this.keys[a]];this.keys.length=0};function tn_Ea(a,b){for(var c=0;c<a.length;++c)b.call(this,a[c],c)}function tn_Fa(a,b){for(var c=[],d=0;d<a.length;++d)c.push(b(a[d]));return c}
function tn_Ga(a){for(var b=0;b<a.length/2;++b){var c=a[b],d=a.length-b-1;a[b]=a[d];a[d]=c}}function tn_Da(a,b,c){for(var d=0,e=0;e<a.length;++e)if(a[e]===b||c&&a[e]==b)a.splice(e--,1),d++;return d}function tn_Ha(a,b){for(var c=0;c<b.length;++c)a.push(b[c])}function tn_f(a){if(!a)return"";var b="";if(3==a.nodeType||4==a.nodeType||2==a.nodeType)b+=a.nodeValue;else if(1==a.nodeType||9==a.nodeType||11==a.nodeType)for(var c=0;c<a.childNodes.length;++c)b+=arguments.callee(a.childNodes[c]);return b}
function tn_Ia(a,b){var c=[];tn_Ja(a,c,b);return c.join("")}
function tn_Ja(a,b,c){if(3==a.nodeType)b.push(tn_Ka(a.nodeValue));else if(4==a.nodeType)c?b.push(a.nodeValue):b.push("<![CDATA["+a.nodeValue+"]]\x3e");else if(8==a.nodeType)b.push("\x3c!--"+a.nodeValue+"--\x3e");else if(1==a.nodeType){b.push("<"+tn_La(a));for(var d=0;d<a.attributes.length;++d){var e=a.attributes[d];e&&e.nodeName&&e.nodeValue&&b.push(" "+tn_La(e)+'="'+tn_Ka(e.nodeValue).replace(/\"/g,"&quot;")+'"')}if(0==a.childNodes.length)b.push("/>");else{b.push(">");for(d=0;d<a.childNodes.length;++d)arguments.callee(a.childNodes[d],
b,c);b.push("</"+tn_La(a)+">")}}else if(9==a.nodeType||11==a.nodeType)for(d=0;d<a.childNodes.length;++d)arguments.callee(a.childNodes[d],b,c)}function tn_La(a){return a.prefix&&0!=a.nodeName.indexOf(a.prefix+":")?a.prefix+":"+a.nodeName:a.nodeName}function tn_Ka(a){return(""+a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}function tn_Ma(a,b,c){return a.setAttribute(b,c)}function tn_Na(a,b){return a.appendChild(b)}function tn_Oa(a,b){return a.createTextNode(b)}
function tn_Pa(a){return a.createDocumentFragment()}function tn_d(a){if("undefined"!=typeof Error)throw Error(a||"Assertion Failed");throw a;};function tn_Qa(a){a=tn_e(a,"&");for(var b=a[0],c=1;c<a.length;++c){var d=a[c].indexOf(";");if(-1==d)b+=a[c];else{var e=a[c].substring(0,d),d=a[c].substring(d+1);switch(e){case "lt":e="<";break;case "gt":e=">";break;case "amp":e="&";break;case "quot":e='"';break;case "apos":e="'";break;case "nbsp":e=String.fromCharCode(160);break;default:var f=window.document.createElement("span");f.innerHTML="&"+e+"; ";e=f.childNodes[0].nodeValue.charAt(0)}b+=e+d}}return b}
var tn_Ra=new RegExp("^("+tn_oa+")"),tn_Sa=new RegExp(tn_sa,"g"),tn_Ta=new RegExp("^("+tn_va+")"),tn_Ua=new RegExp(tn_za,"g");
function tn_Va(a){var b=/\/$/,c,d;a.match(/^<\?xml/)?5==a.search(/[ \t\r\n]+version([ \t\r\n]+)?=([ \t\r\n]+)?("1\.0"|'1\.0')/)?(c=tn_Ra,d=tn_Sa):5==a.search(/[ \t\r\n]+version([ \t\r\n]+)?=([ \t\r\n]+)?("1\.1"|'1\.1')/)?(c=tn_Ta,d=tn_Ua):alert("VersionInfo is missing, or unknown version number."):(c=tn_Ra,d=tn_Sa);var e=new tn_g,f=e,h=[],p=f;h.push(p);var m="";a=tn_e(a,"<");for(var l=1;l<a.length;++l){var g=tn_e(a[l],">"),k=g[0],g=tn_Qa(g[1]||"");if(m)if(k=a[l].indexOf(m),-1!=k){var q=a[l].substring(0,
k);p.nodeValue+="<"+q;h.pop();p=h[h.length-1];g=a[l].substring(k+m.length);m=""}else p.nodeValue+="<"+a[l],g=null;else if(0==k.indexOf("![CDATA["))if(q=8,k=a[l].indexOf("]]\x3e"),-1!=k){var q=a[l].substring(q,k),n=e.createCDATASection(q);p.appendChild(n)}else q=a[l].substring(q),g=null,n=e.createCDATASection(q),p.appendChild(n),p=n,h.push(n),m="]]\x3e";else if(0==k.indexOf("!--"))q=3,k=a[l].indexOf("--\x3e"),-1!=k?(q=a[l].substring(q,k),n=e.createComment(q),p.appendChild(n)):(q=a[l].substring(q),
g=null,n=e.createComment(q),p.appendChild(n),p=n,h.push(n),m="--\x3e");else if("/"==k.charAt(0))h.pop(),p=h[h.length-1];else if("?"!=k.charAt(0)&&"!"!=k.charAt(0)){for(var q=k.match(b),n=c.exec(k)[1],n=e.createElement(n),t;t=d.exec(k);){var r=tn_Qa(t[5]||t[7]||"");n.setAttribute(t[1],r)}p.appendChild(n);q||(p=n,h.push(n))}g&&p!=f&&tn_Na(p,e.createTextNode(g))}return f}
function tn_Wa(a,b,c){var d;if(b&&(d=b.call(null,a),"boolean"==typeof d&&!d))return!1;for(var e=a.firstChild;e;e=e.nextSibling)if(1==e.nodeType&&(d=arguments.callee.call(this,e,b,c),"boolean"==typeof d&&!d))return!1;if(c&&(d=c.call(null,a),"boolean"==typeof d&&!d))return!1}function tn_h(a,b,c,d){this.attributes=[];this.childNodes=[];tn_h.init.call(this,a,b,c,d)}
tn_h.init=function(a,b,c,d){this.nodeType=a-0;this.nodeName=""+b;this.nodeValue=""+c;this.ownerDocument=d;this.parentNode=this.previousSibling=this.nextSibling=this.lastChild=this.firstChild=null};tn_h.ga=[];
tn_h.recycle=function(a){if(a)if(a.constructor==tn_g)tn_h.recycle(a.documentElement);else if(a.constructor==this){tn_h.ga.push(a);for(var b=0;b<a.attributes.length;++b)tn_h.recycle(a.attributes[b]);for(b=0;b<a.childNodes.length;++b)tn_h.recycle(a.childNodes[b]);a.attributes.length=0;a.childNodes.length=0;tn_h.init.call(a,0,"","",null)}};tn_h.create=function(a,b,c,d){if(0<tn_h.ga.length){var e=tn_h.ga.pop();tn_h.init.call(e,a,b,c,d);return e}return new tn_h(a,b,c,d)};
tn_h.prototype.appendChild=function(a){0==this.childNodes.length&&(this.firstChild=a);a.previousSibling=this.lastChild;a.nextSibling=null;this.lastChild&&(this.lastChild.nextSibling=a);a.parentNode=this;this.lastChild=a;this.childNodes.push(a)};
tn_h.prototype.replaceChild=function(a,b){if(b!=a)for(var c=0;c<this.childNodes.length;++c)if(this.childNodes[c]==b){this.childNodes[c]=a;c=b.parentNode;b.parentNode=null;a.parentNode=c;c=b.previousSibling;b.previousSibling=null;a.previousSibling=c;a.previousSibling&&(a.previousSibling.nextSibling=a);c=b.nextSibling;b.nextSibling=null;a.nextSibling=c;a.nextSibling&&(a.nextSibling.previousSibling=a);this.firstChild==b&&(this.firstChild=a);this.lastChild==b&&(this.lastChild=a);break}};
tn_h.prototype.insertBefore=function(a,b){if(b!=a&&b.parentNode==this){a.parentNode&&a.parentNode.removeChild(a);for(var c=[],d=0;d<this.childNodes.length;++d){var e=this.childNodes[d];e==b&&(c.push(a),a.parentNode=this,a.previousSibling=b.previousSibling,b.previousSibling=a,a.previousSibling&&(a.previousSibling.nextSibling=a),a.nextSibling=b,this.firstChild==b&&(this.firstChild=a));c.push(e)}this.childNodes=c}};
tn_h.prototype.removeChild=function(a){for(var b=[],c=0;c<this.childNodes.length;++c){var d=this.childNodes[c];d!=a?b.push(d):(d.previousSibling&&(d.previousSibling.nextSibling=d.nextSibling),d.nextSibling&&(d.nextSibling.previousSibling=d.previousSibling),this.firstChild==d&&(this.firstChild=d.nextSibling),this.lastChild==d&&(this.lastChild=d.previousSibling))}this.childNodes=b};tn_h.prototype.hasAttributes=function(){return 0<this.attributes.length};
tn_h.prototype.setAttribute=function(a,b){for(var c=0;c<this.attributes.length;++c)if(this.attributes[c].nodeName==a){this.attributes[c].nodeValue=""+b;return}this.attributes.push(tn_h.create(2,a,b,this))};tn_h.prototype.getAttribute=function(a){for(var b=0;b<this.attributes.length;++b)if(this.attributes[b].nodeName==a)return this.attributes[b].nodeValue;return null};
tn_h.prototype.removeAttribute=function(a){for(var b=[],c=0;c<this.attributes.length;++c)this.attributes[c].nodeName!=a&&b.push(this.attributes[c]);this.attributes=b};tn_h.prototype.getElementsByTagName=function(a){var b=[];tn_Wa(this,function(c){c.nodeName==a&&b.push(c)},null);return b};tn_h.prototype.getElementById=function(a){var b=null;tn_Wa(this,function(c){if(c.getAttribute("id")==a)return b=c,!1},null);return b};
function tn_g(){tn_h.call(this,9,"#document",null,null);this.documentElement=null}tn_g.prototype=new tn_h(9,"#document");tn_g.prototype.clear=function(){tn_h.recycle(this.documentElement);this.documentElement=null};tn_g.prototype.appendChild=function(a){tn_h.prototype.appendChild.call(this,a);this.documentElement=this.childNodes[0]};tn_g.prototype.createElement=function(a){return tn_h.create(1,a,null,this)};
tn_g.prototype.createDocumentFragment=function(){return tn_h.create(11,"#document-fragment",null,this)};tn_g.prototype.createTextNode=function(a){return tn_h.create(3,"#text",a,this)};tn_g.prototype.createAttribute=function(a){return tn_h.create(2,a,null,this)};tn_g.prototype.createComment=function(a){return tn_h.create(8,"#comment",a,this)};tn_g.prototype.createCDATASection=function(a){return tn_h.create(4,"#cdata-section",a,this)};function tn_Xa(a,b){tn_Ya(new tn_i(a,b),b)}
function tn_Ya(a,b){var c=b.getAttribute("select");if(c)b.removeAttribute("select"),tn_Za(a,b,c);else{if(c=b.getAttribute("display"))if(tn__a(c,a).booleanValue())b.removeAttribute("display");else{b.parentNode.removeChild(b);return}if(c=b.getAttribute("values"))b.removeAttribute("values"),tn_0a(a,b,c);if(c=b.getAttribute("transclude"))(c=tn_1a(c,b.ownerDocument))?(b.parentNode.replaceChild(c,b),tn_Ya(a,c)):b.parentNode.removeChild(b),tn_h.recycle(b);else if(c=b.getAttribute("content"))b.removeAttribute("content"),
tn_2a(a,b,c);else{for(var c=[],d=0;d<b.childNodes.length;++d)1==b.childNodes[d].nodeType&&c.push(b.childNodes[d]);for(d=0;d<c.length;++d)tn_Ya(a,c[d])}}}
function tn_Za(a,b,c){var d=c.split(/;/),e=tn__a(d[0],a).a();if(0<e.length){c=[];for(var f=1;f<e.length;++f){var h=tn_Ca(b.ownerDocument,b);c.push(h);b.parentNode.insertBefore(h,b)}c.push(b);b=[];for(f=1;f<d.length;++f){var p=d[f],m=0;"#"==p.charAt(m)?(h="number",m++):h="text";"-"==p.charAt(m)?(p="descending",m++):p="ascending";m=tn_3a(d[f].substr(m));b.push({expr:m,type:h,order:p})}a=a.clone(e[0],0,e);tn_4a(a,b);for(f=0;f<a.r();++f)1==a.nodelist[f].nodeType&&tn_Ya(a.clone(a.nodelist[f],f),c[f])}else b.parentNode.removeChild(b)}
function tn_0a(a,b,c){c=c.split(/;/);for(var d=0;d<c.length;++d){var e=c[d].indexOf(":");if(!(0>e)){var f=c[d].substr(0,e),e=tn__a(c[d].substr(e+1),a);"$"==f.charAt(0)?a.da(f.substr(1),e):f&&tn_Ma(b,f,e.stringValue())}}}
function tn_2a(a,b,c){for(;b.firstChild;)b.removeChild(b.firstChild);a=tn__a(c,a);if("node-set"==a.type)for(c=0;c<a.value.length;++c){var d=a.value[c];if(1==d.nodeType)for(d=d.firstChild;d;d=d.nextSibling){var e=tn_Ca(b.ownerDocument,d);b.appendChild(e)}else 2==d.nodeType&&(d=b.ownerDocument.createTextNode(d.nodeValue),b.appendChild(d))}else d=tn_Oa(b.ownerDocument,a.stringValue()),b.appendChild(d)}function tn__a(a,b){var c=tn_3a(a);return c=c.evaluate(b)}
function tn_1a(a,b){var c=b.getElementById(a);return c?c=tn_Ca(b,c):null};function tn_3a(a){tn_5a();var b=tn_6a[a];if(b)return b;if(a.match(/^(\$|@)?\w+$/i))return b=tn_7a(a),tn_6a[a]=b;if(a.match(/^\w+(\/\w+)*$/i))return b=tn_8a(a),tn_6a[a]=b;for(var b=a,c=[],d=null,e=null,f=!1,h=0,p=0,m=0;!f;){h++;a=a.replace(/^\s*/,"");for(var e=d,l=d=null,g="",k=0;k<tn_9a.length;++k){var q=tn_9a[k].re.exec(a);p++;if(q&&0<q.length&&q[0].length>g.length){l=tn_9a[k];g=q[0];break}}!l||l!=tn_$a&&l!=tn_ab&&l!=tn_bb&&l!=tn_cb||e&&e.tag!=tn_db&&e.tag!=tn_j&&e.tag!=tn_k&&e.tag!=tn_eb&&e.tag!=
tn_fb||(l=tn_l);l?(a=a.substr(g.length),d={tag:l,match:g,prec:l.prec?l.prec:0,expr:new tn_gb(g)}):f=!0;for(;tn_hb(c,d);)m++}1!=c.length&&tn_d("XPath parse error "+b+":\n"+tn_ib(c));q=c[0].expr;return tn_6a[b]=q}var tn_6a={};
function tn_hb(a,b){var c=null;if(0<a.length){var d=a[a.length-1];if(d=tn_m[d.tag.key])for(var e=0;e<d.length;++e){var f=d[e],h=tn_jb(a,f[1]);if(h.length){c={tag:f[0],rule:f,match:h};c.prec=tn_kb(c);break}}}if(c&&(!b||c.prec>b.prec||b.tag.left&&c.prec>=b.prec)){for(e=0;e<c.match.matchlength;++e)a.pop();d=tn_Fa(c.match,function(a){return a.expr});c.expr=c.rule[3].apply(null,d);a.push(c);c=!0}else b&&a.push(b),c=!1;return c}
function tn_jb(a,b){for(var c=a.length,d=b.length,e=[],f=e.matchlength=0,d=d-1,c=c-1;0<=d&&0<=c;--d,c-=f){var f=0,h=[];if(b[d]==tn_lb)for(--d,e.push(h);0<=c-f&&a[c-f].tag==b[d];)h.push(a[c-f]),f+=1,e.matchlength+=1;else if(b[d]==tn_mb)for(--d,e.push(h);0<=c-f&&2>f&&a[c-f].tag==b[d];)h.push(a[c-f]),f+=1,e.matchlength+=1;else if(b[d]==tn_nb)if(--d,e.push(h),a[c].tag==b[d])for(;0<=c-f&&a[c-f].tag==b[d];)h.push(a[c-f]),f+=1,e.matchlength+=1;else return[];else if(a[c].tag==b[d])e.push(a[c]),f+=1,e.matchlength+=
1;else return[];tn_Ga(h);h.expr=tn_Fa(h,function(a){return a.expr})}tn_Ga(e);return-1==d?e:[]}function tn_kb(a){var b=0;if(a.rule)if(3<=a.rule.length&&0<=a.rule[2])b=a.rule[2];else for(var c=0;c<a.rule[1].length;++c)var d=a.rule[1][c].prec||2,b=Math.max(b,d);else if(a.tag)b=a.tag.prec||2;else if(a.length)for(c=0;c<a.length;++c)d=tn_kb(a[c]),b=Math.max(b,d);return b}function tn_ib(a){for(var b="",c=0;c<a.length;++c)b&&(b+="\n"),b+=a[c].tag.label;return b}
function tn_i(a,b,c,d,e){this.node=a;this.stylesheet=b||null;this.position=c||0;this.nodelist=d||[a];this.variables={};this.parent=e||null;this.root=e?e.root:9==this.node.nodeType?a:a.ownerDocument}tn_i.prototype.clone=function(a,b,c){return new tn_i(a||this.node,this.stylesheet,"undefined"!=typeof b?b:this.position,c||this.nodelist,this)};tn_i.prototype.da=function(a,b){this.variables[a]=b};
tn_i.prototype.D=function(a){return"undefined"!=typeof this.variables[a]?this.variables[a]:this.parent?this.parent.D(a):null};tn_i.prototype.La=function(a){this.node=this.nodelist[a];this.position=a};tn_i.prototype.r=function(){return this.nodelist.length};function tn_n(a){this.value=a;this.type="string"}tn_n.prototype.stringValue=function(){return this.value};tn_n.prototype.booleanValue=function(){return 0<this.value.length};tn_n.prototype.numberValue=function(){return this.value-0};
tn_n.prototype.a=function(){tn_d(this)};function tn_o(a){this.value=a;this.type="boolean"}tn_o.prototype.stringValue=function(){return""+this.value};tn_o.prototype.booleanValue=function(){return this.value};tn_o.prototype.numberValue=function(){return this.value?1:0};tn_o.prototype.a=function(){tn_d(this)};function tn_p(a){this.value=a;this.type="number"}tn_p.prototype.stringValue=function(){return""+this.value};tn_p.prototype.booleanValue=function(){return!!this.value};
tn_p.prototype.numberValue=function(){return this.value-0};tn_p.prototype.a=function(){tn_d(this)};function tn_q(a){this.value=a;this.type="node-set"}tn_q.prototype.stringValue=function(){return 0==this.value.length?"":tn_f(this.value[0])};tn_q.prototype.booleanValue=function(){return 0<this.value.length};tn_q.prototype.numberValue=function(){return this.stringValue()-0};tn_q.prototype.a=function(){return this.value};function tn_gb(a){this.value=a}tn_gb.prototype.evaluate=function(){return new tn_n(this.value)};
function tn_r(){this.absolute=!1;this.rootExpr=null;this.steps=[]}tn_r.prototype.g=function(a){this.steps.push(a)};tn_r.prototype.aa=function(a){this.steps.unshift(a)};tn_r.prototype.evaluate=function(a){var b;b=this.rootExpr?this.rootExpr.evaluate(a).a():this.absolute?[a.root]:[a.node];for(var c=[],d=0;d<b.length;++d){var e=b[d];tn_ob(c,this.steps,0,e,a)}return new tn_q(c)};
function tn_ob(a,b,c,d,e){var f=b[c];d=e.clone(d);f=f.evaluate(d).a();for(d=0;d<f.length;++d)c==b.length-1?a.push(f[d]):tn_ob(a,b,c+1,f[d],e)}function tn_s(a,b,c){this.axis=a;this.nodetest=b;this.predicate=c||[]}tn_s.prototype.ja=function(a){this.predicate.push(a)};
tn_s.prototype.evaluate=function(a){var b=a.node,c=[];if(this.axis==tn_t.ANCESTOR_OR_SELF)for(c.push(b),b=b.parentNode;b;b=b.parentNode)c.push(b);else if(this.axis==tn_t.ANCESTOR)for(b=b.parentNode;b;b=b.parentNode)c.push(b);else if(this.axis==tn_t.ATTRIBUTE)tn_Ha(c,b.attributes);else if(this.axis==tn_t.CHILD)tn_Ha(c,b.childNodes);else if(this.axis==tn_t.DESCENDANT_OR_SELF)c.push(b),tn_pb(c,b);else if(this.axis==tn_t.DESCENDANT)tn_pb(c,b);else if(this.axis==tn_t.FOLLOWING)for(;b;b=b.parentNode)for(var d=
b.nextSibling;d;d=d.nextSibling)c.push(d),tn_pb(c,d);else if(this.axis==tn_t.FOLLOWING_SIBLING)for(b=b.nextSibling;b;b=b.nextSibling)c.push(b);else if(this.axis==tn_t.NAMESPACE)tn_d("not implemented: axis namespace");else if(this.axis==tn_t.PARENT)b.parentNode&&c.push(b.parentNode);else if(this.axis==tn_t.PRECEDING)for(;b;b=b.parentNode)for(d=b.previousSibling;d;d=d.previousSibling)c.push(d),tn_qb(c,d);else if(this.axis==tn_t.PRECEDING_SIBLING)for(b=b.previousSibling;b;b=b.previousSibling)c.push(b);
else this.axis==tn_t.SELF?c.push(b):tn_d("ERROR -- NO SUCH AXIS: "+this.axis);for(var d=c,c=[],e=0;e<d.length;++e)b=d[e],this.nodetest.evaluate(a.clone(b,e,d)).booleanValue()&&c.push(b);for(e=0;e<this.predicate.length;++e)for(var d=c,c=[],f=0;f<d.length;++f)b=d[f],this.predicate[e].evaluate(a.clone(b,f,d)).booleanValue()&&c.push(b);return new tn_q(c)};function tn_rb(){this.value=new tn_o(!0)}tn_rb.prototype.evaluate=function(){return this.value};function tn_sb(){}
tn_sb.prototype.evaluate=function(a){return new tn_o(1==a.node.nodeType||2==a.node.nodeType)};function tn_tb(){}tn_tb.prototype.evaluate=function(a){return new tn_o(3==a.node.nodeType)};function tn_ub(){}tn_ub.prototype.evaluate=function(a){return new tn_o(8==a.node.nodeType)};function tn_vb(a){this.target=a}tn_vb.prototype.evaluate=function(a){return new tn_o(7==a.node.nodeType&&(!this.target||a.node.nodeName==this.target))};function tn_wb(a){this.regex=new RegExp("^"+a+":");this.nsprefix=a}
tn_wb.prototype.evaluate=function(a){a=a.node;return new tn_o(this.regex.test(a.nodeName))};function tn_xb(a){this.name=a}tn_xb.prototype.evaluate=function(a){a=a.node;return new tn_o(a.nodeName==this.name)};function tn_yb(a){this.expr=a}tn_yb.prototype.evaluate=function(a){var b=this.expr.evaluate(a);return"number"==b.type?new tn_o(a.position==b.numberValue()-1):new tn_o(b.booleanValue())};function tn_zb(a){this.name=a;this.args=[]}tn_zb.prototype.Q=function(a){this.args.push(a)};
tn_zb.prototype.evaluate=function(a){var b=""+this.name.value;return(b=this.xpathfunctions[b])?b.call(this,a):new tn_o(!1)};
tn_zb.prototype.xpathfunctions={last:function(a){tn_c(0==this.args.length);return new tn_p(a.r())},position:function(a){tn_c(0==this.args.length);return new tn_p(a.position+1)},count:function(a){tn_c(1==this.args.length);a=this.args[0].evaluate(a);return new tn_p(a.a().length)},id:function(a){tn_c(1==this.args.length);var b=this.args[0].evaluate(a),c=[],d;if("node-set"==b.type){d=[];for(var e=b.a(),b=0;b<e.length;++b)for(var f=tn_f(e[b]).split(/\s+/),h=0;h<f.length;++h)d.push(f[h])}else d=b.stringValue().split(/\s+/);
a=a.node.ownerDocument;for(b=0;b<d.length;++b)(e=a.getElementById(d[b]))&&c.push(e);return new tn_q(c)},"local-name":function(){tn_d("not implmented yet: XPath function local-name()")},"namespace-uri":function(){tn_d("not implmented yet: XPath function namespace-uri()")},name:function(a){tn_c(1==this.args.length||0==this.args.length);a=0==this.args.length?[a.node]:this.args[0].evaluate(a).a();return 0==a.length?new tn_n(""):new tn_n(a[0].nodeName)},string:function(a){tn_c(1==this.args.length||0==
this.args.length);return 0==this.args.length?new tn_n((new tn_q([a.node])).stringValue()):new tn_n(this.args[0].evaluate(a).stringValue())},concat:function(a){for(var b="",c=0;c<this.args.length;++c)b+=this.args[c].evaluate(a).stringValue();return new tn_n(b)},document:function(a){var b=this.args[0].evaluate(a).stringValue();if(""===b&&a.stylesheet)return new tn_q([a.stylesheet]);tn_d("Can't resolve uri in document(\""+b+'")')},"starts-with":function(a){tn_c(2==this.args.length);var b=this.args[0].evaluate(a).stringValue();
a=this.args[1].evaluate(a).stringValue();return new tn_o(0==b.indexOf(a))},contains:function(a){tn_c(2==this.args.length);var b=this.args[0].evaluate(a).stringValue();a=this.args[1].evaluate(a).stringValue();return new tn_o(-1!=b.indexOf(a))},"substring-before":function(a){tn_c(2==this.args.length);var b=this.args[0].evaluate(a).stringValue();a=this.args[1].evaluate(a).stringValue();a=b.indexOf(a);b=-1==a?"":b.substr(0,a);return new tn_n(b)},"substring-after":function(a){tn_c(2==this.args.length);
var b=this.args[0].evaluate(a).stringValue();a=this.args[1].evaluate(a).stringValue();var c=b.indexOf(a),b=-1==c?"":b.substr(c+a.length);return new tn_n(b)},substring:function(a){tn_c(2==this.args.length||3==this.args.length);var b=this.args[0].evaluate(a).stringValue(),c=this.args[1].evaluate(a).numberValue();if(2==this.args.length)c=Math.max(0,Math.round(c)-1),b=b.substr(c);else{a=this.args[2].evaluate(a).numberValue();var d=Math.round(c)-1,c=Math.max(0,d);a=Math.round(a)-Math.max(0,-d);b=b.substr(c,
a)}return new tn_n(b)},"string-length":function(a){a=0<this.args.length?this.args[0].evaluate(a).stringValue():(new tn_q([a.node])).stringValue();return new tn_p(a.length)},"normalize-space":function(a){a=0<this.args.length?this.args[0].evaluate(a).stringValue():(new tn_q([a.node])).stringValue();a=a.replace(/^\s*/,"").replace(/\s*$/,"").replace(/\s+/g," ");return new tn_n(a)},translate:function(a){tn_c(3==this.args.length);var b=this.args[0].evaluate(a).stringValue(),c=this.args[1].evaluate(a).stringValue();
a=this.args[2].evaluate(a).stringValue();for(var d=0;d<c.length;++d)b=b.replace(new RegExp(c.charAt(d),"g"),a.charAt(d));return new tn_n(b)},"boolean":function(a){tn_c(1==this.args.length);return new tn_o(this.args[0].evaluate(a).booleanValue())},not:function(a){tn_c(1==this.args.length);a=!this.args[0].evaluate(a).booleanValue();return new tn_o(a)},"true":function(){tn_c(0==this.args.length);return new tn_o(!0)},"false":function(){tn_c(0==this.args.length);return new tn_o(!1)},lang:function(a){tn_c(1==
this.args.length);var b=this.args[0].evaluate(a).stringValue(),c;for(a=a.node;a&&a!=a.parentNode&&!(c=a.getAttribute("xml:lang"));)a=a.parentNode;return c?(b=new RegExp("^"+b+"$","i"),new tn_o(b.test(c)||b.test(c.replace(/_.*$/,"")))):new tn_o(!1)},number:function(a){tn_c(1==this.args.length||0==this.args.length);return 1==this.args.length?new tn_p(this.args[0].evaluate(a).numberValue()):new tn_p((new tn_q([a.node])).numberValue())},sum:function(a){tn_c(1==this.args.length);a=this.args[0].evaluate(a).a();
for(var b=0,c=0;c<a.length;++c)b+=tn_f(a[c])-0;return new tn_p(b)},floor:function(a){tn_c(1==this.args.length);a=this.args[0].evaluate(a).numberValue();return new tn_p(Math.floor(a))},ceiling:function(a){tn_c(1==this.args.length);a=this.args[0].evaluate(a).numberValue();return new tn_p(Math.ceil(a))},round:function(a){tn_c(1==this.args.length);a=this.args[0].evaluate(a).numberValue();return new tn_p(Math.round(a))},"ext-join":function(a){tn_c(2==this.args.length);var b=this.args[0].evaluate(a).a();
a=this.args[1].evaluate(a).stringValue();for(var c="",d=0;d<b.length;++d)c&&(c+=a),c+=tn_f(b[d]);return new tn_n(c)},"ext-if":function(a){tn_c(3==this.args.length);return this.args[0].evaluate(a).booleanValue()?this.args[1].evaluate(a):this.args[2].evaluate(a)},"ext-cardinal":function(a){tn_c(1<=this.args.length);for(var b=this.args[0].evaluate(a).numberValue(),c=[],d=0;d<b;++d)c.push(a.node);return new tn_q(c)}};function tn_Ab(a,b){this.expr1=a;this.expr2=b}
tn_Ab.prototype.evaluate=function(a){var b=this.expr1.evaluate(a).a();a=this.expr2.evaluate(a).a();for(var c=b.length,d=0;d<a.length;++d){for(var e=a[d],f=!1,h=0;h<c;++h)b[h]==e&&(f=!0,h=c);f||b.push(e)}return new tn_q(b)};function tn_Bb(a,b){this.filter=a;this.rel=b}tn_Bb.prototype.evaluate=function(a){for(var b=this.filter.evaluate(a).a(),c=[],d=0;d<b.length;++d)for(var e=this.rel.evaluate(a.clone(b[d],d,b)).a(),f=0;f<e.length;++f)c.push(e[f]);return new tn_q(c)};
function tn_Cb(a,b){this.expr=a;this.predicate=b}tn_Cb.prototype.evaluate=function(a){for(var b=this.expr.evaluate(a).a(),c=0;c<this.predicate.length;++c)for(var d=b,b=[],e=0;e<d.length;++e){var f=d[e];this.predicate[c].evaluate(a.clone(f,e,d)).booleanValue()&&b.push(f)}return new tn_q(b)};function tn_Db(a){this.expr=a}tn_Db.prototype.evaluate=function(a){return new tn_p(-this.expr.evaluate(a).numberValue())};function tn_Eb(a,b,c){this.expr1=a;this.expr2=c;this.op=b}
tn_Eb.prototype.evaluate=function(a){var b;switch(this.op.value){case "or":b=new tn_o(this.expr1.evaluate(a).booleanValue()||this.expr2.evaluate(a).booleanValue());break;case "and":b=new tn_o(this.expr1.evaluate(a).booleanValue()&&this.expr2.evaluate(a).booleanValue());break;case "+":b=new tn_p(this.expr1.evaluate(a).numberValue()+this.expr2.evaluate(a).numberValue());break;case "-":b=new tn_p(this.expr1.evaluate(a).numberValue()-this.expr2.evaluate(a).numberValue());break;case "*":b=new tn_p(this.expr1.evaluate(a).numberValue()*
this.expr2.evaluate(a).numberValue());break;case "mod":b=new tn_p(this.expr1.evaluate(a).numberValue()%this.expr2.evaluate(a).numberValue());break;case "div":b=new tn_p(this.expr1.evaluate(a).numberValue()/this.expr2.evaluate(a).numberValue());break;case "=":b=this.compare(a,function(a,b){return a==b});break;case "!=":b=this.compare(a,function(a,b){return a!=b});break;case "<":b=this.compare(a,function(a,b){return a<b});break;case "<=":b=this.compare(a,function(a,b){return a<=b});break;case ">":b=
this.compare(a,function(a,b){return a>b});break;case ">=":b=this.compare(a,function(a,b){return a>=b});break;default:tn_d("BinaryExpr.evaluate: "+this.op.value)}return b};
tn_Eb.prototype.compare=function(a,b){var c=this.expr1.evaluate(a),d=this.expr2.evaluate(a);if("node-set"==c.type&&"node-set"==d.type)for(var c=c.a(),e=d.a(),d=!1,f=0;f<c.length;++f)for(var h=0;h<e.length;++h)b(tn_f(c[f]),tn_f(e[h]))&&(d=!0,h=e.length,f=c.length);else if("node-set"==c.type||"node-set"==d.type)if("number"==c.type)for(c=c.numberValue(),e=d.a(),d=!1,f=0;f<e.length;++f){if(h=tn_f(e[f])-0,b(c,h)){d=!0;break}}else if("number"==d.type)for(e=c.a(),c=d.numberValue(),d=!1,f=0;f<e.length;++f){if(h=
tn_f(e[f])-0,b(h,c)){d=!0;break}}else if("string"==c.type)for(c=c.stringValue(),e=d.a(),d=!1,f=0;f<e.length;++f){if(h=tn_f(e[f]),b(c,h)){d=!0;break}}else if("string"==d.type)for(e=c.a(),c=d.stringValue(),d=!1,f=0;f<e.length;++f){if(h=tn_f(e[f]),b(h,c)){d=!0;break}}else d=b(c.booleanValue(),d.booleanValue());else d="boolean"==c.type||"boolean"==d.type?b(c.booleanValue(),d.booleanValue()):"number"==c.type||"number"==d.type?b(c.numberValue(),d.numberValue()):b(c.stringValue(),d.stringValue());return new tn_o(!!d)};
function tn_Fb(a){this.value=a}tn_Fb.prototype.evaluate=function(){return new tn_n(this.value)};function tn_Gb(a){this.value=a}tn_Gb.prototype.evaluate=function(){return new tn_p(this.value)};function tn_Hb(a){this.name=a}tn_Hb.prototype.evaluate=function(a){return a.D(this.name)};function tn_u(a){return a}function tn_Ib(a,b){b.absolute=!0;return b}function tn_Jb(a,b){b.absolute=!0;b.aa(tn_v(a.value));return b}function tn_Kb(){var a=new tn_r;a.g(tn_v("."));a.absolute=!0;return a}
function tn_Lb(a){var b=new tn_r;b.absolute=!0;b.g(tn_v(a.value));return b}function tn_Mb(a){var b=new tn_r;b.g(a);return b}function tn_Nb(a,b,c){a.g(c);return a}function tn_Ob(a,b){a.g(tn_v(b.value));return a}function tn_Pb(a,b,c){b=new tn_r;b.rootExpr=a;b.g(c);return b}function tn_Qb(a){return tn_v(a.value)}function tn_Rb(a){return tn_v(a.value)}function tn_Sb(a,b,c){return new tn_s(a.value,c)}function tn_Tb(a,b){return new tn_s("attribute",b)}function tn_Ub(a){return new tn_s("child",a)}
function tn_Vb(a,b){a.ja(b);return a}function tn_v(a){switch(a){case "//":return new tn_s("descendant-or-self",new tn_rb);case ".":return new tn_s("self",new tn_rb);case "..":return new tn_s("parent",new tn_rb)}}function tn_Wb(){return new tn_sb}function tn_Xb(a){return new tn_wb(a.value)}function tn_Yb(a){return new tn_xb(a.value)}
function tn_Zb(a){a=a.value.replace(/\s*\($/,"");switch(a){case "node":return new tn_rb;case "text":return new tn_tb;case "comment":return new tn_ub;case "processing-instruction":return new tn_vb("")}}function tn__b(a,b){var c=a.replace(/\s*\($/,"");"processing-instruction"!=c&&tn_d(c);return new tn_vb(b.value)}function tn_0b(a,b){return new tn_yb(b)}function tn_1b(a,b){return b}function tn_2b(a){return new tn_zb(a)}
function tn_3b(a,b,c,d){a=new tn_zb(a);a.Q(c);for(c=0;c<d.length;++c)a.Q(d[c]);return a}function tn_4b(a,b){return b}function tn_5b(a,b,c){return new tn_Ab(a,c)}function tn_6b(a,b,c){return new tn_Bb(a,c)}function tn_7b(a,b,c){c.aa(tn_v(b.value));return new tn_Bb(a,c)}function tn_8b(a,b){return 0<b.length?new tn_Cb(a,b):a}function tn_9b(a,b){return new tn_Db(b)}function tn_w(a,b,c){return new tn_Eb(a,b,c)}function tn_$b(a){a=a.value.substring(1,a.value.length-1);return new tn_Fb(a)}
function tn_ac(a){return new tn_Gb(a.value)}function tn_bc(a,b){return new tn_Hb(b.value)}function tn_7a(a){if("$"==a.charAt(0))return new tn_Hb(a.substr(1));if("@"==a.charAt(0)){a=new tn_xb(a.substr(1));a=new tn_s("attribute",a);var b=new tn_r;b.g(a);return b}if(a.match(/^[0-9]+$/))return new tn_Gb(a);a=new tn_xb(a);a=new tn_s("child",a);b=new tn_r;b.g(a);return b}function tn_8a(a){a=tn_e(a,"/");for(var b=new tn_r,c=0;c<a.length;++c){var d=new tn_xb(a[c]),d=new tn_s("child",d);b.g(d)}return b}
var tn_t={ANCESTOR_OR_SELF:"ancestor-or-self",ANCESTOR:"ancestor",ATTRIBUTE:"attribute",CHILD:"child",DESCENDANT_OR_SELF:"descendant-or-self",DESCENDANT:"descendant",FOLLOWING_SIBLING:"following-sibling",FOLLOWING:"following",NAMESPACE:"namespace",PARENT:"parent",PRECEDING_SIBLING:"preceding-sibling",PRECEDING:"preceding",SELF:"self"},tn_cc=[tn_t.ANCESTOR_OR_SELF,tn_t.ANCESTOR,tn_t.ATTRIBUTE,tn_t.CHILD,tn_t.DESCENDANT_OR_SELF,tn_t.DESCENDANT,tn_t.FOLLOWING_SIBLING,tn_t.FOLLOWING,tn_t.NAMESPACE,tn_t.PARENT,
tn_t.PRECEDING_SIBLING,tn_t.PRECEDING,tn_t.SELF].join("|"),tn_dc={label:"|",prec:17,re:/^\|/},tn_j={label:"//",prec:19,re:/^\/\//},tn_k={label:"/",prec:30,re:/^\//},tn_eb={label:"::",prec:20,re:/^::/},tn_ec={label:":",prec:1E3,re:/^:/},tn_fc={label:"[axis]",re:new RegExp("^("+tn_cc+")")},tn_gc={label:"(",prec:34,re:/^\(/},tn_x={label:")",re:/^\)/},tn_hc={label:"..",prec:34,re:/^\.\./},tn_ic={label:".",prec:34,re:/^\./},tn_db={label:"@",prec:34,re:/^@/},tn_jc={label:",",re:/^,/},tn_cb={label:"or",
prec:10,re:/^or\b/},tn_bb={label:"and",prec:11,re:/^and\b/},tn_kc={label:"=",prec:12,re:/^=/},tn_lc={label:"!=",prec:12,re:/^!=/},tn_mc={label:">=",prec:13,re:/^>=/},tn_nc={label:">",prec:13,re:/^>/},tn_oc={label:"<=",prec:13,re:/^<=/},tn_pc={label:"<",prec:13,re:/^</},tn_qc={label:"+",prec:14,re:/^\+/,left:!0},tn_rc={label:"-",prec:14,re:/^\-/,left:!0},tn_$a={label:"div",prec:15,re:/^div\b/,left:!0},tn_ab={label:"mod",prec:15,re:/^mod\b/,left:!0},tn_sc={label:"[",prec:32,re:/^\[/},tn_tc={label:"]",
re:/^\]/},tn_fb={label:"$",re:/^\$/},tn_uc={label:"[ncname]",re:new RegExp("^"+tn_Ba)},tn_vc={label:"*",prec:15,re:/^\*/,left:!0},tn_wc={label:"[litq]",prec:20,re:/^'[^\']*'/},tn_xc={label:"[litqq]",prec:20,re:/^"[^\"]*"/},tn_yc={label:"[number]",prec:35,re:/^\d+(\.\d*)?/},tn_l={label:"[qname]",re:new RegExp("^("+tn_Ba+":)?"+tn_Ba)},tn_zc={label:"[nodetest-start]",re:/^(processing-instruction|comment|text|node)\(/},tn_9a=[tn_j,tn_k,tn_hc,tn_ic,tn_eb,tn_ec,tn_fc,tn_zc,tn_gc,tn_x,tn_sc,tn_tc,tn_db,
tn_jc,tn_cb,tn_bb,tn_lc,tn_kc,tn_mc,tn_nc,tn_oc,tn_pc,tn_qc,tn_rc,tn_vc,tn_dc,tn_ab,tn_$a,tn_wc,tn_xc,tn_yc,tn_l,tn_uc,tn_fb],tn_Ac={label:"LocationPath"},tn_y={label:"RelativeLocationPath"},tn_z={label:"AbsoluteLocationPath"},tn_A={label:"Step"},tn_B={label:"NodeTest"},tn_Bc={label:"Predicate"},tn_Cc={label:"Literal"},tn_C={label:"Expr"},tn_D={label:"PrimaryExpr"},tn_Dc={label:"Variablereference"},tn_Ec={label:"Number"},tn_Fc={label:"FunctionCall"},tn_Gc={label:"ArgumentRemainder"},tn_E={label:"PathExpr"},
tn_Hc={label:"UnionExpr"},tn_Ic={label:"FilterExpr"},tn_Jc={label:"Digits"},tn_Kc=[tn_Ac,tn_y,tn_z,tn_A,tn_B,tn_Bc,tn_Cc,tn_C,tn_D,tn_Dc,tn_Ec,tn_Fc,tn_Gc,tn_E,tn_Hc,tn_Ic,tn_Jc],tn_mb={label:"?"},tn_lb={label:"*"},tn_nb={label:"+"},tn_Lc=[[tn_Ac,[tn_y],18,tn_u],[tn_Ac,[tn_z],18,tn_u],[tn_z,[tn_k,tn_y],18,tn_Ib],[tn_z,[tn_j,tn_y],18,tn_Jb],[tn_z,[tn_k],0,tn_Kb],[tn_z,[tn_j],0,tn_Lb],[tn_y,[tn_A],31,tn_Mb],[tn_y,[tn_y,tn_k,tn_A],31,tn_Nb],[tn_y,[tn_y,tn_j,tn_A],31,tn_Ob],[tn_y,[tn_D,tn_k,tn_A],31,
tn_Pb],[tn_A,[tn_ic],33,tn_Qb],[tn_A,[tn_hc],33,tn_Rb],[tn_A,[tn_fc,tn_eb,tn_B],33,tn_Sb],[tn_A,[tn_db,tn_B],33,tn_Tb],[tn_A,[tn_B],33,tn_Ub],[tn_A,[tn_A,tn_Bc],33,tn_Vb],[tn_B,[tn_vc],33,tn_Wb],[tn_B,[tn_uc,tn_ec,tn_vc],33,tn_Xb],[tn_B,[tn_l],33,tn_Yb],[tn_B,[tn_zc,tn_x],33,tn_Zb],[tn_B,[tn_zc,tn_Cc,tn_x],33,tn__b],[tn_Bc,[tn_sc,tn_C,tn_tc],33,tn_0b],[tn_D,[tn_Dc],33,tn_u],[tn_D,[tn_gc,tn_C,tn_x],33,tn_1b],[tn_D,[tn_Cc],30,tn_u],[tn_D,[tn_Ec],30,tn_u],[tn_D,[tn_Fc],30,tn_u],[tn_Fc,[tn_l,tn_gc,tn_x],
-1,tn_2b],[tn_Fc,[tn_l,tn_gc,tn_C,tn_Gc,tn_lb,tn_x],-1,tn_3b],[tn_Gc,[tn_jc,tn_C],-1,tn_4b],[tn_Hc,[tn_E],20,tn_u],[tn_Hc,[tn_Hc,tn_dc,tn_E],20,tn_5b],[tn_E,[tn_Ac],20,tn_u],[tn_E,[tn_Ic],19,tn_u],[tn_E,[tn_Ic,tn_k,tn_y],20,tn_6b],[tn_E,[tn_Ic,tn_j,tn_y],20,tn_7b],[tn_Ic,[tn_D,tn_Bc,tn_lb],20,tn_8b],[tn_C,[tn_D],16,tn_u],[tn_C,[tn_Hc],16,tn_u],[tn_C,[tn_rc,tn_C],-1,tn_9b],[tn_C,[tn_C,tn_cb,tn_C],-1,tn_w],[tn_C,[tn_C,tn_bb,tn_C],-1,tn_w],[tn_C,[tn_C,tn_kc,tn_C],-1,tn_w],[tn_C,[tn_C,tn_lc,tn_C],-1,
tn_w],[tn_C,[tn_C,tn_pc,tn_C],-1,tn_w],[tn_C,[tn_C,tn_oc,tn_C],-1,tn_w],[tn_C,[tn_C,tn_nc,tn_C],-1,tn_w],[tn_C,[tn_C,tn_mc,tn_C],-1,tn_w],[tn_C,[tn_C,tn_qc,tn_C],-1,tn_w,!0],[tn_C,[tn_C,tn_rc,tn_C],-1,tn_w,!0],[tn_C,[tn_C,tn_vc,tn_C],-1,tn_w,!0],[tn_C,[tn_C,tn_$a,tn_C],-1,tn_w,!0],[tn_C,[tn_C,tn_ab,tn_C],-1,tn_w,!0],[tn_Cc,[tn_wc],-1,tn_$b],[tn_Cc,[tn_xc],-1,tn_$b],[tn_Ec,[tn_yc],-1,tn_ac],[tn_Dc,[tn_fb,tn_l],200,tn_bc]],tn_m=[];
function tn_5a(){function a(a,b,c){a[b]||(a[b]=[]);a[b].push(c)}if(!tn_m.length){tn_Lc.sort(function(a,b){var c=a[1].length,d=b[1].length;return c<d?1:c>d?-1:0});for(var b=1,c=0;c<tn_Kc.length;++c)tn_Kc[c].key=b++;for(c=0;c<tn_9a.length;++c)tn_9a[c].key=b++;for(c=0;c<tn_Lc.length;++c)for(var b=tn_Lc[c],d=b[1],e=d.length-1;0<=e;--e)if(d[e]==tn_nb){a(tn_m,d[e-1].key,b);break}else if(d[e]==tn_lb||d[e]==tn_mb)a(tn_m,d[e-1].key,b),--e;else{a(tn_m,d[e].key,b);break}tn_Ea(tn_m,function(){})}}
function tn_pb(a,b){for(var c=b.firstChild;c;c=c.nextSibling)a.push(c),arguments.callee(a,c)}function tn_qb(a,b){for(var c=b.lastChild;c;c=c.previousSibling)a.push(c),arguments.callee(a,c)}
function tn_4a(a,b){if(0!=b.length){for(var c=[],d=0;d<a.r();++d){for(var e=a.nodelist[d],f={node:e,key:[]},e=a.clone(e,0,[e]),h=0;h<b.length;++h){var p=b[h],m=p.expr.evaluate(e),l;"text"==p.type?l=m.stringValue():"number"==p.type&&(l=m.numberValue());f.key.push({value:l,order:p.order})}f.key.push({value:d,order:"ascending"});c.push(f)}c.sort(tn_Mc);f=[];for(d=0;d<c.length;++d)f.push(c[d].node);a.nodelist=f;a.La(0)}}
function tn_Mc(a,b){for(var c=0;c<a.key.length;++c){var d="descending"==a.key[c].order?-1:1;if(a.key[c].value>b.key[c].value)return 1*d;if(a.key[c].value<b.key[c].value)return-1*d}return 0}function tn_F(a,b){var c=tn_3a(a);return c=c.evaluate(b)};function tn_Nc(a,b){var c=tn_Pa(new tn_g);tn_Oc(new tn_i(a,b),b,c);return c=tn_Ia(c)}
function tn_Oc(a,b,c){var d=9==c.nodeType?c:c.ownerDocument,e=b.nodeName.split(/:/);if(1==e.length||"xsl"!=e[0])tn_Pc(a,b,c,d);else switch(e[1]){case "apply-imports":alert("not implemented: "+e[1]);break;case "apply-templates":e=(e=tn_G(b,"select"))?tn_F(e,a).a():a.node.childNodes;a=a.clone(e[0],0,e);tn_Qc(a,b);tn_Rc(a,b);var f=tn_G(b,"mode"),d=b.ownerDocument.documentElement,e=[];for(b=0;b<d.childNodes.length;++b){var h=d.childNodes[b];1==h.nodeType&&"xsl:template"==h.nodeName&&h.getAttribute("mode")==
f&&e.push(h)}for(d=0;d<a.r();++d)for(h=a.nodelist[d],b=0;b<e.length;++b)tn_Oc(a.clone(h,d),e[b],c);break;case "attribute":e=tn_G(b,"name");e=tn_Sc(e,a);h=tn_Pa(d);tn_H(a,b,h);b=tn_f(h);c.setAttribute(e,b);break;case "attribute-set":alert("not implemented: "+e[1]);break;case "call-template":e=tn_G(b,"name");d=b.ownerDocument.documentElement;a=a.clone();tn_Qc(a,b);for(b=0;b<d.childNodes.length;++b)if(h=d.childNodes[b],1==h.nodeType&&"xsl:template"==h.nodeName&&h.getAttribute("name")==e){tn_H(a,h,c);
break}break;case "choose":tn_Tc(a,b,c);break;case "comment":h=tn_Pa(d);tn_H(a,b,h);b=tn_f(h);b=d.createComment(b);c.appendChild(b);break;case "copy":(h=tn_Uc(c,a.node,d))&&tn_H(a,b,h);break;case "copy-of":e=tn_G(b,"select");b=tn_F(e,a);if("node-set"==b.type)for(e=b.a(),b=0;b<e.length;++b)tn_Vc(c,e[b],d);else h=tn_Oa(d,b.stringValue()),c.appendChild(h);break;case "decimal-format":alert("not implemented: "+e[1]);break;case "element":e=tn_G(b,"name");e=tn_Sc(e,a);h=d.createElement(e);c.appendChild(h);
tn_H(a,b,h);break;case "fallback":alert("not implemented: "+e[1]);break;case "for-each":tn_Wc(a,b,c);break;case "if":d=tn_G(b,"test");d=tn_F(d,a);null!=d&&d.booleanValue()&&tn_H(a,b,c);break;case "import":alert("not implemented: "+e[1]);break;case "include":alert("not implemented: "+e[1]);break;case "key":alert("not implemented: "+e[1]);break;case "message":alert("not implemented: "+e[1]);break;case "namespace-alias":alert("not implemented: "+e[1]);break;case "number":alert("not implemented: "+e[1]);
break;case "otherwise":alert("error if here: "+e[1]);break;case "output":break;case "preserve-space":break;case "processing-instruction":alert("not implemented: "+e[1]);break;case "sort":break;case "strip-space":alert("not implemented: "+e[1]);break;case "stylesheet":case "transform":tn_H(a,b,c);break;case "template":(d=tn_G(b,"match"))&&tn_Xc(d,a)&&tn_H(a,b,c);break;case "text":b=tn_f(b);h=d.createTextNode(b);c.appendChild(h);break;case "value-of":e=tn_G(b,"select");b=tn_F(e,a).stringValue();h=d.createTextNode(b);
c.appendChild(h);break;case "param":tn_Yc(a,b,!1);break;case "variable":tn_Yc(a,b,!0);break;case "when":alert("error if here: "+e[1]);break;case "with-param":alert("error if here: "+e[1]);break;default:alert("error if here: "+e[1])}}function tn_Qc(a,b){for(var c=0;c<b.childNodes.length;++c){var d=b.childNodes[c];1==d.nodeType&&"xsl:with-param"==d.nodeName&&tn_Yc(a,d,!0)}}
function tn_Rc(a,b){for(var c=[],d=0;d<b.childNodes.length;++d){var e=b.childNodes[d];if(1==e.nodeType&&"xsl:sort"==e.nodeName){var f=tn_G(e,"select"),f=tn_3a(f),h=tn_G(e,"data-type")||"text",e=tn_G(e,"order")||"ascending";c.push({expr:f,type:h,order:e})}}tn_4a(a,c)}function tn_Yc(a,b,c){var d=tn_G(b,"name"),e=tn_G(b,"select");0<b.childNodes.length?(e=tn_Pa(b.ownerDocument),tn_H(a,b,e),b=new tn_q([e])):b=e?tn_F(e,a):new tn_n("");!c&&a.D(d)||a.da(d,b)}
function tn_Tc(a,b,c){for(var d=0;d<b.childNodes.length;++d){var e=b.childNodes[d];if(1==e.nodeType)if("xsl:when"==e.nodeName){var f=tn_G(e,"test");if(tn_F(f,a).booleanValue()){tn_H(a,e,c);break}}else if("xsl:otherwise"==e.nodeName){tn_H(a,e,c);break}}}function tn_Wc(a,b,c){var d=tn_G(b,"select"),d=tn_F(d,a).a();a=a.clone(d[0],0,d);tn_Rc(a,b);for(d=0;d<a.r();++d){var e=a.nodelist[d];tn_H(a.clone(e,d),b,c)}}
function tn_H(a,b,c){a=a.clone();for(var d=0;d<b.childNodes.length;++d)tn_Oc(a,b.childNodes[d],c)}function tn_Pc(a,b,c,d){if(3==b.nodeType)tn_Zc(b)&&(d=d.createTextNode(b.nodeValue),c.appendChild(d));else if(1==b.nodeType){d=d.createElement(b.nodeName);for(var e=0;e<b.attributes.length;++e){var f=b.attributes[e];if(f){var h=f.nodeName,f=tn_Sc(f.nodeValue,a);d.setAttribute(h,f)}}c.appendChild(d);tn_H(a,b,d)}else tn_H(a,b,c)}
function tn_Zc(a){if(!a.nodeValue.match(/^\s*$/))return!0;a=a.parentNode;if("xsl:text"==a.nodeName)return!0;for(;a&&1==a.nodeType;){var b=a.getAttribute("xml:space");if(b)if("default"==b)break;else if("preserve"==b)return!0;a=a.parentNode}return!1}function tn_Sc(a,b){var c=tn_e(a,"{");if(1==c.length)return a;for(var d="",e=0;e<c.length;++e){var f=tn_e(c[e],"}");if(2!=f.length)d+=c[e];else var h=tn_F(f[0],b).stringValue(),d=d+(h+f[1])}return d}
function tn_G(a,b){var c=a.getAttribute(b);return c?tn_Qa(c):c}function tn_Vc(a,b,c){if(11==b.nodeType||9==b.nodeType)for(var d=0;d<b.childNodes.length;++d)arguments.callee(a,b.childNodes[d],c);else{var e=tn_Uc(a,b,c);if(e){for(d=0;d<b.attributes.length;++d)arguments.callee(e,b.attributes[d],c);for(d=0;d<b.childNodes.length;++d)arguments.callee(e,b.childNodes[d],c)}}}
function tn_Uc(a,b,c){if(1==b.nodeType)return b=c.createElement(b.nodeName),a.appendChild(b),b;3==b.nodeType?(b=c.createTextNode(b.nodeValue),a.appendChild(b)):4==b.nodeType?(b=c.createCDATASection(b.nodeValue),a.appendChild(b)):8==b.nodeType?(b=c.createComment(b.nodeValue),a.appendChild(b)):2==b.nodeType&&a.setAttribute(b.nodeName,b.nodeValue);return null}
function tn_Xc(a,b){var c=tn_3a(a),d;if(c.steps&&!c.absolute&&1==c.steps.length&&"child"==c.steps[0].axis&&0==c.steps[0].predicate.length)d=c.steps[0].nodetest.evaluate(b).booleanValue();else{d=!1;for(var e=b.node;!d&&e;){for(var f=c.evaluate(b.clone(e,0,[e])).a(),h=0;h<f.length;++h)if(f[h]==b.node){d=!0;break}e=e.parentNode}}return d};function tn__c(a,b){window[a]=b}tn__c("nxslProcess",tn_Xa);tn__c("xmlParse",tn_Va);tn__c("xsltProcess",tn_Nc);tn__c("xmlText",tn_Ia);tn__c("xmlImportNode",tn_Ca);var tn_0c="http://www.gstatic.com/translate/infowindow/";function tn_1c(a){tn_0c=a}function tn_2c(){return tn_0c+"transparent.png"}var tn_3c=Number.MAX_VALUE;function tn_I(a,b,c,d,e,f){var h=((b?b.ownerDocument:null)||document).createElement(a);c&&tn_J(h,c);d&&tn_4c(h,d);h.style.display="none";b&&!e&&(tn_K(b,h),b.windo&&(h.windo=b.windo));f||window.setTimeout(function(){h.style.display=""},0);return h}function tn_L(a,b){var c=((b?b.ownerDocument:null)||document).createTextNode(a);b&&tn_K(b,c);return c}function tn_M(a){return tn_N(a)+"px"}function tn_J(a,b){var c=a.style;c.position="absolute";c.left=tn_M(b.x);c.top=tn_M(b.y)}
function tn_4c(a,b){var c=a.style;c.width=tn_M(b.width);c.height=tn_M(b.height)}function tn_O(a,b){a.style.width=tn_M(b)}function tn_P(a,b){a.style.height=tn_M(b)}function tn_(a){a.style.display="none"}function tn_Q(a){a.style.display=""}function tn_R(a){a.style.visibility="hidden"}function tn_5c(a){a.style.visibility=""}function tn_6c(a){tn_7c(a,"hidden")}function tn_7c(a,b){a.style.overflow=b}var tn_S=Math.min,tn_T=Math.max,tn_N=Math.round;
function tn_U(a,b){try{a.style.cursor=b}catch(c){"pointer"==b&&tn_U(a,"hand")}}function tn_8c(a){tn_9c(a,"gmnoscreen");tn_$c(a,"gmnoprint")}function tn_ad(a,b,c){return window.setTimeout(function(){b.apply(a)},c)}function tn_bd(a){a=a.target||a.srcElement;3==a.nodeType&&(a=a.parentNode);return a}function tn_K(a,b){a.appendChild(b)}function tn_V(a){a.parentNode&&(a.parentNode.removeChild(a),tn_cd(a))}function tn_dd(a){for(var b;b=a.firstChild;)tn_cd(b),a.removeChild(b)}
function tn_ed(a,b){a.innerHTML!=b&&(tn_dd(a),a.innerHTML=b)}function tn_fd(a){tn_W.f()?a.style.MozUserSelect="none":(a.unselectable="on",a.onselectstart=tn_gd)}function tn_hd(a,b){for(var c=a.length,d=0;d<c;++d)b(a[d],d)}function tn_id(a,b,c){for(var d in a)(c||!a.hasOwnProperty||a.hasOwnProperty(d))&&b(d,a[d])}function tn_jd(a,b,c,d){c=c||0;for(d=d||b.length;c<d;++c)a.push(b[c])}function tn_gd(){return!1}
function tn_kd(a,b){1==tn_W.type?a.style.filter="alpha(opacity="+tn_N(100*b)+")":a.style.opacity=b}function tn_ld(a,b,c){a=tn_I("div",a,b,c);a.style.backgroundColor="black";tn_kd(a,.35);return a}function tn_X(a,b){var c=(a?a.ownerDocument:null)||document;if(a.currentStyle)return c=tn_md(b),a.currentStyle[c];if(c.defaultView&&c.defaultView.getComputedStyle)return(c=c.defaultView.getComputedStyle(a,""))?c.getPropertyValue(b):"";c=tn_md(b);return a.style[c]}
function tn_nd(a,b,c){b=c?c:tn_X(a,b);if("number"==typeof b||isNaN(parseInt(b,10)))return b;if(2<b.length&&"px"==b.substring(b.length-2))return parseInt(b,10);(c=a.ownerDocument.getElementById("__mapsBaseCssDummy__"))?a.parentNode.appendChild(c):(c=tn_I("div",a,new tn_a(0,0),new tn_Y(0,0)),c.id="__mapsBaseCssDummy__",tn_R(c));c.style.width="0px";c.style.width=b;return c.offsetWidth}function tn_od(a){return new tn_Y(tn_pd(a,"border-left-width"),tn_pd(a,"border-top-width"))}
function tn_pd(a,b){var c=tn_X(a,b);return isNaN(parseInt(c,10))?0:tn_nd(a,b,c)}function tn_md(a){return a.replace(/-(\w)/g,function(a,c){return(""+c).toUpperCase()})}function tn_qd(a){a.length=0}function tn_rd(a){var b=!1;a&&"object"==typeof a&&(b="function"==typeof Window?a instanceof Window:"object"==typeof a.navigator&&"object"==typeof a.history&&"object"==typeof a.document);return b}function tn_sd(a){return a=tn_rd(a)?a:a&&a.windo?a.windo:window}
function tn_td(a,b){var c=tn_sd(b);return a.windo=c};function tn_ud(a,b,c){tn_vd([a],function(a){b(a[0])},c)}
function tn_vd(a,b,c){c=c||screen.width;var d=tn_I("div",window.document.body,new tn_a(-screen.width,-screen.height),new tn_Y(c,screen.height)),e=[];for(c=0;c<a.length;c++){var f=tn_I("div",d,tn_a.ORIGIN);tn_K(f,a[c]);e.push(f)}window.setTimeout(function(){for(var c=[],f=new tn_Y(0,0),m=0;m<e.length;m++){var l=e[m],g=new tn_Y(l.offsetWidth,l.offsetHeight);c.push(g);l.removeChild(a[m]);tn_V(l);f.width=tn_T(f.width,g.width);f.height=tn_T(f.height,g.height)}tn_V(d);e=null;b(c,f)},0)};function tn_wd(a,b,c,d,e,f,h){e&&1==tn_W.type?(b=tn_I("div",b,c,d),b.style.overflow="hidden",d&&f&&(b.sizingMethod="scale"),d=tn_I("img",b),tn_R(d),tn_xd(d,tn_yd,tn_zd)):(b=tn_I("img",b,c,d),h&&tn_xd(b,tn_yd,tn_Ad));h&&(b.hideAndTrackLoading=!0);tn_fd(b);1==tn_W.type&&(b.galleryImg="no");b.style.border=tn_M(0);b.style.padding=tn_M(0);b.style.margin=tn_M(0);b.oncontextmenu=tn_Bd;tn_Cd(b,a);return b}
function tn_zd(){var a=this.parentNode;a.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod="+(a.sizingMethod?a.sizingMethod:"crop")+',src="'+this.src+'")';a.hideAndTrackLoading&&(a.loaded=!0)}function tn_Cd(a,b){"DIV"==a.tagName?(a.firstChild.src=b,a.src=b,a.hideAndTrackLoading&&(a.style.filter="",a.loaded=!1)):a.hideAndTrackLoading&&b!=tn_2c()?(b!=tn_2c()?(a.loaded=!1,a.pendingSrc=b):a.pendingSrc=null,a.src=tn_2c()):a.src=b}
function tn_Ad(){var a=this;a.src==tn_2c()&&a.pendingSrc?(a.src=a.pendingSrc,a.pendingSrc=null):a.loaded=!0};var tn_Dd="dblclick",tn_yd="load",tn_Ed="unload",tn_Fd="clearlisteners";var tn_Gd=!1;function tn_Z(){this.k=[]}function tn_Hd(){}tn_Z.instance=function(a){a||(a=window);a.gEventListenerPool||(a.gEventListenerPool=new tn_Z);return a.gEventListenerPool};tn_Z.remove=function(a){tn_Z.instance(tn_sd(a)).Ga(a)};tn_Z.prototype.Ga=function(a){var b=this.k.pop(),c=a.oa();c<this.k.length&&(this.k[c]=b,b.B(c));a.B(-1)};tn_Z.push=function(a){tn_Z.instance(tn_sd(a)).Fa(a)};tn_Z.prototype.Fa=function(a){this.k.push(a);a.B(this.k.length-1)};
tn_Z.prototype.clear=function(){for(var a=0;a<this.k.length;++a)this.k[a].B(-1);this.k=[]};function tn_Id(a,b,c){a=new EventListener(a,b,c,0);tn_Z.push(a);return a}function tn_Jd(a){a.remove();tn_Z.remove(a)}function tn_Kd(a){tn__(a,tn_Fd);tn_hd(tn_Ld(a),function(a){a.remove();tn_Z.remove(a)})}function tn_Ld(a,b){var c=[],d=a.__e_;d&&(b?d[b]&&tn_jd(c,d[b]):tn_id(d,function(a,b){tn_jd(c,b)}));return c}
function tn_Md(a,b,c){var d=null,e=a.__e_;e?(d=e[b],d||(d=[],c&&(e[b]=d))):(d=[],c&&(a.__e_={},a.__e_[b]=d));return d}function tn__(a,b,c){var d=[];tn_jd(d,arguments,2);tn_hd(tn_Ld(a,b),function(b){if(tn_Gd)b.apply(a,d);else try{b.apply(a,d)}catch(c){}})}
function tn_xd(a,b,c){3==tn_W.type&&b==tn_Dd?(a["on"+b]=c,c=new EventListener(a,b,c,3)):a.addEventListener?(a.addEventListener(b,c,!1),c=new EventListener(a,b,c,1)):a.attachEvent?(c=tn_Nd(a,c),a.attachEvent("on"+b,c),c=new EventListener(a,b,c,2)):(a["on"+b]=c,c=new EventListener(a,b,c,3));var d=tn_sd(a);a==d&&b==tn_Ed||tn_Z.push(c);return c}function tn_0(a,b,c,d){c=tn_Od(c,d);return tn_xd(a,b,c)}function tn_Pd(a,b,c){tn_0(a,"click",b,c);1==tn_W.type&&tn_0(a,tn_Dd,b,c)}
function tn_Od(a,b){return function(c){c||(c=window.event);c&&!c.target&&(c.target=c.srcElement);b.call(a,c,this)}}function tn_Nd(a,b){return function(){return b.apply(a,arguments)}}function EventListener(a,b,c,d){tn_c(a);tn_c("function"==typeof c);var e=this;e.n=a;e.C=b;e.G=c;e.Ua=d;e.ua=-1;tn_td(e,a);tn_Md(a,b,!0).push(e)}
EventListener.prototype.remove=function(){var a=this;switch(a.Ua){case 1:a.n.removeEventListener(a.C,a.G,!1);break;case 2:a.n.detachEvent("on"+a.C,a.G);break;case 3:a.n["on"+a.C]=null}tn_Da(tn_Md(a.n,a.C),a);a.n=null;a.G=null;a.remove=tn_Hd;a.apply=tn_Hd};EventListener.prototype.oa=function(){return this.ua};EventListener.prototype.B=function(a){this.ua=a};EventListener.prototype.apply=function(a,b){return this.G.apply(a,b)};function tn_cd(a){tn_Wa(a,tn_Kd)}
function tn_Qd(a){"click"==a.type&&tn__(document,"logclick",a);1==tn_W.type?(window.event.cancelBubble=!0,window.event.returnValue=!1):(a.preventDefault(),a.stopPropagation())}function tn_Rd(a){"click"==a.type&&tn__(document,"logclick",a);1==tn_W.type?window.event.cancelBubble=!0:a.stopPropagation()}function tn_Bd(a){1==tn_W.type?window.event.returnValue=!1:a.preventDefault()};var tn_Sd="opera msie chrome applewebkit firefox camino mozilla".split(" "),tn_Td="x11; macintosh windows android ipad ipod iphone webos".split(" ");
function tn_1(a){this.agent=a;this.os=this.type=-1;this.osVersion=0;this.cpu=-1;this.build=this.revision=this.version=0;a=a.toLowerCase();for(var b=0;b<tn_Sd.length;b++){var c=tn_Sd[b];if(-1!=a.indexOf(c)){this.type=b;b=new RegExp(c+"[ /]?([0-9]+(.[0-9]+)?)");if(b=b.exec(a))this.version=parseFloat(b[1]);break}}6==this.type&&(b=/^Mozilla\/.*Gecko\/.*(Minefield|Shiretoko)[ /]?([0-9]+(.[0-9]+)?)/,b=b.exec(this.agent))&&(this.type=4,this.version=parseFloat(b[2]));3==this.type&&(b=/^.*Version\/?([0-9]+(.[0-9]+)?)/,
b=b.exec(this.agent))&&(this.build=this.version,this.version=parseFloat(b[1]));0==this.type&&(b=/^Opera\/9.[89].*Version\/?([0-9]+(.[0-9]+)?)/,b=b.exec(this.agent))&&(this.version=parseFloat(b[1]));for(b=0;b<tn_Td.length;b++)if(c=tn_Td[b],-1!=a.indexOf(c)){this.os=b;break}1==this.os?(b=/Mac OS X[ ]+([0-9]+)[\._]([0-9]+)/,(b=b.exec(this.agent))&&3<=b.length&&(this.osVersion=parseFloat(b[1]+"."+b[2]))):2==this.os&&(b=/Windows NT ([0-9]+.[0-9]+)/,(b=b.exec(this.agent))&&2<=b.length&&(this.osVersion=
parseFloat(b[1])));1==this.os&&-1!=a.indexOf("intel")&&(this.cpu=0);b=/\brv:\s*(\d+\.\d+)/.exec(a);this.f()&&b&&(this.revision=parseFloat(b[1]));1==this.type&&(this.ab=/win64;/.test(a))}tn_1.Za="F9152AEC-3462-4632-8087-EEE3C3CDDA24";tn_1.$a="application/geplugin";tn_1.Ya="getSelf";tn_1.prototype.f=function(){return 4==this.type||6==this.type||5==this.type};tn_1.OS_NAMES={};tn_1.OS_NAMES[2]="windows";tn_1.OS_NAMES[1]="macos";tn_1.OS_NAMES[0]="unix";tn_1.OS_NAMES[3]="android";tn_1.OS_NAMES[6]="iphone";
tn_1.OS_NAMES[-1]="other";tn_1.BROWSER_NAMES={};tn_1.BROWSER_NAMES[1]="ie";tn_1.BROWSER_NAMES[4]="firefox";tn_1.BROWSER_NAMES[2]="chrome";tn_1.BROWSER_NAMES[3]="safari";tn_1.BROWSER_NAMES[0]="opera";tn_1.BROWSER_NAMES[5]="camino";tn_1.BROWSER_NAMES[6]="mozilla";tn_1.BROWSER_NAMES[-1]="other";var tn_W=new tn_1(navigator.userAgent);tn_a.ORIGIN=new tn_a(0,0);tn_a.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function tn_Y(a,b){this.width=a;this.height=b}tn_Y.ZERO=new tn_Y(0,0);tn_Y.prototype.toString=function(){return"("+this.width+", "+this.height+")"};function tn_Ud(a){this.minX=this.minY=tn_3c;this.maxX=this.maxY=-tn_3c;var b=arguments;if(a&&a.length)for(b=0;b<a.length;b++)this.extend(a[b]);else 4<=b.length&&(this.minX=b[0],this.minY=b[1],this.maxX=b[2],this.maxY=b[3])}
tn_Ud.prototype.min=function(){return new tn_a(this.minX,this.minY)};tn_Ud.prototype.max=function(){return new tn_a(this.maxX,this.maxY)};tn_Ud.prototype.toString=function(){return"("+this.min()+", "+this.max()+")"};tn_Ud.prototype.extend=function(a){var b=this;b.minX=tn_S(b.minX,a.x);b.maxX=tn_T(b.maxX,a.x);b.minY=tn_S(b.minY,a.y);b.maxY=tn_T(b.maxY,a.y)};
tn_Ud.intersection=function(a,b){return new tn_Ud([new tn_a(tn_T(a.minX,b.minX),tn_T(a.minY,b.minY)),new tn_a(tn_S(a.maxX,b.maxX),tn_S(a.maxY,b.maxY))])};function tn_$c(a,b){var c=a.className?""+a.className:"";if(c){for(var c=c.split(/\s+/),d=!1,e=0;e<c.length;++e)if(c[e]==b){d=!0;break}d||c.push(b);a.className=c.join(" ")}else a.className=b}function tn_9c(a,b){var c=a.className?""+a.className:"";if(c&&-1!=c.indexOf(b)){for(var c=c.split(/\s+/),d=0;d<c.length;++d)c[d]==b&&c.splice(d--,1);a.className=c.join(" ")}};function tn_Vd(){}tn_Vd.monitor=function(){};tn_Vd.monitorAll=function(){};tn_Vd.dump=function(){};function tn_2(){var a=tn_I("div",document.body),b=a.style;b.position="absolute";b.left=tn_M(7);b.bottom=tn_M(4);b.zIndex=1E4;var c=tn_ld(a,new tn_a(2,2)),d=tn_I("div",a),b=d.style;b.position="relative";b.zIndex=1;b.fontFamily="Verdana,Arial,sans-serif";b.fontSize="small";b.border="1px solid black";var e=[["Clear",this.clear],["Close",this.close]],f=tn_I("div",d),b=f.style;b.position="relative";b.zIndex=2;b.backgroundColor="#979797";b.color="white";b.fontSize="85%";b.padding=tn_M(2);tn_U(f,"default");
tn_fd(f);tn_L("Log",f);for(b=0;b<e.length;b++){var h=e[b];tn_L(" - ",f);var p=tn_I("span",f);p.style.textDecoration="underline";tn_L(h[0],p);tn_Pd(p,this,h[1]);tn_U(p,"pointer")}d=tn_I("div",d);b=d.style;b.backgroundColor="white";b.width="80em";b.height="10em";b.overflow=tn_W.f()?"-moz-scrollbars-vertical":"auto";tn_xd(d,"mousedown",tn_Rd);this.I=d;this.S=a;this.e=c}tn_2.instance=function(){var a=tn_2.n;a||(a=new tn_2,tn_2.n=a);return a};
tn_2.prototype.write=function(a,b){var c=this.ma();b&&(c=tn_I("span",c),c.style.color=b);tn_L(a,c);this.Ha()};tn_2.prototype.clear=function(){this.I.innerHTML=""};tn_2.prototype.close=function(){tn_V(this.S)};tn_2.prototype.ma=function(){var a=tn_I("div",this.I),b=a.style;b.fontSize="85%";b.borderBottom="1px solid silver";b.paddingBottom=tn_M(2);b=tn_I("div",a);b.style.color="gray";b.style.fontSize="75%";tn_L(this.Pa(),b);return a};
tn_2.prototype.Ha=function(){this.I.scrollTop=this.I.scrollHeight;this.Na()};tn_2.prototype.Pa=function(){var a=new Date;return this.v(a.getHours(),2)+":"+this.v(a.getMinutes(),2)+":"+this.v(a.getSeconds(),2)+":"+this.v(a.getMilliseconds(),3)};tn_2.prototype.v=function(a,b){for(var c=a.toString();c.length<b;)c="0"+c;return c};tn_2.prototype.Na=function(){tn_4c(this.e,new tn_Y(this.S.offsetWidth,this.S.offsetHeight))};function tn_Wd(a,b){for(var c=new tn_a(0,0);a&&a!=b;){"BODY"==a.nodeName&&tn_Xd(c,a);var d=tn_od(a);c.x+=d.width;c.y+=d.height;"BODY"==a.nodeName&&tn_W.f()||(c.x+=a.offsetLeft,c.y+=a.offsetTop);tn_W.f()&&1.8<=tn_W.revision&&a.offsetParent&&"BODY"!=a.offsetParent.nodeName&&"visible"!=tn_X(a.offsetParent,"overflow")&&(d=tn_od(a.offsetParent),c.x+=d.width,c.y+=d.height);a.offsetParent&&(c.x-=a.offsetParent.scrollLeft,c.y-=a.offsetParent.scrollTop);if(1!=tn_W.type&&tn_Yd(a)){tn_W.f()&&(c.x-=self.pageXOffset,
c.y-=self.pageYOffset,d=tn_od(a.offsetParent.parentNode),c.x+=d.width,c.y+=d.height);break}3==tn_W.type&&a.offsetParent&&(d=tn_od(a.offsetParent),c.x-=d.width,c.y-=d.height);a=a.offsetParent}1==tn_W.type&&!b&&document.documentElement&&(c.x+=document.documentElement.clientLeft,c.y+=document.documentElement.clientTop);return b&&null==a?(d=tn_Wd(b),new tn_a(c.x-d.x,c.y-d.y)):c}
function tn_Yd(a){return a.offsetParent&&"BODY"==a.offsetParent.nodeName&&"static"==tn_X(a.offsetParent,"position")&&(0==tn_W.type&&"static"!=tn_X(a,"position")||0!=tn_W.type&&"absolute"==tn_X(a,"position"))?!0:!1}
function tn_Xd(a,b){var c=!1;if(tn_W.f()){var c="visible"!=tn_X(b,"overflow")&&"visible"!=tn_X(b.parentNode,"overflow"),d="static"!=tn_X(b,"position");if(d||c){a.x+=tn_nd(b,"margin-left");a.y+=tn_nd(b,"margin-top");var e=tn_od(b.parentNode);a.x+=e.width;a.y+=e.height}d&&(a.x+=tn_nd(b,"left"),a.y+=tn_nd(b,"top"))}if((tn_W.f()||1==tn_W.type)&&"BackCompat"!=document.compatMode||c)self.pageYOffset?(a.x-=self.pageXOffset,a.y-=self.pageYOffset):(a.x-=document.documentElement.scrollLeft,a.y-=document.documentElement.scrollTop)}
function tn_Zd(a,b){if("undefined"!=typeof a.offsetX){var c=tn_bd(a),d=tn_Wd(c,b),e=new tn_a(a.offsetX,a.offsetY);3==tn_W.type&&(c=tn_od(c),e.x-=c.width,e.y-=c.height);return new tn_a(d.x+e.x,d.y+e.y)}return"undefined"!=typeof a.clientX?(d=3==tn_W.type?new tn_a(a.pageX-self.pageXOffset,a.pageY-self.pageYOffset):new tn_a(a.clientX,a.clientY),e=tn_Wd(b),new tn_a(d.x-e.x,d.y-e.y)):tn_a.ORIGIN};function tn__d(a){this.ticks=a;this.tick=0}tn__d.prototype.reset=function(){this.tick=0};tn__d.prototype.next=function(){this.tick++;var a=Math.PI*(this.tick/this.ticks-.5);return(Math.sin(a)+1)/2};tn__d.prototype.more=function(){return this.tick<this.ticks};tn__d.prototype.extend=function(){this.tick>this.ticks/3&&(this.tick=tn_N(this.ticks/3))};var tn_0d=!1;function tn_1d(a,b,c){this.name=a;"string"==typeof b&&(a=tn_I("div",null),tn_ed(a,b),b=a);this.contentElem=b;b.style.zIndex=9500;this.onclick=c}function tn_3(){this.ba=new Rect(0,0,0,0);this.$=tn_Y.ZERO;this.c=[];this.i=[];this.N=[];this.fa=[];this.p=this.q=0;this.m=this.R(tn_Y.ZERO);this.d={};this.j=this.P=this.ya=!1;this.ea=new tn_a(8,8);this.Z="ltr"}
tn_3.prototype.create=function(a,b){var c=this.d,d=tn_2d(c,a,[["iw_n",628,6,0,0,"iw_n1"],["iw_n",628,6,0,0,"iw_n2"],["iw_w",6,598,0,0],["iw_e",6,598,0,0],["iw_s0",628,6,0,0,"iw_s1"],["iw_s0",628,6,0,0,"iw_s2"],["iw_c",628,598,0,0]]),e=new tn_Y(6,6);tn_4(c,d,"iw_nw",e);tn_4(c,d,"iw_ne",e);tn_4(c,d,"iw_xtap",new tn_Y(32,21));tn_4(c,d,"iw_xtap_l",new tn_Y(32,21));tn_4(c,d,"iw_xtap_u",new tn_Y(32,21));tn_4(c,d,"iw_xtap_ul",new tn_Y(32,21));tn_4(c,d,"iw_xtap_rd",new tn_Y(21,32));tn_4(c,d,"iw_xtap_ld",
new tn_Y(21,32));tn_4(c,d,"iw_sw0",e,"iw_sw");tn_4(c,d,"iw_se0",e,"iw_se");tn_8c(d);this.b=d;var e=new tn_Y(8,8),f=tn_2d(c,b,[["iws_n",628,8,0,0,"iws_n1"],["iws_n",628,8,0,0,"iws_n2"],["iws_w",8,598,0,0],["iws_e",8,598,0,0],["iws_s",628,8,0,0,"iws_s1"],["iws_s",628,8,0,0,"iws_s2"],["iws_c",628,598,0,0]]);tn_4(c,f,"iws_nw",e);tn_4(c,f,"iws_ne",e);tn_4(c,f,"iws_sw",e);tn_4(c,f,"iws_se",e);tn_4(c,f,"iws_tap",new tn_Y(37,16));tn_4(c,f,"iws_tap_l",new tn_Y(32,16));tn_4(c,f,"iws_tap_u",new tn_Y(37,26));
tn_4(c,f,"iws_tap_ul",new tn_Y(32,26));tn_4(c,f,"iws_tap_rd",new tn_Y(16,37));tn_4(c,f,"iws_tap_ld",new tn_Y(26,37));tn_4(c,f,"iws_tab_dl",new tn_Y(8,28));tn_4(c,f,"iws_tab_dr",new tn_Y(14,28));tn_4(c,f,"iws_tab_l",new tn_Y(8,28));tn_4(c,f,"iws_tab_r",new tn_Y(14,28));tn_(c.iws_tab_dl);tn_(c.iws_tab_dr);tn_(c.iws_tab_l);tn_(c.iws_tab_r);tn_8c(f);this.e=f;e=new tn_Y(14,13);f=tn_4(c,d,"close",e,"close",!0);f.style.zIndex=1E4;tn_U(f,"pointer");tn_Pd(f,this,this.Da);f=tn_4(c,d,"maximize",e,"maximize",
!0);f.style.zIndex=1E4;tn_R(f);tn_U(f,"pointer");tn_Pd(f,this,this.maximize);c=tn_4(c,d,"restore",e,"restore",!0);c.style.zIndex=10001;tn_R(c);tn_U(c,"pointer");tn_Pd(c,this,this.restore);tn_0(d,"mousedown",this,this.V);tn_0(d,tn_Dd,this,this.na);tn_0(d,"click",this,this.V);tn_0(d,"contextmenu",this,tn_Rd);tn_0(d,"mousewheel",this,tn_Rd);tn_0(d,"DOMMouseScroll",this,tn_Rd);this.Ma();this.hide()};tn_3.prototype.remove=function(){tn_V(this.e);tn_V(this.b)};
tn_3.prototype.ia=function(a){a?(tn_Q(this.d.maximize),tn_Q(this.d.restore)):(tn_(this.d.maximize),tn_(this.d.restore))};tn_3.prototype.M=function(a){this.d.close.style.visibility=a?"visible":"hidden"};tn_3.prototype.Ja=function(a){this.Z=!0===a||"rtl"===a?"rtl":"ltr"};tn_3.prototype.xa=function(a){this.ya=a};tn_3.prototype.za=function(a){this.Aa=a};tn_3.prototype.ha=function(a){this.P=a};
tn_3.prototype.K=function(a){if(!a.getClientRects)return this.l(tn_ga(a));var b=this.s(),c=this.d,d=b.width,e=b.height,f=window.innerWidth||document.body.scrollWidth,b=document.documentElement.scrollLeft||window.scrollX||document.body.scrollLeft,h=document.documentElement.scrollTop||window.scrollY||document.body.scrollTop;tn_(c.iw_xtap);tn_(c.iw_xtap_l);tn_(c.iw_xtap_u);tn_(c.iw_xtap_ul);tn_(c.iw_xtap_ld);tn_(c.iw_xtap_rd);tn_(c.iws_tap);tn_(c.iws_tap_l);tn_(c.iws_tap_u);tn_(c.iws_tap_ul);tn_(c.iws_tap_ld);
tn_(c.iws_tap_rd);var p,m,l,g,c=a.getClientRects(),k=Array(c.length),q=tn_ga(a);a=c[0].top-q.y;for(var n=0;n<c.length;++n){k[n]={left:c[n].left,right:c[n].right,top:c[n].top,bottom:c[n].bottom};0<n&&k[n].bottom==k[n-1].bottom&&(k[n].left==k[n-1].right?(k[n].left=k[n-1].left,k[n].top=tn_S(k[n].top,k[n-1].top)):k[n].right==k[n-1].left&&(k[n].right=k[n-1].right,k[n].top=tn_S(k[n].top,k[n-1].top)));if(!p||k[n].left<=p.left)p=k[n];if(!m||k[n].right>=m.right)m=k[n];if(!l||k[n].top<=l.top)l=k[n];if(!g||
k[n].bottom>=g.bottom)g=k[n]}if(this.j&&21+d+6+12+m.right<f)return this.l(new Rect(p.left+b,m.top-a,m.right-p.left,m.bottom-m.top));if(this.j&&18+d+21<p.left)return this.l(new Rect(p.left+b,p.top-a,m.right-p.left,p.bottom-p.top));this.P&&21+e+6+12+(1<this.c.length?20:0)>q.y-(this.Aa?h:0)?(d=this.j,this.j=!1,l=this.l(new Rect(g.left+b,l.top-a,g.right-g.left,g.bottom-l.top))):(d=this.j,this.j=!1,l=this.l(new Rect(l.left+b,l.top-a,l.right-l.left,g.bottom-l.top)));this.j=d;return l};
tn_3.prototype.l=function(a,b){var c=this.s(),d=this.d,e=c.width,f=c.height,h=document.body.scrollWidth,p=document.documentElement.scrollLeft||window.scrollX||document.body.scrollLeft,m=document.documentElement.scrollTop||window.scrollY||document.body.scrollTop;tn_(d.iw_xtap);tn_(d.iw_xtap_l);tn_(d.iw_xtap_u);tn_(d.iw_xtap_ul);tn_(d.iw_xtap_ld);tn_(d.iw_xtap_rd);tn_(d.iws_tap);tn_(d.iws_tap_l);tn_(d.iws_tap_u);tn_(d.iws_tap_ul);tn_(d.iws_tap_ld);tn_(d.iws_tap_rd);var l=0,c=0,g,k,q,n,t,r=0,u=this.j;
u&&21+e+6+12+a.x+a.w<p+h?(k=!0,f=d.iw_xtap_ld,m=d.iws_tap_ld):u&&18+e+21+p<a.x?(q=!0,f=d.iw_xtap_rd,m=d.iws_tap_rd,c=5):(this.P&&21+f+6+12+(1<this.c.length?20:0)+(this.Aa?m:0)>a.y?(f=d.iw_xtap_u,m=d.iws_tap_u,l=0,g=!0):(f=d.iw_xtap,m=d.iws_tap,l=0),tn_N(a.x+a.w/2)+32+6+12>p+h&&(f==d.iw_xtap_u?(f=d.iw_xtap_ul,m=d.iws_tap_ul):(f=d.iw_xtap_l,m=d.iws_tap_l),c=5,l=32),n=tn_N((e-32)/2),this.ya&&(n+6+12+l+p>a.x+tn_N(a.w/2)?(n=a.x+tn_N(a.w/2)-6-12-l-p,0>n&&(r=tn_S(-n,tn_N(a.w/2)),n=0)):a.x+tn_N(a.w/2)-l+
e-n+18>p+h&&(g?(f=d.iw_xtap_ul,m=d.iws_tap_ul):(f=d.iw_xtap_l,m=d.iws_tap_l),c=5,l=32,n=a.x+tn_N(a.w/2)-l+e+6+12-h-p,n>e-32&&(r=tn_T(e-32-n,-tn_N(a.w/2)),n=e-32))),t=e-32-n);tn_Q(f);tn_Q(m);this.Ta=k?0:q?6+e+21:6+n+l;e=this.$=b||tn_Y.ZERO;r=this.Ta-r;d=k||q?6:g?0:this.pa().height+(1<this.c.length?20:0);r-=e.width;d-=e.height;this.cb=e=new tn_a(a.x+(k?a.w:q?0:a.w/2)-r,a.y+(k||q?a.h/2:g?a.h:0)-d);tn_J(this.b,e);tn_J(this.e,e);this.ba=a;this.Ca=void 0;return this.Ea(k,q,g,n,t,f,m,c)};
tn_3.prototype.Ea=function(a,b,c,d,e,f,h,p){var m=!(a||b||c);this.O=f;this.L=h;var l=this.s(),g=this.d,k=l.width,q=l.height,n=1<this.c.length?this.q:0;c?(tn_O(g.iw_n1,tn_T(d,0)),tn_O(g.iw_n2,tn_T(e,0)),tn_O(g.iw_s1,k-n),tn_O(g.iw_s2,0),tn_O(g.iws_n1,tn_T(d,0)),tn_O(g.iws_n2,tn_T(e,0)),tn_O(g.iws_s1,k-n),tn_O(g.iws_s2,0)):m?(tn_O(g.iw_n1,k-n),tn_O(g.iw_n2,0),tn_O(g.iw_s1,tn_T(d,0)),tn_O(g.iw_s2,tn_T(e,0)),tn_O(g.iws_n1,k-n),tn_O(g.iws_n2,0),tn_O(g.iws_s1,tn_T(d,0)),tn_O(g.iws_s2,tn_T(e,0))):(tn_O(g.iw_n1,
k),tn_O(g.iw_n2,0),tn_O(g.iw_s1,k-n),tn_O(g.iw_s2,0),tn_O(g.iws_n1,k),tn_O(g.iws_n2,0),tn_O(g.iws_s1,k-n),tn_O(g.iws_s2,0));tn_4c(g.iw_c,l);a?(tn_P(g.iw_w,tn_T(q-32,0)),tn_P(g.iw_e,tn_T(q,32)),tn_P(g.iws_w,tn_T(q-32,0)),tn_P(g.iws_e,tn_T(q,32))):b?(tn_P(g.iw_e,tn_T(q-32,0)),tn_P(g.iw_w,tn_T(q,32)),tn_P(g.iws_e,tn_T(q-32,0)),tn_P(g.iws_w,tn_T(q,32))):(tn_P(g.iw_w,q),tn_P(g.iw_e,q),tn_P(g.iws_w,q),tn_P(g.iws_e,q));e=a?15:0;var l=e+5-2,t=e+6,r=t+5,u=t+k,A=u+5,C=a?0:b?u:t+d,F=C+p,E=C+32,G=E+5,k=c?15:
!a&&!b&&1<this.c.length?20:0,B=k+5-2,v=k+6,D=v+5,w=v+(a||b?tn_T(q,32):q),y=w+5,q=c||a||b?w:0;p=q+5-(c||a||b?0:2);d=c||a||b?w+6-1:0;var H=new tn_a(t,w),I=new tn_a(r,y),J=new tn_a(t,k),K=new tn_a(r,B);tn_J(g.iw_nw,new tn_a(e,k));tn_J(g.iws_nw,new tn_a(l,B));m?(tn_J(g.iw_n1,new tn_a(t+n,k)),tn_J(g.iws_n1,new tn_a(r+n,B)),tn_J(g.iw_s1,H),tn_J(g.iws_s1,I),tn_J(g.iw_s2,new tn_a(E,w)),tn_J(g.iws_s2,new tn_a(G,y)),tn_(g.iws_tab_dl),tn_(g.iws_tab_dr),tn_Q(g.iws_tab_l),tn_Q(g.iws_tab_r),tn_J(g.iws_tab_l,new tn_a(l,
p)),tn_J(g.iws_tab_r,new tn_a(r+n-14,p))):(tn_J(g.iw_n1,J),tn_J(g.iws_n1,K),tn_J(g.iw_s2,H),tn_J(g.iws_s2,I),tn_J(g.iw_s1,new tn_a(t+n,w)),tn_J(g.iws_s1,new tn_a(r+n,y)),tn_Q(g.iws_tab_dl),tn_Q(g.iws_tab_dr),tn_(g.iws_tab_l),tn_(g.iws_tab_r),tn_J(g.iws_tab_dl,new tn_a(l,p)),tn_J(g.iws_tab_dr,new tn_a(r+n-14,p)));c?(tn_J(g.iw_n2,new tn_a(E,k)),tn_J(g.iws_n2,new tn_a(G,B))):(tn_J(g.iw_n2,J),tn_J(g.iws_n2,K));tn_J(g.iw_ne,new tn_a(u,k));tn_J(g.iws_ne,new tn_a(A,B));tn_J(g.iw_w,new tn_a(e,v+(a?32:0)));
tn_J(g.iws_w,new tn_a(l,D+(a?32:0)));tn_J(g.iw_c,new tn_a(t,v));tn_J(g.iws_c,new tn_a(r,D));tn_O(g.iw_c,u-t);tn_P(g.iw_c,w-v);tn_O(g.iws_c,A-r);tn_P(g.iws_c,y-D);tn_J(g.iw_e,new tn_a(u,v+(b?32:0)));tn_J(g.iws_e,new tn_a(A,D+(b?32:0)));tn_J(g.iw_sw,new tn_a(e,w));tn_J(g.iws_sw,new tn_a(l,y));tn_J(g.iw_se,new tn_a(u,w));tn_J(g.iws_se,new tn_a(A,y));a?(tn_J(f,new tn_a(0,v)),tn_J(h,new tn_a(0,v))):b?(tn_J(f,new tn_a(u,v)),tn_J(h,new tn_a(A,v))):c?(tn_J(f,new tn_a(C,0)),tn_J(h,new tn_a(F,0))):(tn_J(f,
new tn_a(C,w)),tn_J(h,new tn_a(F,y)));a="rtl"==this.Z?-0+t:u-14+0;b=v-0;tn_J(g.close,new tn_a(a,b));"hidden"!=g.close.style.visibility&&(a="rtl"==this.Z?a+16:a-16);a=new tn_a(a,b);tn_J(g.maximize,a);tn_J(g.restore,a);this.ea=new tn_a(e+8,k+8);for(a=0;a<this.i.length;a++)b=this.i[a],tn_J(b,this.ea);if(2>this.c.length)tn_(g.iws_tab_l),tn_(g.iws_tab_r),tn_(g.iws_tab_dl),tn_(g.iws_tab_dr),tn_Q(g.iw_sw),tn_Q(g.iws_sw),tn_Q(g.iw_nw),tn_Q(g.iws_nw);else for(m?(tn_(g.iw_nw),tn_(g.iws_nw),tn_Q(g.iw_sw),tn_Q(g.iws_sw)):
(tn_(g.iw_sw),tn_(g.iws_sw),tn_Q(g.iw_nw),tn_Q(g.iws_nw)),a=0;a<this.c.length;++a){g=this.c[a];k=g.images;f=g.textWidth;b=g.labelNode;var r=b.style,x;0<a&&(x=this.fa[a-1]);tn_(k.iw_tabback_dl);tn_(k.iw_tabback_dm);tn_(k.iw_tabback_dr);tn_(k.iw_tabback_l);tn_(k.iw_tabback_m);tn_(k.iw_tabback_r);tn_(k.iw_tab_dl);tn_(k.iw_tab_dm);tn_(k.iw_tab_dr);tn_(k.iw_tab_l);tn_(k.iw_tab_m);tn_(k.iw_tab_r);tn_(k.iws_tab_m);tn_(k.iws_tab_dm);x?(tn_(x.iws_tab_do),tn_(x.iws_tab_o)):(tn_(k.iw_tab_1l),tn_(k.iw_tab_1dl),
tn_(k.iw_tabback_1l),tn_(k.iw_tabback_1dl),tn_(k.iws_tab_1l),tn_(k.iws_tab_1dl));var z;c=this.b.style.zIndex;m?(this.p==a?(h=0==a?k.iw_tab_1l:k.iw_tab_l,n=k.iw_tab_m,t=k.iw_tab_r,++c):(h=0==a?k.iw_tabback_1l:k.iw_tabback_l,n=k.iw_tabback_m,t=k.iw_tabback_r),k=k.iws_tab_m,x&&(z=x.iws_tab_o),r.paddingTop=tn_M(4),r.paddingBottom=tn_M(0)):(this.p==a?(h=0==a?k.iw_tab_1dl:k.iw_tab_dl,n=k.iw_tab_dm,t=k.iw_tab_dr,++c):(h=0==a?k.iw_tabback_1dl:k.iw_tabback_dl,n=k.iw_tabback_dm,t=k.iw_tabback_dr),k=k.iws_tab_dm,
x&&(z=x.iws_tab_do),r.paddingTop=tn_M(4),r.paddingBottom="");tn_Q(h);tn_Q(n);tn_Q(t);tn_Q(k);r=g.offset+(0==a?6:11);tn_J(h,new tn_a(e+g.offset,q));tn_J(n,new tn_a(e+r,q));tn_O(n,f);tn_J(k,new tn_a(l+2+r,p));tn_O(k,f);tn_J(t,new tn_a(e+r+f,q));z&&(tn_Q(z),tn_J(z,new tn_a(l+r-14+2,p)),z.parentNode||tn_K(this.e,z));h.style.zIndex=c;n.style.zIndex=c;t.style.zIndex=c;f=f+2+3;tn_O(b,f);tn_J(b,new tn_a(e+r-2,d));tn_Q(b);b.style.zIndex=c+1;!b.parentNode&&0<g.textWidth&&tn_K(this.b,b)}};
tn_3.prototype.A=function(){this.Ca?this.K(this.Ca,this.$):this.ba&&this.l(this.ba,this.$)};tn_3.prototype.s=function(){return new tn_Y(tn_T(this.m.width,this.q),this.m.height)};tn_3.prototype.reset=function(a,b,c,d,e){this.u(c,b,e);this.l(a,d);this.show();tn_R(this.d.restore)};tn_3.prototype.hide=function(){this.O&&tn_(this.O);this.L&&tn_(this.L);tn_(this.b);tn_(this.e)};tn_3.prototype.show=function(){this.wa()&&(tn_Q(this.b),tn_Q(this.e),this.O&&tn_Q(this.O),this.L&&tn_Q(this.L))};
tn_3.prototype.Ma=function(){this.bb=!0};tn_3.prototype.wa=function(){return"none"==this.b.style.display};tn_3.prototype.Ia=function(a){if(a!=this.p){this.ca(a);var b=this.i;tn_hd(b,tn_);tn_Q(b[a]);var c=this;window.setTimeout(function(){c.A()},0)}};tn_3.prototype.Da=function(){tn__(this,"closeclick")};
tn_3.prototype.maximize=function(a){if(!this.H){tn__(this,"maximizeclick");tn_5c(this.d.restore);this.Oa=this.m;this.Xa=this.c;this.Wa=this.p;this.o=this.o||new tn_Y(628,598);var b=new tn_Y(4+this.o.width,4+this.o.height);tn_W.f()&&(b.width+=1);this.Y(b,a)}};tn_3.prototype.restore=function(a){this.H&&(tn__(this,"restoreclick"),tn_R(this.d.restore),this.u(this.o,this.Xa,this.Wa),this.Ra=this.Oa,this.Y(this.Oa,a))};
tn_3.prototype.Y=function(a,b){this.X=new tn__d(!0===b?1:10);this.F=this.m;this.ra=a;this.T()};tn_3.prototype.T=function(){var a=this.X.next();this.X.more()&&tn_ad(this,this.T,10);var b=this.F.width+(this.ra.width-this.F.width)*a,a=this.F.height+(this.ra.height-this.F.height)*a;this.J(new tn_Y(b,a));this.A();this.Qa();this.X.more()||this.qa()};tn_3.prototype.qa=function(){this.H?(this.H=!1,tn__(this,"restoreend")):(this.H=!0,tn__(this,"maximizeend"),this.o&&this.Ba&&this.u(this.o,this.Ba,this.Sa))};
tn_3.prototype.J=function(a){return a=this.m=this.R(a)};tn_3.prototype.na=function(a){if(1==tn_W.type)tn_Qd(a);else{var b=tn_Zd(a,this.b);b.y<=this.W()&&tn_Qd(a)}};tn_3.prototype.V=function(a){if(1==tn_W.type)tn_Rd(a);else{var b=tn_Zd(a,this.b);b.y<=this.W()&&(a.cancelDrag=!0)}};tn_3.prototype.W=function(){return this.s().height+12};tn_3.prototype.pa=function(){var a=this.s();return new tn_Y(a.width+12,a.height+21+6)};
tn_3.prototype.u=function(a,b,c){this.la();this.Ra=a;a=new tn_Y(4+a.width,4+a.height);tn_W.f()&&(a.width+=1);var d=this.J(a),e=[];this.c=e;var f=c||0;a=new tn_Y(d.width+-4,d.height+-4);var h=this.ea,p=this.i=[];for(c=0;c<b.length;c++){var m=tn_I("div",this.b,h,a);tn_6c(m);c!=f&&tn_(m);m.style.zIndex=10;tn_K(m,b[c].contentElem);p.push(m)}if(1<b.length){a=[];h=new tn_Y(11,26);p=new tn_Y(14,26);this.va();for(c=0;c<b.length;++c){var l={images:b[c].images||{},textWidth:b[c].textWidth||0,offset:b[c].offset||
0,name:b[c].name,contentElem:b[c].contentElem,onclick:b[c].onclick},g=l.images;tn_2d(g,this.b,[["iw_tabback_dm",1,26,0,0],["iw_tabback_m",1,26,0,0],["iw_tab_dm",1,26,0,0],["iw_tab_m",1,26,0,0]]);tn_4(g,this.b,"iw_tabback_dl",h);tn_4(g,this.b,"iw_tabback_dr",p);tn_4(g,this.b,"iw_tabback_l",h);tn_4(g,this.b,"iw_tabback_r",p);tn_4(g,this.b,"iw_tab_dl",h);tn_4(g,this.b,"iw_tab_dr",p);tn_4(g,this.b,"iw_tab_l",h);tn_4(g,this.b,"iw_tab_r",p);tn_2d(g,this.e,[["iws_tab_dm",1,28,0,0],["iws_tab_m",1,28,0,0]]);
m=function(a,b){tn_(b);a.N.push(b)};if(0==c){var k=new tn_Y(6,26);tn_4(g,this.b,"iw_tab_1dl",k);tn_4(g,this.b,"iw_tab_1l",k);tn_4(g,this.b,"iw_tabback_1dl",k);tn_4(g,this.b,"iw_tabback_1l",k);k=new tn_Y(8,28);tn_4(g,this.e,"iws_tab_1dl",k);tn_4(g,this.e,"iws_tab_1l",k);m(this,g.iw_tab_1dl);m(this,g.iw_tab_1l);m(this,g.iw_tabback_1dl);m(this,g.iw_tabback_1l);m(this,g.iws_tab_1dl);m(this,g.iws_tab_1l)}m(this,g.iw_tabback_dl);m(this,g.iw_tabback_dm);m(this,g.iw_tabback_dr);m(this,g.iw_tabback_l);m(this,
g.iw_tabback_m);m(this,g.iw_tabback_r);m(this,g.iw_tab_dl);m(this,g.iw_tab_dm);m(this,g.iw_tab_dr);m(this,g.iw_tab_l);m(this,g.iw_tab_m);m(this,g.iw_tab_r);m(this,g.iws_tab_dm);m(this,g.iws_tab_m);g=document.createElement("div");l.labelNode=g;tn_P(g,20);k=g.style;tn_6c(g);k.fontWeight="bold";k.fontFamily="Arial,sans-serif";k.fontSize=tn_M(12);k.textAlign="center";k.display="inline";tn_3d(g);tn_L(l.name,g);(function(a,b,c,d){tn_Pd(d,a,function(){a.Ia(b);c&&c()})})(this,c,b[c].onclick,g);this.N.push(g);
a.push(g);this.c.push(l);0<c&&(l={},g=new tn_Y(14,28),tn_4(l,this.e,"iws_tab_do",g),tn_4(l,this.e,"iws_tab_o",g),m(this,l.iws_tab_do),m(this,l.iws_tab_o),this.fa.push(l))}var q=this;tn_vd(a,function(a){var b;if(a.length==e.length){for(var c=0;c<a.length;++c){var g=b=e[c];0!=a[c].width&&(g.textWidth=tn_T(0,a[c].width-2-3));tn_Q(g.labelNode);tn_K(q.b,g.labelNode);if(0<c){var h=e[c-1];g.offset=h.offset+h.textWidth+(1==c?6:11)+14-11}}q.q=b.offset+b.textWidth+14+11-6;if(q.q+30>d.width)for(q.J(new tn_Y(q.q+
30,d.height)),a=new tn_Y(q.q+30+-4,d.height+-4),c=0;c<q.i.length;++c)tn_4c(q.i[c],a)}q.ca(f);q.A()})}else l={images:b[0].images||{},textWidth:b[0].textWidth||0,offset:b[0].offset||0,name:b[0].name,contentElem:b[0].contentElem,onclick:b[0].onclick},this.c.push(l),this.A()};tn_3.prototype.Qa=function(){for(var a=new tn_Y(this.m.width+-4,this.m.height+-4),b=0;b<this.i.length;b++){var c=this.i[b];tn_4c(c,a)}};tn_3.prototype.Ka=function(a,b,c){this.o=a;this.Ba=b;this.Sa=c;tn_5c(this.d.maximize)};
tn_3.prototype.la=function(){var a=this.i;tn_hd(a,tn_V);tn_qd(a);a=this.N;tn_hd(a,tn_V);tn_qd(a);this.p=0};tn_3.prototype.R=function(a){return new tn_Y(tn_T(a.width,32),tn_T(a.height,0))};tn_3.prototype.va=function(){this.N=[];this.fa=[];this.q=0};tn_3.prototype.ca=function(a){tn_3d(this.c[this.p].labelNode);this.p=a;tn_4d(this.c[a].labelNode)};function tn_4d(a){var b=a.style;b.color="";b.textDecoration="";tn_U(a,"")}
function tn_3d(a){var b=a.style;b.color="#0000cc";b.textDecoration="underline";tn_U(a,"pointer")}function tn_2d(a,b,c){b=tn_I("div",b,null,null,!1,!0);for(var d=0;d<c.length;d++){var e=c[d],f=new tn_Y(e[1],e[2]),h=new tn_a(e[3],e[4]),p=tn_0c+e[0]+".png",f=tn_wd(p,b,h,f,!0,!0);a[e[5]||e[0]]=f}return b}
function tn_4(a,b,c,d,e,f){if(1==tn_W.type&&7>tn_W.version)return b=tn_wd(tn_0c+c+(f?".gif":".png"),b,new tn_a(0,0),d,!0,!0),a[e||c]=b;tn_0d||(tn_0d=!0,d=document.createElement("link"),d.rel="stylesheet",d.type="text/css",d.href=tn_0c+"iw_sprite.css",document.getElementsByTagName("head")[0].appendChild(d));d=document.createElement("div");d.className="SPRITE_"+c;d.style.overflow="hidden";b.appendChild(d);return a[e||c]=d};if(window.jstiming){window.jstiming.ka={};window.jstiming.Va=1;var tn_5d=function(a,b,c){var d=a.t[b],e=a.t.start;if(d&&(e||c))return d=a.t[b][0],e=void 0!=c?c:e[0],d-e},tn_6d=function(a,b,c){var d="";window.jstiming.srt&&(d+="&srt="+window.jstiming.srt,delete window.jstiming.srt);window.jstiming.pt&&(d+="&tbsrt="+window.jstiming.pt,delete window.jstiming.pt);try{window.external&&window.external.tran?d+="&tran="+window.external.tran:window.gtbExternal&&window.gtbExternal.tran?d+="&tran="+window.gtbExternal.tran():
window.chrome&&window.chrome.csi&&(d+="&tran="+window.chrome.csi().tran)}catch(e){}var f=window.chrome;if(f&&(f=f.loadTimes)){f().wasFetchedViaSpdy&&(d+="&p=s");if(f().wasNpnNegotiated){var d=d+"&npn=1",h=f().npnNegotiatedProtocol;h&&(d+="&npnv="+(encodeURIComponent||escape)(h))}f().wasAlternateProtocolAvailable&&(d+="&apa=1")}var p=a.t,m=p.start,f=[],h=[],l;for(l in p)if("start"!=l&&0!=l.indexOf("_")){var g=p[l][1];g?p[g]&&h.push(l+"."+tn_5d(a,l,p[g][0])):m&&f.push(l+"."+tn_5d(a,l))}delete p.start;
if(b)for(var k in b)d+="&"+k+"="+b[k];(b=c)||(b="https:"==document.location.protocol?"https://csi.gstatic.com/csi":"http://csi.gstatic.com/csi");return a=[b,"?v=3","&s="+(window.jstiming.sn||"translate")+"&action=",a.name,h.length?"&it="+h.join(","):"",d,"&rt=",f.join(",")].join("")},tn_7d=function(a,b,c){a=tn_6d(a,b,c);if(!a)return"";b=new Image;var d=window.jstiming.Va++;window.jstiming.ka[d]=b;b.onload=b.onerror=function(){window.jstiming&&delete window.jstiming.ka[d]};b.src=a;b=null;return a},
tn_8d=function(a,b,c){if("prerender"==document.webkitVisibilityState)return!1;tn_7d(a,b,c);return!0};window.jstiming.report=function(a,b,c){if("prerender"==document.webkitVisibilityState){var d=!1,e=function(){d||(b?b.prerender="1":b={prerender:"1"},tn_8d(a,b,c)&&(d=!0,document.removeEventListener("webkitvisibilitychange",e,!1)))};document.addEventListener("webkitvisibilitychange",e,!1);return""}return tn_7d(a,b,c)}};var tn_5,tn_6=null,tn_7,tn_9d,tn_$d,tn_ae=!1,tn_be=!1,tn_8=!1,tn_9=!1,tn_ce={right:"left",left:"right",ltr:"rtl",rtl:"ltr"};function tn_de(a){return a.substring(0,1).toUpperCase()+a.substring(1)}
var _intlStrings={_originalText:"Original Text:",_interfaceDirection:"ltr",_interfaceAlign:"left",_langpair:"",_currentBy:"",_unknown:"unknown",_suggestTranslation:"Suggest a translation",_submit:"Submit",_feedbackUrl:"https://translate.google.com/translate_suggestion",_suggestThanks:"Thank you for helping us improve the quality of our translations.",_reverse:!1,_staticContentPath:""};
function tn_ee(a){if(3==a.nodeType)return a.nodeValue;if(1==a.nodeType){for(var b="",c=0;c<a.childNodes.length;++c)b+=tn_ee(a.childNodes[c]);return b}return""}function tn_fe(a,b){if(a)if(3==b.nodeType)a.appendChild(document.createTextNode(b.nodeValue));else if(1==b.nodeType){var c;if("a"===b.nodeName||"A"===b.nodeName){c=document.createElement("a");var d=b.getAttribute("href");d&&c.setAttribute("href",d);a.appendChild(c)}else c=a;for(d=0;d<b.childNodes.length;++d)tn_fe(c,b.childNodes[d])}}
function _setupIW(){if(!tn_ae){_intlStrings._staticContentPath&&tn_1c(_intlStrings._staticContentPath);tn_5=new tn_3;tn_7=document.createElement("div");tn_7.id="google-infowindow";tn_7.className="notranslate";tn_9d=document.createElement("span");tn_7.onmouseover=tn_ge;tn_7.onmouseout=tn_he;document.body.appendChild(tn_9d);document.body.appendChild(tn_7);var a=document.createElement("div");document.body.appendChild(a);tn_(a);a.innerHTML='<iframe id="google-feedback-frame" name="" + FEEDBACK_TARGET_IFRAME_NAME + ""></iframe>';
tn_5.create(tn_7,tn_9d);tn_7.firstChild.style.zIndex=2147483647;tn_9d.firstChild.style.zIndex=2147483647;tn_5.M(!0);tn_5.xa(!0);tn_5.za(!0);tn_5.ha(!0);tn_5.ia(!1);tn_5.Ja(_intlStrings._interfaceDirection);tn_Id(tn_5,"closeclick",function(){tn_he(!0);tn_9&&tn_ie(!1)});var b=document.getElementById("gt-nvframe");b&&window.addEventListener("scroll",function(){b.style.top=-document.body.scrollTop+"px"},!1);tn_ae=!0}}var tn_$=null;function tn_ge(){tn_be=!0;tn_je(tn_6)}
function tn_je(a){if(a&&(null!==tn_$&&(window.clearTimeout(tn_$),tn_$=null),!tn_8))if(tn_6==a)tn_9||(tn_$d=tn_6.style.backgroundColor,tn_6.style.backgroundColor="#E6ECF9");else{tn_9&&(tn_5.restore(!0),tn_9=!1);for(var b,c=a.cloneNode(!0),d=a.childNodes.length-1;0<=d;--d)"google-src-text"==a.childNodes[d].className&&(b=a.childNodes[d].cloneNode(!0),c.removeChild(c.childNodes[d]),b.className="google-src-active-text");if(b){tn_5.M(!0);tn_$d=a.style.backgroundColor;a.style.backgroundColor="#E6ECF9";var e=
document.createElement("div"),d=document.createElement("div"),f=document.createElement("img"),h=document.createElement("div");h.appendChild(f);f.width=48;f.height=17;f.border=0;f.style.display="inline";f.style.padding="0px";f.style.border="0px solid black";h.style.margin="0px";h.style.marginBottom="-17px";h.style.padding="0px";h.style.textAlign=tn_ce[_intlStrings._interfaceAlign];f.src="http://www.google.com/images/logo_smallest.png";f.style["margin"+tn_de(_intlStrings._interfaceAlign)]="6px";f.style["margin"+
tn_de(tn_ce[_intlStrings._interfaceAlign])]=tn_M(18);e.appendChild(h);e.appendChild(d);d.appendChild(document.createTextNode(_intlStrings._originalText));d.style.color="#333";d.style.direction=_intlStrings._interfaceDirection;d.style.textAlign=_intlStrings._interfaceAlign;d.style.fontWeight="bold";d.style.fontSize="12px";d.style.minHeight="19px";d.style.fontFamily="arial,sans-serif";d.style["margin"+tn_de(tn_ce[_intlStrings._interfaceAlign])]=tn_M(72);d=document.createElement("div");d.className="google-src-active-text";
d.style.lineHeight="19px";d.style.direction=_intlStrings._interfaceDirection;d.style.textAlign=_intlStrings._interfaceAlign;tn_fe(d,b);e.appendChild(d);e.style.zIndex=2147483647;if(0==_intlStrings._langpair.length)tn_6=a,tn_ud(e,function(a){tn_5.hide();tn_5.u(a,[new tn_1d(_intlStrings._originalText,e)]);tn_5.K(tn_6);tn_5.show()},(document.width||document.body.scrollWidth)/2);else{var d=e.cloneNode(!0),p=document.createElement("div");p.appendChild(d);d=document.createElement("div");f=document.createElement("span");
h=document.createElement("div");h.style.direction=_intlStrings._interfaceDirection;h.style.textAlign=_intlStrings._interfaceAlign;h.style.marginTop=tn_M(5);d.appendChild(h);var m=document.createElement("img");m.src="http://www.google.com/images/zippy_plus_sm.gif";m.width=12;m.height=12;m.border=0;m.style.border="none";m.style.verticalAlign="middle";h.appendChild(m);h.appendChild(document.createTextNode(" "));h.appendChild(f);f.appendChild(document.createTextNode(_intlStrings._suggestTranslation));
f.style.direction=_intlStrings._interfaceDirection;f.style.textAlign=_intlStrings._interfaceAlign;f.style.color="#0000CC";f.style.textDecoration="underline";f.style.fontFamily="arial,sans-serif";f.style.fontSize="12px";h.onclick=tn_ke;tn_U(f,"pointer");e.appendChild(d);var l=document.createElement("div"),d=document.createElement("div"),f=document.createElement("span");d.style.direction=_intlStrings._interfaceDirection;d.style.textAlign=_intlStrings._interfaceAlign;d.style.marginTop=tn_M(5);d.style.marginBottom=
tn_M(6);l.appendChild(d);h=document.createElement("img");h.src="http://www.google.com/images/zippy_minus_sm.gif";h.width=12;h.height=12;h.border=0;h.style.border="none";h.style.verticalAlign="middle";d.appendChild(h);d.appendChild(document.createTextNode(" "));d.appendChild(f);f.appendChild(document.createTextNode(_intlStrings._suggestTranslation));f.style.direction=_intlStrings._interfaceDirection;f.style.textAlign=_intlStrings._interfaceAlign;f.style.color="#0000CC";f.style.textDecoration="underline";
f.style.fontFamily="arial,sans-serif";f.style.fontSize="12px";d.onclick=function(){tn_ie(!0)};tn_U(f,"pointer");tn_6=a;a=document.createElement("div");d=document.createElement("form");d.style.marginBottom="0px";d.style.paddingBottom="0px";d.target="google-feedback-frame";d.method="post";d.action=_intlStrings._feedbackUrl;a.appendChild(d);var g=document.createElement("input");g.type="hidden";g.name="gtrans";d.appendChild(g);_intlStrings._reverse?(f=tn_ee(c),c=tn_ee(b)):(c=tn_ee(c),f=tn_ee(b));g.value=
c;b=document.createElement("input");b.type="hidden";b.value=f;b.name="text";d.appendChild(b);b=document.createElement("input");b.name="langpair";b.type="hidden";b.value=_intlStrings._langpair;d.appendChild(b);b=document.createElement("input");b.name="u";b.type="hidden";b.value=tn_le("u");d.appendChild(b);b=document.createElement("input");b.name="oe";b.type="hidden";if(document.charset)b.value=document.charset,d.appendChild(b);else if(document.characterSet)b.value=document.characterSet,d.appendChild(b);
else if(f=tn_le("oe"))d.appendChild(b),b.value=f;var k=document.createElement("textarea");k.rows=3;k.name="utrans";k.value=c;d.appendChild(k);b=document.createElement("div");b.style.direction=_intlStrings._interfaceDirection;b.style.textAlign=tn_ce[_intlStrings._interfaceAlign];b.style.marginTop=tn_M(6);b.style.marginBottom="0px";d.appendChild(b);c=document.createElement("input");c.type="submit";c.value=_intlStrings._submit;b.appendChild(c);var q=document.createElement("div");q.appendChild(document.createElement("hr"));
q.appendChild(document.createTextNode(_intlStrings._suggestThanks));q.style.direction=_intlStrings._interfaceDirection;q.style.textAlign=_intlStrings._interfaceAlign;q.style.fontFamily="arial,sans-serif";q.style.fontSize="12px";q.style.overflow="auto";q.style.marginTop="10px";tn_(q);l.appendChild(a);p.appendChild(l);p.appendChild(q);d.onsubmit=function(){window.setTimeout(function(){tn_(l);tn_Q(q)},1);tn_8=!1;return k.value!=g.value};tn_vd([p,e],function(a){k.style.width=tn_M(a[0].width-6);k.style.padding=
tn_M(2);tn_5.hide();tn_5.u(a[1],[new tn_1d(_intlStrings._originalText,e)]);tn_5.Ka(a[0],[new tn_1d(_intlStrings._originalText,p)]);tn_5.K(tn_6);tn_5.M(!0);tn_5.show()},(document.width||document.body.scrollWidth)/2)}}}}function tn_le(a){for(var b=window.location.search.substring(1),b=b.split("&"),c=0;c<b.length;c++){var d=b[c].split("=");if(d[0].toLowerCase()==a&&0<d.length)return window.unescape(d[1])}return""}
function tn_me(a){tn_ae&&(tn_be=!0,tn_8||(null!==tn_$&&(window.clearTimeout(tn_$),tn_$=null),tn_6==a?(tn_$d=tn_6.style.backgroundColor,tn_6.style.backgroundColor="#E6ECF9"):tn_$=window.setTimeout(function(){tn_je(a)},500)))}function tn_he(a){tn_ae&&(!0!==a&&(tn_be=!1),tn_8||(tn_6&&tn_6.style&&(tn_6.style.backgroundColor=tn_$d),tn_$&&(window.clearTimeout(tn_$),tn_$=null),!0!==a?tn_$=window.setTimeout(tn_ne,250):tn_ne()))}
function tn_ne(){tn_8||(tn_5.hide(),tn_9&&(tn_5.restore(!0),tn_9=!1),tn_6=null)}function tn_ke(){tn_9=tn_8=!0;var a=tn_Id(tn_5,"maximizeend",function(){tn_Jd(a)});tn_5.maximize()}function tn_ie(a){var b=tn_Id(tn_5,"restoreend",function(){tn_Jd(b);tn_9=!1;a?window.setTimeout(function(){tn_8=!1;tn_be||tn_he(!0)},500):(tn_8=!1,tn_be||tn_he(!0))});tn_5.restore()}
function _csi(a,b){var c={};c.sl=a;c.tl=b;var d=window.jstiming.load;d.tick("prt");d.tick("ol");d.name="w";window.jstiming.sn="translate";window.jstiming.report(d,c);try{window.external&&window.external.resT()}catch(e){}}function tn_oe(a){var b=window.onload;window.onload=b?function(){try{a()}catch(c){}b(null)}:a}var _tipon=tn_me,_tipoff=tn_he,_addload=tn_oe,tn_pe=window.jstiming.load;tn_pe.tick("jl");
