#!/bin/bash

# this file needs to exist for main.s to compile
touch apu/spc.bin

apuobjs=""
cpuobjs=""
romtitle=""
# Checks for Existence of RomTitle Argument 1
if [ -z $1 ]
  then
    romtitle="Tracker.smc"
  else
	  romtitle="$1"
fi

echo '# ROM TITLE'
echo "ROMTITLE = $romtitle"
cat MakefileGenerator/compilerheader

#APU
echo '' > /tmp/apu
for file in apu/*.s; do
	echo "$file" > /tmp/filename
	objname=`sed s/"\.s"/"\.o"/ /tmp/filename`
	apuobjs="$apuobjs $objname"
	printf '# %s \n' $file >> /tmp/apu
	wla-spc700 -Mo $file $objname 2>> /tmp/apu
	printf '\t\t$(APU_CC) $(APU_CFLAGS) $< $(OBJDIR)/$@\n' >> /tmp/apu
done

echo '' > /tmp/cpu
for file in cpu/*.s; do
	echo "$file" > /tmp/filename
	objname=`sed s/"\.s"/"\.o"/ /tmp/filename`
	cpuobjs="$cpuobjs $objname"
	printf '# %s \n' $file >> /tmp/cpu
	wla-65816 -Mo $file $objname 2>> /tmp/cpu
	printf '\t\t$(CPU_CC) $(CPU_CFLAGS) $< $(OBJDIR)/$@\n' >> /tmp/cpu
done





echo ''
echo '# It is important that all object files are listed in OFILES'
echo "CPU_OFILES = $cpuobjs"
echo "APU_OFILES = $apuobjs"

cat MakefileGenerator/ObjectInformation
#echo '# Object Information'
#echo 'OBJDIR = obj'
#echo ''
#echo 'CPU_OBJDIR = $(OBJDIR)/cpu'
#echo 'CPU_OBJS = $(addprefix $(OBJDIR)/,$(CPU_OFILES))'
#echo 'APU_OBJDIR = $(OBJDIR)/apu'
#echo 'APU_OBJS = $(addprefix $(OBJDIR)/,$(APU_OFILES))'
#echo ''
#echo 'OFILES = $(CPU_OFILES)'
#echo 'OFILES += $(APU_OFILES)'
#echo ''
#echo 'OBJS = $(CPU_OBJS)'
#echo 'OBJS += $(APU_OBJS)'
#echo '# --'

echo 'VPATH = $(OBJDIR):gfx:gfx/ascii'
echo ''

cat MakefileGenerator/MainRecipes
cat MakefileGenerator/DirectoryCreators
echo ''

echo '#------------------------------'
echo '#APU SIDE'
echo '#------------------------------'

./MakefileGenerator/format apu /tmp/apu
echo '#------------------------------'
echo '#CPU SIDE'
echo '#------------------------------'
./MakefileGenerator/format cpu /tmp/cpu
echo ''
cat MakefileGenerator/clean