dependencies: \
  /Users/bazz/Projects/newmeatball/meatball-code/Meatball/Engine/XCode/Engine/../../net.cpp \
  /Users/bazz/Projects/newmeatball/meatball-code/Meatball/Engine/XCode/Engine/../../include/SDL_ep.h \
  /Library/Frameworks/SDL.framework/Headers/SDL.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_main.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_stdinc.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_config.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_platform.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_config_macosx.h \
  /Library/Frameworks/SDL.framework/Headers/begin_code.h \
  /Library/Frameworks/SDL.framework/Headers/close_code.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_audio.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_error.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_endian.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_mutex.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_thread.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_rwops.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_cdrom.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_cpuinfo.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_events.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_active.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_keyboard.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_keysym.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_mouse.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_video.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_joystick.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_quit.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_loadso.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_timer.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_version.h \
  /Users/bazz/Projects/newmeatball/meatball-code/Meatball/Engine/XCode/Engine/../../include/framerate.h \
  /Users/bazz/Projects/newmeatball/meatball-code/Meatball/Engine/XCode/Engine/../../include/image.h \
  /Library/Frameworks/SDL_image.framework/Headers/SDL_image.h \
  /Users/bazz/Projects/newmeatball/meatball-code/Meatball/Engine/XCode/Engine/../../include/audio.h \
  /Library/Frameworks/SDL_mixer.framework/Headers/SDL_mixer.h \
  /Library/Frameworks/SDL.framework/Headers/SDL_types.h \
  /Users/bazz/Projects/newmeatball/meatball-code/Meatball/Engine/XCode/Engine/../../include/video.h \
  /Users/bazz/Projects/newmeatball/meatball-code/Meatball/Engine/XCode/Engine/../../include/sprite.h \
  /Users/bazz/Projects/newmeatball/meatball-code/Meatball/Engine/XCode/Engine/../../include/gfx.h \
  /Library/Frameworks/SGE.framework/Headers/SGE.h \
  /Library/Frameworks/SGE.framework/Headers/sge_surface.h \
  /Library/Frameworks/SGE.framework/Headers/sge_internal.h \
  /Library/Frameworks/SGE.framework/Headers/sge_config.h \
  /Library/Frameworks/SGE.framework/Headers/sge_primitives.h \
  /Library/Frameworks/SGE.framework/Headers/sge_misc.h \
  /Library/Frameworks/SGE.framework/Headers/sge_tt_text.h \
  /Library/Frameworks/SGE.framework/Headers/sge_bm_text.h \
  /Library/Frameworks/SGE.framework/Headers/sge_textpp.h \
  /Library/Frameworks/SGE.framework/Headers/sge_shape.h \
  /Library/Frameworks/SGE.framework/Headers/sge_collision.h \
  /Library/Frameworks/SGE.framework/Headers/sge_blib.h \
  /Library/Frameworks/SGE.framework/Headers/sge_rotation.h \
  /Users/bazz/Projects/newmeatball/meatball-code/Meatball/Engine/XCode/Engine/../../include/misc.h \
  /Users/bazz/Projects/newmeatball/meatball-code/Meatball/Engine/XCode/Engine/../../include/font.h \
  /Library/Frameworks/SDL_ttf.framework/Headers/SDL_ttf.h \
  /Users/bazz/Projects/newmeatball/meatball-code/Meatball/Engine/XCode/Engine/../../include/img_manager.h \
  /Users/bazz/Projects/newmeatball/meatball-code/Meatball/Engine/XCode/Engine/../../include/snd_manager.h \
  /Users/bazz/Projects/newmeatball/meatball-code/Meatball/Engine/XCode/Engine/../../include/net.h \
  /Library/Frameworks/SDL_net.framework/Headers/SDL_net.h
