/*
 * MidiSuite.java
 * JUnit based test
 *
 *  libjdkmidijava Java Class Library for MIDI
 *
 *  https://clicker.jdkoftinoff.com/projects/trac/jdks/wiki/libjdkmidijava
 *
 *  Copyright (C) 2006  J.D. Koftinoff Software, Ltd.
 *  www.jdkoftinoff.com
 *  jeffk@jdkoftinoff.com
 *
 *  *** RELEASED UNDER THE GNU GENERAL PUBLIC LICENSE (GPL) September 11, 2006 ***
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

package com.jdkoftinoff.midi;

import junit.framework.*;

/**
 *
 * @author jeffk
 */
public class MidiSuite extends TestCase {
    
    public MidiSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("MidiSuite");
        suite.addTest(com.jdkoftinoff.midi.MIDISystemExclusiveTest.suite());
        suite.addTest(com.jdkoftinoff.midi.MIDIMessageTest.suite());
        suite.addTest(com.jdkoftinoff.midi.MIDITest.suite());
        suite.addTest(com.jdkoftinoff.midi.MIDITimedMessageTest.suite());
        return suite;
    }
    
}
