all:
	tasm -07 -b twosamples.asm spc.obj

	size spc.obj
	wla music
#	snes music.smc
#	zsnes music.smc
spc:
	tasm -07 -b twosamples.asm spc.obj
	size spc.obj
	size piano.brr
asm:
	wla music
	snes music.smc
#	zsnes music.smc
